### ISSUE TITLE
Ignition's "wrote ssh authorized keys file" report accumulates in `/etc/issue`

### ISSUE THREAD

**Issue by PhrozenByte** [coreos/fedora-coreos-tracker#1033]
**Describe the bug**
When re-provisioning a FCOS instance with a persistent `/var` (i.e. running `coreos-installer` while keeping `/var` of a previous FCOS instance, e.g. via some non-FCOS live system) Ignition will append notices like

```
wrote ssh authorized keys file for user: %s
```

to `/etc/issue.d/30_ssh_authorized_keys.issue`. Since this file isn't truncated first, the messages accumulate when re-provisioning the instance (i.e. the message is shown `n+1` times when the system has been reprovisioned `n` times before).

Note: The keys itself don't accumulate because Ignition will always overwrite `~/.ssh/authorized_keys` as a whole.

**Reproduction steps**
Re-provision FCOS with a persistent `/var` and with some SSH authorized keys (see Butane config below).

How you do this shouldn't really matter, I re-provision my instances like this:

1. Install FCOS on `/dev/sda`
2. Boot into some non-CoreOS live system (e.g. Debian, openSUSE, …) and make sure Rust and `cargo` are installed. Run `cargo install coreos-installer`
3. `coreos-installer --ignition-file /path/to/my/config.ign /dev/sda`
4. `reboot`

**Expected behavior**
Ignition reports that it has written a user's SSH authorized keys only once. `/etc/issue.d/30_ssh_authorized_keys.issue` should be:

```
Ignition: wrote ssh authorized keys file for user: core
```

**Actual behavior**
Ignition appends the new message to the previous file, showing the message multiple times (matching how often the instance was re-provisioned before). `/etc/issue.d/30_ssh_authorized_keys.issue` is (when re-provisioning for the first time):

```
Ignition: wrote ssh authorized keys file for user: core
Ignition: wrote ssh authorized keys file for user: core
```

**System details**
 - Bare Metal
 - FCOS 35.20211029.3.0

**Ignition config**
Butane config:

```yml
variant: fcos
version: 1.4.0
storage:
  disks:
    - device: /dev/sda
      wipe_table: false
      partitions:
        - number: 4
          label: root
          size_mib: 8192
          wipe_partition_entry: true
          resize: true
        - number: 5
          label: var
          size_mib: 0
  filesystems:
    - device: /dev/disk/by-partlabel/var
      format: ext4
      path: /var
      with_mount_unit: true
passwd:
  users:
    - name: core
      ssh_authorized_keys:
        - key1
```

**Additional information**
A possible solution might be to simply truncate `/etc/issue.d/30_ssh_authorized_keys.issue` before creating the SSH authorized keys files.
