### ISSUE TITLE
Error resizing LUKS rootfs

### ISSUE THREAD

**Issue by sedlund** [coreos/fedora-coreos-tracker#1077]
I didnt see this documented as a limitation, but ignition fails with

`ignition-ostree-growfs 'nothing to read on input'`

Seems to come from:  https://github.com/coreos/fedora-coreos-config/blob/532fd714e4fff8ee6f6f77cd09f4889560512299/overlay.d/05core/usr/lib/dracut/modules.d/40ignition-ostree/ignition-ostree-growfs.sh#L88

Here is an ignition

```yaml
variant: fcos
version: 1.4.0
passwd:
  users:
    - name: core
      password_hash: $6$ub
      ssh_authorized_keys:
        - ssh-rsa AAAAB3Nz

boot_device:
  luks:
    tpm2: true

storage:

  disks:
    - device: /dev/nvme0n1
      partitions:
        - label: ceph
          # 12G + 1 MiB for the partition table, 384 for `/boot`, 127 for `/boot/efi`
          start_mib: 12801
          size_mib: 0

  filesystems:
    - device: /dev/mapper/root
      format: btrfs
      label: root
      mount_options:
        - compress=zstd:1
      wipe_filesystem: true
```

**Comment by sedlund** [comment]
My apologies, I originally got the error using luks key_file not tpm2.

Using https://console.aws.amazon.com/ec2/home?region=us-east-1#launchAmi=ami-0ebf4b94cc66b73f2  on t3a.medium.

I will try the partitioning as suggested.

Attached: [rdsosreport.txt.gz](https://github.com/coreos/fedora-coreos-tracker/files/7931120/rdsosreport.txt.gz)


Here is the correct ignition:

```yaml

variant: fcos
version: 1.4.0
passwd:
  users:
    - name: core
      password_hash: $6$ubjP0
      ssh_authorized_keys:
        - ssh-rsa AAAA

storage:

  disks:
    - device: /dev/nvme0n1
      partitions:
        - label: ceph
          # 12G + 1 MiB for the partition table, 384 for `/boot`, 127 for `/boot/efi`
          start_mib: 12801
          size_mib: 0

  luks:
    - name: root
      label: luks-root
      devi

      wipe_volume: true
      # using key_file on a rootfs will ask for pass on boot
      key_file:
        inline: "canttellyou"

  filesystems:
    - device: /dev/mapper/root
      format: btrfs
      label: root
      mount_options:
        - compress=zstd:1
      wipe_filesystem: true
```
