### ISSUE TITLE
Improve deny-list between FCOS and RHCOS

### ISSUE THREAD

**Issue by ravanelli** [coreos/fedora-coreos-tracker#1115]
**Describe the enhancement**
Today if we want to skip some test in RHCOs we need to have it added  in the openshift/os  deny-list , FCOS also have a deny-list. 
Would be nice to have these tests shared/merged so we don't need to add them in both places. If a test is in the FCOS deny-list it willb be also be valid for RHCOS.

**Comment by dustymabe** [comment]
In this case I think we should take a "default not shared, but ability to share" approach. For example an entry like:

```
- pattern: ext.config.kdump.crash                                                                                                     
  tracker: https://github.com/coreos/fedora-coreos-tracker/issues/1075                                                                
  arches:                                                                                                                             
    - aarch64
```

Would just apply to `fcos`, but an entry like:

```
- pattern: ext.config.kdump.crash                                                                                                     
  tracker: https://github.com/coreos/fedora-coreos-tracker/issues/1075
  distros:
    - fcos
    - rhcos                                                                
  arches:                                                                                                                             
    - aarch64
```

Would apply to `rhcos` too. The default would be to just apply to `fcos` but we could request sharing by adding `rhcos` into a `distros` section.
