### ISSUE TITLE
`rdcore bind-boot` fails with "Error: Expected one vendor dir"

### ISSUE THREAD

**Issue by iluminae** [coreos/fedora-coreos-tracker#1116]
**Describe the bug**
After install via PXE on some host models, encountering: `Error: Expected one vendor dir on /dev/sda2, got 2` after reboot. I have 4 hosts, 2 poweredge r415 and 2 poweredge r210 II. This issue is happening on both r210s, but the same process works on the r415s.

**Reproduction steps**
1. PXE boot server with kernel and initrd and kernel commandline: `console=ttyS1,115200n8 coreos.live.rootfs_url=%s coreos.inst.install_dev=%s coreos.inst.ignition_url=%s`
2. Tried install_dev at /dev/disk/by-id and simply /dev/sdX - both do the same.

**Expected behavior**
After reboot, I expect it to boot.

**Actual behavior**
 Install appears fine, triggers reboot, boots with no output and reboots again, then boots into an error: `coreos-boot-edit[900]: Error: Expected one vendor dir on /dev/sda2, got 2`.

**System details**
 - Bare Metal (PXE)
 - Fedora CoreOS version 35.20220213.3.0
 - Dell Poweredge r210 II

**Ignition config**
```
variant: fcos                                                                                                                                                                        
version: 1.4.0
kernel_arguments:
  should_exist:
  - mitigations=off
  - selinux=0
  - console=ttyS1,115200n8
  should_not_exist:
  - console=ttyS0,115200n8
  - mitigations=auto,nosmt
passwd:
  users:
  - name: REDACTED
    password_hash: REDACTED
    ssh_authorized_keys:
    - REDACTED
    groups:
    - "sudo"
    - "wheel"
storage:
  files:
  - path: /etc/hostname
    mode: 420
    overwrite: true
    contents:
      inline: "dosd-00"
  - path: /etc/ssh/sshd_config.d/20-enable-passwords.conf
    mode: 0644
    overwrite: true
    contents:
      inline: |
        PasswordAuthentication yes
  - path: /etc/NetworkManager/system-connections/eno2.nmconnection
    mode: 0600
    overwrite: true
    contents:
      inline: |
        [connection]
        id=eno2
        type=ethernet
        interface-name=eno2
        [ethernet]
        mtu=9000
        [ipv4]
        address1=192.168.6.0/24
        dns-search=
        may-fail=false
        method=manual
        never-default=true
        route1=192.168.6.0/24,192.168.6.0
```
