### ISSUE TITLE
iptables.service in ignition, with /etc/sysconfig/iptables is loading first time, but not subsequent boots.

### ISSUE THREAD

**Issue by millerthegorilla** [coreos/fedora-coreos-tracker#1127]
**Describe the bug**
I created a config.ign with iptables.service switched on, and with a config added to /etc/sysconfig/iptables and the config is loading the first boot, but not subsequent boots.
```Systemctl status iptables.service``` is reporting that the unit is enabled but inactive.
```systemctl start iptables.service``` installs the config from /etc/sysconfig/iptables, and changes the status to active.

**Reproduction steps**
1. create a config.ign from a butane config as follows:
```
systemd:
  units:
    - name: iptables.service
      enabled: true
storage:
  files:
    - path: /etc/sysconfig/iptables
      mode: 0644
      overwrite: true
      contents:
        inline: |
          *filter
          :INPUT DROP [0:0]
          :FORWARD DROP [0:0]
          :OUTPUT ACCEPT [0:0]
          -A INPUT -i lo -j ACCEPT
          -A INPUT -i eth1 -j ACCEPT
          -A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
          -A INPUT -p tcp -m tcp --dport 22 -j ACCEPT
          -A INPUT -p tcp -m tcp --dport 80 -j ACCEPT
          -A INPUT -p tcp -m tcp --dport 443 -j ACCEPT
          -A INPUT -p icmp -m icmp --icmp-type 0 -j ACCEPT
          -A INPUT -p icmp -m icmp --icmp-type 3 -j ACCEPT
          -A INPUT -p icmp -m icmp --icmp-type 11 -j ACCEPT
          COMMIT
```
2.  install coreos
3. boot, - run ```iptables -S``` config is displayed as above
4. reboot - run ```iptables -S``` config has returned to standard, with all ports open etc.

**Expected behavior**
I expected the locked down iptables firewall as per the config in the butane file above.
**Actual behavior**
A clear and concise description of what actually happened.
subsequent boots after first boot did not load config.
**System details**
 - Bare Metal
 - raspberry pi 4b
 - Fedora CoreOS version
latest
**Ignition config**
```yaml
variant: fcos
version: 1.4.0
passwd:
  users:
    - name: core
      ssh_authorized_keys:
            - ssh-ed25519 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx bob@bob.com
systemd:
  units:
    - name: iptables.service
      enabled: true
storage:
  files:
    - path: /etc/sysconfig/iptables
      mode: 0644
      overwrite: true
      contents:
        inline: |
          *filter
          :INPUT DROP [0:0]
          :FORWARD DROP [0:0]
          :OUTPUT ACCEPT [0:0]
          -A INPUT -i lo -j ACCEPT
          -A INPUT -i eth1 -j ACCEPT
          -A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
          -A INPUT -p tcp -m tcp --dport 22 -j ACCEPT
          -A INPUT -p tcp -m tcp --dport 80 -j ACCEPT
          -A INPUT -p tcp -m tcp --dport 443 -j ACCEPT
          -A INPUT -p icmp -m icmp --icmp-type 0 -j ACCEPT
          -A INPUT -p icmp -m icmp --icmp-type 3 -j ACCEPT
          -A INPUT -p icmp -m icmp --icmp-type 11 -j ACCEPT
          COMMIT
```

Please attach the Butane config or Ignition config used to provision your system. Be sure to sanitize any private data. If not using Butane to generate your Ignition config, does the Ignition config pass validation using [ignition-validate](https://coreos.github.io/ignition/getting-started/#config-validation)?

**Additional information**
reported on matrix chat, requested to post issue.
