### ISSUE TITLE
Unable to install Fedora CoreOS on a Netcup VPS

### ISSUE THREAD

**Issue by dylangerdaly** [coreos/fedora-coreos-tracker#1135]
**Describe the bug**
Unable to install Fedora CoreOS (Stable v35.20220227.3.0) on a NetCup.eu VPS

**Ignition config**
```
version: "1.4.0"
variant: fcos
passwd:
  users:
    - name: director
      password_hash: "X"
      ssh_authorized_keys:
        - ssh-ed25519 X
      groups: [ 'wheel' ]
storage:
  disks:
    - device: /dev/vda
      wipe_table: true
      partitions:
        - size_mib: 47683.715820313
          label: root
          number: 1
          resize: true
        - size_mib: 4768.371582031
          label: swap
          number: 2
        - size_mib: 0
          label: data
          number: 3
  filesystems:
    - device: /dev/disk/by-partlabel/root
      wipe_filesystem: true
      format: xfs
      label: root
    - device: /dev/disk/by-partlabel/swap
      format: swap
      wipe_filesystem: true
      with_mount_unit: true
    - device: /dev/disk/by-partlabel/data
      wipe_filesystem: true
      format: ext4
      label: data
```

![Screenshot_2022-03-20_15-18-19](https://user-images.githubusercontent.com/7969682/159149593-4540a4b4-73be-49c3-a4a4-be8e0ef014c6.png)

I think it's either a legacy boot (BIOS) bug or a Clock bug

**Additional information**
It appears something break somewhere, I can't get logging because the VPS Console dosen't allow scrolling.

**Comment by dustymabe** [comment]
In this case the boot is failing for some reason and then there is another failure when trying to get to `emergency.target`. Unfortunately we never see the original reason the boot failed.

There have been other cases similar to this:

- https://discussion.fedoraproject.org/t/first-boot-error-failed-to-set-up-standard-input-inappropriate-ioctl-for-device/29181
- https://github.com/coreos/fedora-coreos-tracker/issues/943#issuecomment-909279315

They mostly boil down to the `console` not being set right (i.e. trying use `ttyS0` as the console when no serial console exists). Maybe try to [remove the serial console entry when you do the install](https://docs.fedoraproject.org/en-US/fedora-coreos/emergency-shell/#_configuring_console_during_installation).

**Comment by dylangerdaly** [comment]
I've made some progress, the issue is related to defining root, I think there's a current bug that breaks if you try to define root.

If I totally remove the partitions and filesystem definitions it installs correctly.

I'm not sure if it's a bug or "feature" to not be able to define the rootfs size or filesystem

**Comment by dustymabe** [comment]
You could try installing in a local VM to test things out before you try on the VPS. One thing that I see that stands out (I'm not sure if it's technically supported or not) is the floating point numbers used for sizes:

```
       - size_mib: 47683.715820313
```

I've always used whole numbers.

**Comment by dylangerdaly** [comment]
I've tried even simply setting ext4 as the fs with

```
  filesystems:
    - device: /dev/disk/by-partlabel/root
      wipe_filesystem: true
      format: ext4
      label: root
```

And it fails in the exact same place, I believe `/dev/disk/by-partlabel/root` is breaking it somewhere

**Comment by dustymabe** [comment]
I think you need to use `partition: 4` if you're trying to modify the existing parition with label `root` in the disk image. See https://discussion.fedoraproject.org/t/ignition-partition-layout-for-coreos/17318/4?u=dustymabe for context.

**Comment by dylangerdaly** [comment]
Interesting, that has semi-worked, it looks like it's duplicated the root partition

```
Device        Start        End    Sectors   Size Type
/dev/vda1      2048       4095       2048     1M BIOS boot
/dev/vda2      4096     264191     260096   127M EFI System
/dev/vda3    264192    1050623     786432   384M Linux filesystem
/dev/vda4   1050624    5134302    4083679   1.9G Linux filesystem
/dev/vda5   5134336   21911551   16777216     8G Linux filesystem
/dev/vda6  21911552   38688767   16777216     8G Linux filesystem
/dev/vda7  38688768 1258291166 1219602399 581.6G Linux filesystem
```

Thank you for your help, I think potentially it's running something twice

**Comment by dylangerdaly** [comment]
Interesting, it appears to be if you set 50GB for the root partition, it'll fail

**Comment by dylangerdaly** [comment]
Okay, narrowed it down to `wipe_table`, when this is set to true it breaks everything.

**Comment by bgilbert** [comment]
Right, if you set `wipe_table: true` on the boot disk, you're responsible for redefining all of the system partitions.  You may choose to do that in the config, but it does leave you responsible for matching the OS defaults, so we generally recommend that you use `wipe_table: false` for the boot disk.

**Comment by dylangerdaly** [comment]
Ah I see, it ignored what I set for `root` and made it 2GB, as a work around I booted back into the ISO, and deleted all of the duplicate partitions, resized partition number 4 manually with `fdisk` and `xfs_growfs`.

**Comment by bgilbert** [comment]
Could you post the current version of your config?

**Comment by dylangerdaly** [comment]
```
version: "1.4.0"
variant: fcos
passwd:
  users:
    - name: director
      password_hash: "X"
      ssh_authorized_keys:
        - ssh-ed25519 X
      groups: [ 'wheel' ]
storage:
  disks:
    - device: /dev/vda
      wipe_table: false
      partitions:
        - label: root
          size_mib: 51200
        - label: data
  filesystems:
    - device: /dev/disk/by-partlabel/root
      format: xfs
      label: root
      wipe_filesystem: true
    - device: /dev/disk/by-partlabel/data
      wipe_filesystem: true
      format: ext4
      label: data
  files:
    - path: /etc/sudoers.d/passwordless
      contents:
        inline: |
          %wheel  ALL=(ALL) NOPASSWD: ALL
      mode: 0440
    - path: /etc/NetworkManager/system-connections/ens3.nmconnection
      mode: 0600
      overwrite: true
      contents:
        inline: |
          [connection]
          type=ethernet
          interface-name=ens3

          [ipv4]
          method=manual
          addresses=X
          gateway=X
          dns=X

          [ipv6]
          addr-gen-mode=stable-privacy
          address1=X
          dns-search=
          method=manual
    - path: /etc/hostname
      mode: 0644
      overwrite: true
      contents:
        inline: X
```

**Comment by bgilbert** [comment]
Okay, right.  You need:

```yaml
      partitions:
        - label: root
          number: 4
          size_mib: 51200
          resize: true
        - label: data
```
