### ISSUE TITLE
raid1 boot_device mirroring with partitions > 2TB breaks install

### ISSUE THREAD

**Issue by stephankoelle** [coreos/fedora-coreos-tracker#1194]
**Describe the bug**
When using raid1 boot_device mirroring together with partition sizes > 2TB there is file corruption.

**Reproduction steps**
1. using a host with two NVMEs > 2 TB

```
variant: fcos
version: 1.4.0
boot_device:
  mirror:
    devices:
      - /dev/nvme0n1
      - /dev/nvme1n1
```
3. `/usr/bin/rpm-ostree install --apply-live --allow-inactive --idempotent htop`
4.  error: Running tmpfiles for /run and /var: Running systemd worker: exit status: 127

After that system is broker, no further ssh login possible (everything gives "invalid ELF header")

**Expected behavior**
boot_device mirroring should work with "arbitrary" sizes partition

**Actual behavior**
System is completely broker, needs re-install where partition is bigger then "size_mib: 2097000". Have not tested the exact value, OK: size_mib: 2097000 , failure: size_mib: 2621000

**System details**
 - Bare Metal & QEMU (with mounted NVMEs)
 - Fedora CoreOS 35.20220424.3.0"

**Ignition config**
```
variant: fcos
version: 1.4.0
boot_device:
  mirror:
    devices:
      - /dev/sda
      - /dev/sdb

```
**Additional information**
Work around, reduce size of root partition

```
storage:
  disks:
    - device: /dev/nvme0n1
      partitions:
        - label: root-1
          #defect 2621000 => error: Running tmpfiles for /run and /var: Running systemd worker: exit status: 127
          #ok 2097000
          size_mib: 2097000
    - device: /dev/nvme1n1
      partitions:
        - label: root-2
          size_mib: 2097000
```
Forum link with more information: https://discussion.fedoraproject.org/t/fedora-coreos-installation-works-preparing-etc-invalid-byte-sequence-in-conversion-input-on-rpm-ostree-install-afterwards/38772/14
