### ISSUE TITLE
Cannot install custom kernel package

### ISSUE THREAD

**Issue by amirgon** [coreos/fedora-coreos-tracker#1196]
**Describe the bug**

Trying to replace kernel base packages with a custom kernel - fails with errors on fedora-coreos 35.

---

### Attempt 1 - try to remove existing kernel packages:

**Reproduction steps**

`sudo rpm-ostree override replace ./kernel-5.16.13-200.nb.fc35.x86_64.rpm  ./kernel-core-5.16.13-200.nb.fc35.x86_64.rpm ./kernel-modules-5.16.13-200.nb.fc35.x86_64.rpm --remove=kernel --remove=kernel-core --remove=kernel-modules`

**Expected behavior**
No errors

**Actual behavior**
rpm-ostree reports an error: `error: Base packages not marked to be removed: kernel-core, kernel, kernel-modules`

---

### Attempt 2 - keep existing kernel packages:

**Reproduction steps**

`sudo rpm-ostree override replace kernel-5.16.13-200.nb.fc35.x86_64.rpm kernel-core-5.16.13-200.nb.fc35.x86_64.rpm kernel-modules-5.16.13-200.nb.fc35.x86_64.rpm`

**Expected behavior**
No errors

**Actual behavior**

rpm-ostree succeeds, but after reboot `rpm-ostree status` reports an error: `error: Installing kernel: regfile copy: No space left on device`
(boot partition is not large enough?)

**System details**
 - QEMU
 - `fedora-coreos-35.20220313.3.1-qemu.x86_64.qcow2`
 - Also tried: `fedora-coreos-35.20220424.3.0-qemu.x86_64.qcow2`

---

**Ignition config**

**Additional information**

The custom kernel is based on `kernel-5.16.13-200.fc35.src.rpm` with a small patch applied and `%define buildid .nb`.  
Built with `rpmbuild -bb --with baseonly --without debuginfo --target=x86_64 kernel.spec`

Related: https://discussion.fedoraproject.org/t/installing-custom-kernel-on-fedora-coreos/39138

**Comment by travier** [comment]
Do we have an example to grow /boot via Ignition? I don't know if we have support for that in Ignition.

**Comment by bgilbert** [comment]
@travier This should work:

```yaml
variant: fcos
version: 1.4.0
storage:
  disks:
    - device: /dev/sda
      partitions:
        - label: boot
          number: 3
          # Resize to 600 MiB
          size_mib: 600
          wipe_partition_entry: true
        - label: root
          number: 4
          wipe_partition_entry: true
  filesystems:
    - device: /dev/disk/by-partlabel/boot
      format: ext4
      label: boot
      wipe_filesystem: true
    - device: /dev/disk/by-partlabel/root
      format: xfs
      label: root
      wipe_filesystem: true
```

We may not want to recommend this too heavily, though, since it makes some assumptions about the underlying image.
