### ISSUE TITLE
Include necessary tpm2_createpolicy module in the initramfs

### ISSUE THREAD

**Issue by freedge** [coreos/fedora-coreos-tracker#1255]
**Describe the bug**
When trying to create a luks boot device using tpm2 and binding against pcrs, it fails with "tpm2_createpolicy: command not found"
as noticed on [discussion](https://discussion.fedoraproject.org/t/coreos-plans-for-measured-boot/40537/5?u=frigo)

**Reproduction steps**
1. use attached butane config
2. boot a VM

**Expected behavior**
should create a luks device

**Actual behavior**
``` /usr/bin/clevis-encrypt-tpm2: line 186: tpm2_createpolicy: command not found```

**System details**
 - QEMU with tpm2 device passthrough
 - fedora-coreos-36.20220618.3.1-qemu.x86_64.qcow2

**Ignition config**
```
variant: fcos
version: 1.4.0
storage:
  filesystems:
    - device: /dev/mapper/root
      format: xfs
      label: root
      wipe_filesystem: true
  luks:
    - clevis:
        custom:
          needs_network: false
          pin: tpm2
          config: '{"pcr_bank":"sha1","pcr_ids":"0,7"}'
      device: /dev/disk/by-partlabel/root
      label: luks-root
      name: root
      wipe_volume: true
```

**Additional information**
