### ISSUE TITLE
SELinux issues deploying rook on CoreOS

### ISSUE THREAD

**Issue by mdbooth** [coreos/fedora-coreos-tracker#1314]
**Describe the bug**
Apologies if this is the wrong place for SELinux policy. Happy to refile this elsewhere if appropriate.

I am trying to deploy rook v1.10.3 on kubernetes 1.25 deployed by kubeadm. The OS is CoreOS 36. The mon service fails to start due to multiple SELinux permission issues. I have included the problem deployment at the end of this issue, but the issue seems to step from use of hostPath.

The deployment declares the following hostPath volumes:

```yaml
      - hostPath:
          path: /var/lib/rook/rook-ceph/log
          type: ""
        name: rook-ceph-log
      - hostPath:
          path: /var/lib/rook/rook-ceph/crash
          type: ""
        name: rook-ceph-crash
      - hostPath:
          path: /var/lib/rook/mon-a/data
          type: ""
```

It creates files and modifies permissions in 2 initContainers before starting the mon container. However, it is prevented by SELinux. The following module appears to make it work for me:

```
module rook-selinux 1.0;

require {
        type container_t;
        type container_var_lib_t;
        class dir { create getattr setattr };
        class file { create getattr setattr lock open read rename unlink write };
}

#============= container_t ==============
allow container_t container_var_lib_t:dir { create getattr setattr };

allow container_t container_var_lib_t:file { create getattr setattr lock open rename unlink read write };
```

However, the scope of this change seems quite large. I don't have enough context to know if this deployment should be doing something entirely different from an SELinux pov.

**Reproduction steps**
1. Install kubernetes 1.25 with kubeadm and crio
2. Leave SELinux in enforcing
3. From https://github.com/rook/rook/tree/v1.10.3/deploy/examples:
  $ kubectl apply -f crds.yaml -f common.yaml -f operator.yaml -f cluster-test.yaml

**Expected behavior**
Clustered storage goodness.

**Actual behavior**
Goodness denied.

**System details**
 - Bare Metal
 - Fedora CoreOS version:
```
# rpm-ostree status
State: idle
AutomaticUpdatesDriver: Zincati
  DriverState: active; periodically polling for updates (last checked Sat 2022-10-08 11:23:32 UTC)
Deployments:
* fedora:fedora/x86_64/coreos/stable
                  Version: 36.20220918.3.0 (2022-10-03T18:34:38Z)
               BaseCommit: cfb20668fc8129a97e097867ec6c3ded67c5f51d69a294a2d238c89a6530f9dc
             GPGSignature: Valid signature by 53DED2CB922D8B8D9E63FD18999F7CBF38AB71F4
          LayeredPackages: cri-o kubeadm-1.25.2 kubectl-1.25.2 kubelet-1.25.2

  fedora:fedora/x86_64/coreos/stable
                  Version: 36.20220906.3.2 (2022-09-22T13:44:19Z)
               BaseCommit: a8b4dda3092f20335cd3270db131f782edf5cad8b11b927283b3da2af42463e6
             GPGSignature: Valid signature by 53DED2CB922D8B8D9E63FD18999F7CBF38AB71F4
          LayeredPackages: cri-o kubeadm-1.25.2 kubectl-1.25.2 kubelet-1.25.2
```

**Additional information**

```
# cat /etc/dnf/modules.d/cri-o.module
[cri-o]
name=cri-o
stream=1.25
profiles=
state=enabled
```

```
# cat /etc/yum.repos.d/kubernetes.repo
[kubernetes]
name=Kubernetes
baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-$basearch
enabled=1
gpgcheck=1
gpgkey=https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
```

Ceph mon deployment (some metadata fields omitted for brevity):
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rook-ceph-mon-a
  namespace: rook-ceph
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: rook-ceph-mon
      ceph_daemon_id: a
      mon: a
      mon_cluster: rook-ceph
      rook_cluster: rook-ceph
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        <snip>
      name: rook-ceph-mon-a
      namespace: rook-ceph
    spec:
      affinity: {}
      containers:
      - args:
        - --fsid=3f311962-5289-45d6-b38d-18b01f9082dd
        - --keyring=/etc/ceph/keyring-store/keyring
        - --log-to-stderr=true
        - --err-to-stderr=true
        - --mon-cluster-log-to-stderr=true
        - '--log-stderr-prefix=debug '
        - --default-log-to-file=false
        - --default-mon-cluster-log-to-file=false
        - --mon-host=$(ROOK_CEPH_MON_HOST)
        - --mon-initial-members=$(ROOK_CEPH_MON_INITIAL_MEMBERS)
        - --id=a
        - --setuser=ceph
        - --setgroup=ceph
        - --foreground
        - --public-addr=10.108.46.208
        - --setuser-match-path=/var/lib/ceph/mon/ceph-a/store.db
        - --public-bind-addr=$(ROOK_POD_IP)
        command:
        - ceph-mon
        env:
        - name: CONTAINER_IMAGE
          value: quay.io/ceph/ceph:v17
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: POD_MEMORY_LIMIT
          valueFrom:
            resourceFieldRef:
              divisor: "0"
              resource: limits.memory
        - name: POD_MEMORY_REQUEST
          valueFrom:
            resourceFieldRef:
              divisor: "0"
              resource: requests.memory
        - name: POD_CPU_LIMIT
          valueFrom:
            resourceFieldRef:
              divisor: "1"
              resource: limits.cpu
        - name: POD_CPU_REQUEST
          valueFrom:
            resourceFieldRef:
              divisor: "0"
              resource: requests.cpu
        - name: ROOK_CEPH_MON_HOST
          valueFrom:
            secretKeyRef:
              key: mon_host
              name: rook-ceph-config
        - name: ROOK_CEPH_MON_INITIAL_MEMBERS
          valueFrom:
            secretKeyRef:
              key: mon_initial_members
              name: rook-ceph-config
        - name: ROOK_POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        image: quay.io/ceph/ceph:v17
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - env
            - -i
            - sh
            - -c
            - |-
              outp="$(ceph --admin-daemon /run/ceph/ceph-mon.a.asok mon_status 2>&1)"
              rc=$?
              if [ $rc -ne 0 ]; then
                echo "ceph daemon health check failed with the following output:"
                echo "$outp" | sed -e 's/^/> /g'
                exit $rc
              fi
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        name: mon
        ports:
        - containerPort: 3300
          name: tcp-msgr2
          protocol: TCP
        - containerPort: 6789
          name: tcp-msgr1
          protocol: TCP
        resources: {}
        securityContext:
          privileged: false
        startupProbe:
          exec:
            command:
            - env
            - -i
            - sh
            - -c
            - |-
              outp="$(ceph --admin-daemon /run/ceph/ceph-mon.a.asok mon_status 2>&1)"
              rc=$?
              if [ $rc -ne 0 ]; then
                echo "ceph daemon health check failed with the following output:"
                echo "$outp" | sed -e 's/^/> /g'
                exit $rc
              fi
          failureThreshold: 6
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/ceph
          name: rook-config-override
          readOnly: true
        - mountPath: /etc/ceph/keyring-store/
          name: rook-ceph-mons-keyring
          readOnly: true
        - mountPath: /var/log/ceph
          name: rook-ceph-log
        - mountPath: /var/lib/ceph/crash
          name: rook-ceph-crash
        - mountPath: /var/lib/ceph/mon/ceph-a
          name: ceph-daemon-data
        workingDir: /var/log/ceph
      dnsPolicy: ClusterFirst
      initContainers:
      - args:
        - --verbose
        - --recursive
        - ceph:ceph
        - /var/log/ceph
        - /var/lib/ceph/crash
        - /var/lib/ceph/mon/ceph-a
        command:
        - chown
        image: quay.io/ceph/ceph:v17
        imagePullPolicy: IfNotPresent
        name: chown-container-data-dir
        resources: {}
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/ceph
          name: rook-config-override
          readOnly: true
        - mountPath: /etc/ceph/keyring-store/
          name: rook-ceph-mons-keyring
          readOnly: true
        - mountPath: /var/log/ceph
          name: rook-ceph-log
        - mountPath: /var/lib/ceph/crash
          name: rook-ceph-crash
        - mountPath: /var/lib/ceph/mon/ceph-a
          name: ceph-daemon-data
      - args:
        - --fsid=3f311962-5289-45d6-b38d-18b01f9082dd
        - --keyring=/etc/ceph/keyring-store/keyring
        - --log-to-stderr=true
        - --err-to-stderr=true
        - --mon-cluster-log-to-stderr=true
        - '--log-stderr-prefix=debug '
        - --default-log-to-file=false
        - --default-mon-cluster-log-to-file=false
        - --mon-host=$(ROOK_CEPH_MON_HOST)
        - --mon-initial-members=$(ROOK_CEPH_MON_INITIAL_MEMBERS)
        - --id=a
        - --setuser=ceph
        - --setgroup=ceph
        - --public-addr=10.108.46.208
        - --mkfs
        command:
        - ceph-mon
        env:
        - name: CONTAINER_IMAGE
          value: quay.io/ceph/ceph:v17
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: POD_MEMORY_LIMIT
          valueFrom:
            resourceFieldRef:
              divisor: "0"
              resource: limits.memory
        - name: POD_MEMORY_REQUEST
          valueFrom:
            resourceFieldRef:
              divisor: "0"
              resource: requests.memory
        - name: POD_CPU_LIMIT
          valueFrom:
            resourceFieldRef:
              divisor: "1"
              resource: limits.cpu
        - name: POD_CPU_REQUEST
          valueFrom:
            resourceFieldRef:
              divisor: "0"
              resource: requests.cpu
        - name: ROOK_CEPH_MON_HOST
          valueFrom:
            secretKeyRef:
              key: mon_host
              name: rook-ceph-config
        - name: ROOK_CEPH_MON_INITIAL_MEMBERS
          valueFrom:
            secretKeyRef:
              key: mon_initial_members
              name: rook-ceph-config
        image: quay.io/ceph/ceph:v17
        imagePullPolicy: IfNotPresent
        name: init-mon-fs
        resources: {}
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/ceph
          name: rook-config-override
          readOnly: true
        - mountPath: /etc/ceph/keyring-store/
          name: rook-ceph-mons-keyring
          readOnly: true
        - mountPath: /var/log/ceph
          name: rook-ceph-log
        - mountPath: /var/lib/ceph/crash
          name: rook-ceph-crash
        - mountPath: /var/lib/ceph/mon/ceph-a
          name: ceph-daemon-data
      nodeSelector:
        kubernetes.io/hostname: node-1
      priorityClassName: system-node-critical
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: rook-config-override
        projected:
          defaultMode: 420
          sources:
          - configMap:
              items:
              - key: config
                mode: 292
                path: ceph.conf
              name: rook-config-override
      - name: rook-ceph-mons-keyring
        secret:
          defaultMode: 420
          secretName: rook-ceph-mons-keyring
      - hostPath:
          path: /var/lib/rook/rook-ceph/log
          type: ""
        name: rook-ceph-log
      - hostPath:
          path: /var/lib/rook/rook-ceph/crash
          type: ""
        name: rook-ceph-crash
      - hostPath:
          path: /var/lib/rook/mon-a/data
          type: ""
        name: ceph-daemon-data
```
