### ISSUE TITLE
customize nic using systemd link file dosen't work

### ISSUE THREAD

**Issue by skycastlelily** [coreos/fedora-coreos-tracker#1317]
**Describe the bug**
I'm following this link[1] to customize nic,but found nic is not customized accordingly. 
[1]https://docs.fedoraproject.org/en-US/fedora-coreos/customize-nic/#_using_a_systemd_link_file

Journal: https://lnie.fedorapeople.org/customiz.txt

**System details**
 - libvirt
 - fedora-coreos-37.20221008.1.0-qemu.x86_64.qcow2

**Ignition config**
Here is the reproduced bu file:
```yaml
  users:
    - name: cloud-user
      groups:
        - wheel
      password_hash:xxxx
      ssh_authorized_keys:
        - ssh-rsa xxx
systemd:
  units:
    - name: rpm-ostree-install-python3.service
      enabled: true
      contents: |
        [Unit]
        Description=Layer python3 with rpm-ostree
        Wants=network-online.target
        After=network-online.target
        # We run before `zincati.service` to avoid conflicting rpm-ostree
        # transactions.
        Before=zincati.service
        ConditionPathExists=!/var/lib/%N.stamp
        [Service]
        Type=oneshot
        RemainAfterExit=yes
        # `--allow-inactive` ensures that rpm-ostree does not return an error
        # if the package is already installed. This is useful if the package is
        # added to the root image in a future Fedora CoreOS release as it will
        # prevent the service from failing.
        ExecStart=/usr/bin/rpm-ostree install --apply-live --allow-inactive python3
        ConditionPathExists=!/var/lib/%N.stamp
        [Install]
        WantedBy=multi-user.target
storage:
  files:
    - path: /etc/ssh/sshd_config.d/20-enable-passwords.conf
      mode: 0644
      contents:
        inline: |
          # Fedora CoreOS disables SSH password login by default.
          # Enable it.
          # This file must sort before 40-disable-passwords.conf.
          PasswordAuthentication yes
    - path: /etc/systemd/network/25-infra.link
      mode: 0644
      contents:
        inline: |
          [Match]
          MACAddress=12:34:56:78:9a:bc
          [Link]
          Name=infra
```

**Additional information**
Add any other information about the problem here.
