### ISSUE TITLE
systemctl daemon-reload interferes with docker's access to /dev/pts/0

### ISSUE THREAD

**Issue by ion1** [coreos/fedora-coreos-tracker#1321]
**Describe the bug**
The version of runc in Fedora CoreOS 36.20220918.3.0 seems to suffer from the bug fixed in [[1.1] Fix failed exec after systemctl daemon-reload (regression in 1.1.3)](https://github.com/opencontainers/runc/pull/3554) which was released in [runc 1.1.4](https://github.com/opencontainers/runc/releases/tag/v1.1.4).

**Reproduction steps**
```
$ docker run -d --rm --name test alpine sleep 1m
615a522f28ad6751139f4ff757378605d136c582b6368cefa860ffccfd4f9b7a
$ docker exec -it test echo hello
hello
$ sudo systemctl daemon-reload
$ docker exec -it test echo hello
OCI runtime exec failed: exec failed: unable to start container process: open /dev/pts/0: operation not permitted: unknown
```

**Expected behavior**
I expect both `docker exec` invocations to work identically.

**Actual behavior**
Docker fails to access `/dev/pts/0` after `systemctl daemon-reload` has been run.

**System details**
* Bare metal
* Fedora CoreOS 36.20220918.3.0

**Ignition config**

<details><summary>Butane file</summary>

```yaml
variant: fcos
version: 1.4.0
passwd:
  users:
    - name: core
      password_hash: x
      ssh_authorized_keys:
        - x
storage:
  files:
    - path: /etc/hostname
      mode: 0644
      contents:
        inline: x
```

</details>

**Additional information**
N/A
