### ISSUE TITLE
Support GRUB bootloader password

### ISSUE THREAD

**Issue by bgilbert** [coreos/fedora-coreos-tracker#134]
Currently, anyone who has access to the console of a Fedora CoreOS machine can break into the machine.  (For example, with Ctrl-Alt-Del followed by `rd.break`.)  To prevent this, some users may want to set a GRUB password.  There should be a documented and tested way to do this with an Ignition config.

**Comment by h-phil** [comment]
I would like to add a `user.cfg` or add the `set superuser` & `password_pbkdf2` lines to the `grub.cfg` but I am unable to mount the `/boot` partition as read/write.

I've also tried to use `ostree admin instutil -v grub2-generate` with no success.

How does fcos build the `/boot/grub2/grub.cfg`? Is there a workaround available?

**Comment by bgilbert** [comment]
FCOS ships a [handwritten `grub.cfg`](https://github.com/coreos/coreos-assembler/blob/master/src/grub.cfg).

**Comment by cgwalters** [comment]
I think a slightly better option here is that GRUB should have an option to entirely disable its CLI, and from a root shell in a running system (possibly `emergency.target`) one should be able to reboot into a specific bootloader entry, with a possibly modified kernel cmdline.

(Of course, setting a password and then discarding it is mostly equivalent to an option to disable the CLI)

**Comment by cgwalters** [comment]
The extremely messy aspect here is that what I think we want more is something like `/boot/grub2/user.cfg` and our `grub.cfg` includes that if it exists.  But this would just clash with the upstream model of generating the whole thing, which we have moved away from because we want the source of truth to be the BLS configs and that's it.

**Comment by bgilbert** [comment]
> I think we want more is something like `/boot/grub2/user.cfg` and our `grub.cfg` includes that if it exists. But this would just clash with the upstream model of generating the whole thing, which we have moved away from because we want the source of truth to be the BLS configs and that's it.

Since we already don't follow the upstream model, is there any harm to further not following it?

**Comment by h-phil** [comment]
> FCOS ships a [handwritten `grub.cfg`](https://github.com/coreos/coreos-assembler/blob/master/src/grub.cfg).

Since it is static I've injected the lines for now on my bare metal installations.
Thanks.

**Comment by control-d** [comment]
In my tests simply adding the code from the template in `/etc/grub.d/01_users` to `grub.cfg` enables the ability to set a password on the grub2 menu

~~~
# tail -n13 /boot/grub2/grub.cfg 

### BEGIN /etc/grub.d/01_users ###
if [ -f ${prefix}/user.cfg ]; then
  source ${prefix}/user.cfg
  if [ -n "${GRUB2_PASSWORD}" ]; then
    set superusers="root"
    export superusers
    password_pbkdf2 root ${GRUB2_PASSWORD}
  fi
fi
### END /etc/grub.d/01_users ###

blscfg
~~~

Then using `grub2-setpassword`/`grub2-set-password` to create `/boot/grub2/user.cfg` enables the password protection. Deleting `/boot/grub2/user.cfg` disabled it.  As long as `user.cfg` is in the expected format I'm not sure it matters how it's created.  The obvious issue with all of this is `/boot` being mounted read-only.

**Comment by h-phil** [comment]
> The obvious issue with all of this is /boot being mounted read-only.

@control-d You can work around this issue if you do something like this in your provisioning. (It's far from perfect)
```
/usr/bin/mount -o remount,rw /boot
  --> create your user.cfg
/usr/bin/mount -o remount,ro /boot
```

**Comment by bgilbert** [comment]
This works:

```yaml
variant: fcos
version: 1.4.0
storage:
  filesystems:
    - device: /dev/disk/by-label/boot
      format: ext4
      path: /boot
  files:
    - path: /boot/grub2/grub.cfg
      append:
        # root/password1
        - inline: |
            set superusers="root"
            password_pbkdf2 root grub.pbkdf2.sha512.10000.874A958E52640980067F3DB9BFC8A6C53205A17A18115B47EA40301DCD059A622EFED53CDC952B26C1173F9DFD3CCB37B27F681F2C2A0DABD40AFF86DE92FA13.209EF048E916ACD770EBA4A6656BF91291F2077EF1C2A26067F3CF39775875D2E3ED6086AC62FB23C0160CD7DA6E3552B98D3A01B500AF50E80367CC969449C2
```

Thoughts:

- I agree that it'd be better to conditionally read a separate `/boot/grub2/user.cfg` rather than encouraging appending to the distributed `grub.cfg`.
- Do we want to encourage manually mounting `/boot` in Ignition, as above?  Alternatively, we could automatically mount it in the initrd along with `/sysroot`, or we could handle everything via Butane sugar.
- Previous boot entries can still be started without a password, as long as there is no attempt to modify the command line.  This allows users with console access to roll back to previous software and previous configs.  This can be prevented by adding `grub_users ""` to old BLS entries, but ostree would need to do that.
