### ISSUE TITLE
configure to create a  partition after root partition  on primary disk is ignored (only affects s390x)

### ISSUE THREAD

**Issue by skycastlelily** [coreos/fedora-coreos-tracker#1358]
### Describe the bug

I'm following this page[1] to  set up /var on a separate partition on the same primary disk,but it failed on s390x system
[1]https://docs.fedoraproject.org/en-US/fedora-coreos/storage/#_setting_up_separate_var_mounts

FYI:
1)I also tried Adding a /var/lib/containers partition to the primary disk,also failed.
2)remove the  filesystems  part of the bu file also failed.
3) change /dev/disk/by-partlabel/var to /dev/vda also failed.

### Reproduction steps

Run the following command line:

```
 virt-install --connect="qemu:///system" --name="${VM_NAME}" --vcpus="${VCPUS}" --memory="${RAM_MB}"         --os-variant="fedora-coreos-$STREAM" --import --graphics=none         --disk="size=${DISK_GB},backing_stor
e=${IMAGE}"         --network bridge=virbr0 --disk path="${IGNITION_CONFIG}",format=raw,readonly=on,serial=ignition,startup_policy=optional
```

### Expected behavior

```
[cloud-user@localhost ~]$ lsblk
NAME   MAJ:MIN RM  SIZE RO TYPE MOUNTPOINTS
vda    252:0    0   10G  0 disk 
├─vda1 252:1    0    1M  0 part 
├─vda2 252:2    0  127M  0 part 
├─vda3 252:3    0  384M  0 part /boot
├─vda4 252:4    0    8G  0 part /sysroot/ostree/deploy/fedora-coreos/var
│                               /usr
│                               /etc
│                               /
│                               /sysroot
└─vda5 252:5    0  1.5G  0 part /var
```

### Actual behavior

```
NAME   MAJ:MIN RM  SIZE RO TYPE MOUNTPOINTS
vda    252:0    0   12G  0 disk 
├─vda1 252:1    0  3.6G  0 part /var
├─vda3 252:3    0  384M  0 part /boot
└─vda4 252:4    0    8G  0 part /sysroot/ostree/deploy/fedora-coreos/var
                                /usr
                                /etc
                                /
                                /sysroot
```

### System details

- `fedora-coreos-37.20221127.1.0-qemu.s390x.qcow2`

### Ignition config

```
variant: fcos
version: 1.4.0
passwd:
  users:
    - name: cloud-user
      groups:
        - wheel
      password_hash: $y$j9T$90Mqu2Viusm6XbBpEBUW60$IF9ZBdoOtbJel4UxNLJDduWBj1ND93FdO5cTDndcXjB
      ssh_authorized_keys:
systemd:
  units:
    - name: rpm-ostree-install-python3.service
      enabled: true
      contents: |
        [Unit]
        Description=Layer vim with rpm-ostree
        Wants=network-online.target
        After=network-online.target
        # We run before `zincati.service` to avoid conflicting rpm-ostree
        # transactions.
        Before=zincati.service
        ConditionPathExists=!/var/lib/%N.stamp
        [Service]
        Type=oneshot
        RemainAfterExit=yes
        # `--allow-inactive` ensures that rpm-ostree does not return an error
        # if the package is already installed. This is useful if the package is
        # added to the root image in a future Fedora CoreOS release as it will
        # prevent the service from failing.
        ExecStart=/usr/bin/rpm-ostree install --apply-live --allow-inactive python3
        ConditionPathExists=!/var/lib/%N.stamp
        [Install]
        WantedBy=multi-user.target
storage:
  files:
    - path: /etc/ssh/sshd_config.d/20-enable-passwords.conf
      mode: 0644
      contents:
        inline: |
          # Fedora CoreOS disables SSH password login by default.
          # Enable it.
          # This file must sort before 40-disable-passwords.conf.
          PasswordAuthentication yes
  disks:
  -
    device: /dev/disk/by-id/coreos-boot-disk
    # We do not want to wipe the partition table since this is the primary
    # device.
    wipe_table: false
    partitions:
    - number: 4
      label: root
      # Allocate at least 8 GiB to the rootfs. See NOTE above about this.
      size_mib: 8192
      resize: true
    - size_mib: 0
      # We assign a descriptive label to the partition. This is important
      # for referring to it in a device-agnostic way in other parts of the
      # configuration.
      label: var
  filesystems:
    - path: /var
      device: /dev/disk/by-partlabel/var
      # We can select the filesystem we'd like.
      format: ext4
      # Ask Butane to generate a mount unit for us so that this filesystem
      # gets mounted in the real root.
      with_mount_unit: true
```

### Additional information

journal: https://lnie.fedorapeople.org/varjournal
