### ISSUE TITLE
Fix k8s containers secret access being blocked by SELinux

### ISSUE THREAD

**Issue by basvdlei** [coreos/fedora-coreos-tracker#1366]
### Describe the bug

Secrets and memory backed emptydir volumes, created by a Kubelet running inside a podman system container, can no longer be accessed by pods after an updating to testing 37.20221225.2.1.

Access is blocked by SELinux:

```
Dec 29 10:13:12 worker-01 audit[7127]: AVC avc:  denied  { open } for  pid=7127 comm="kube-state-metr" path="/var/run/secrets/kubernetes.io/serviceaccount/..2022_12_29_10_05_35.1005894857/token" dev="tmpfs" ino=3 scontext=system_u:system_r:container_t:s0:c159,c820 tcontext=system_u:object_r:tmpfs_t:s0 tclass=file permissive=0
Dec 29 10:14:38 worker-01 audit[7603]: AVC avc:  denied  { open } for  pid=7603 comm="kube-state-metr" path="/var/run/secrets/kubernetes.io/serviceaccount/..2022_12_29_10_05_35.1005894857/token" dev="tmpfs" ino=3 scontext=system_u:system_r:container_t:s0:c159,c820 tcontext=system_u:object_r:tmpfs_t:s0 tclass=file permissive=0
Dec 29 10:17:28 worker-01 audit[8328]: AVC avc:  denied  { open } for  pid=8328 comm="kube-state-metr" path="/var/run/secrets/kubernetes.io/serviceaccount/..2022_12_29_10_05_35.1005894857/token" dev="tmpfs" ino=3 scontext=system_u:system_r:container_t:s0:c159,c820 tcontext=system_u:object_r:tmpfs_t:s0 tclass=file permissive=0
```

Downgrading container-selinux to container-selinux 2:2.193.0-1.fc37.noarch with `rpm-ostree override replace` resolves the issue.

### Reproduction steps

1. Run a Kubelet with Podman privileged container and a volumemount: `--volume /var/lib/kubelet:/var/lib/kubelet:rshared,z`
2. Create a secret and a pod:

```
apiVersion: v1
kind: Secret
metadata:
  name: test-secret
type: Opaque
data:
  USER_NAME: YWRtaW4=
  PASSWORD: MWYyZDFlMmU2N2Rm
---
apiVersion: v1
kind: Pod
metadata:
  name: volumetest
  labels:
    pod-type: testing
spec:
  containers:
  - name: test
    image: registry.fedoraproject.org/fedora:37
    command: ['sh', '-c', 'echo "Hello world" && sleep +inf']
    volumeMounts:
    - mountPath: /test-secret
      name: test-secret
    - mountPath: /test-default-emptydir
      name: test-default-emptydir
    - mountPath: /test-memory-emptydir
      name: test-memory-emptydir
  volumes:
  - name: test-default-emptydir
    emptyDir:
  - name: test-memory-emptydir
    emptyDir:
      medium: Memory
      sizeLimit: 64Mi
  - name: test-secret
    secret:
      secretName: test-secret
```

3.  Look at the SELinux labels of the created volumes:
```
ls -lZ /var/lib/kubelet/pods/*/*
```

### Expected behavior

tmpfs volumes to be labeled with `system_u:object_r:container_file_t:s0` and the pod containers are allowed access:

```
kubernetes.io~empty-dir:
total 0
drwxrwxrwx. 2 root root system_u:object_r:container_file_t:s0  6 Dec 29 13:35 test-default-emptydir
drwxrwxrwt. 2 root root system_u:object_r:container_file_t:s0 40 Dec 29 13:35 test-memory-emptydir

kubernetes.io~projected:
total 0
drwxrwxrwt. 3 root root system_u:object_r:container_file_t:s0 140 Dec 29 13:35 kube-api-access-7v7qb

kubernetes.io~secret:
total 0
drwxrwxrwt. 3 root root system_u:object_r:container_file_t:s0 120 Dec 29 13:35 test-secret
```

### Actual behavior

The volumes backed by a tmpfs filesystem are labeled with `system_u:object_r:container_file_t:s0` and pod container access is denied.

```
kubernetes.io~empty-dir:
total 0
drwxrwxrwx. 2 root root system_u:object_r:container_file_t:s0  6 Dec 29 13:23 test-default-emptydir
drwxrwxrwt. 2 root root system_u:object_r:tmpfs_t:s0          40 Dec 29 13:23 test-memory-emptydir

kubernetes.io~projected:
total 0
drwxrwxrwt. 3 root root system_u:object_r:tmpfs_t:s0 140 Dec 29 13:23 kube-api-access-7lmxp

kubernetes.io~secret:
total 0
drwxrwxrwt. 3 root root system_u:object_r:tmpfs_t:s0 120 Dec 29 13:23 test-secret
```

### System details

- QEMU
- Fedora CoreOS 37.20221225.2.1 (Testing)

### Additional information

I've not tested this, but this issue should affect [Poseidon Typhoon Kubernetes](https://typhoon.psdn.io/fedora-coreos/aws/) on Fedora CoreOS as well, as we are using the same method to run a kubelet with podman: https://github.com/poseidon/typhoon/blob/main/azure/fedora-coreos/kubernetes/workers/butane/worker.yaml#L53
