### ISSUE TITLE
NetworkManager configures the SR-IOV interface on Azure with accelerated networking

### ISSUE THREAD

**Issue by freedge** [coreos/fedora-coreos-tracker#1383]
### Describe the bug

deploying a VM using accelerated networking on Azure,
Azure exposes a second interface, that is supposed to stay [unmanaged](https://learn.microsoft.com/en-us/azure/virtual-network/accelerated-networking-overview#custom-images-or-azure-compute-gallery-images), but NetworkManager still configures it.

### Reproduction steps

1. deploy a VM with accelerated networking
2. reboot it
3. ip a

### Expected behavior

eth0 should be the only managed and configured interface.

When explicitly telling the NetworkManager to not manage this interface as [doc](https://learn.microsoft.com/en-us/azure/virtual-network/accelerated-networking-overview#custom-images-or-azure-compute-gallery-images),  the second interface should not receive an IP

### Actual behavior

both eth0 and enP36480s1 are configured and given an IP.

When creating a 99-azure-unmanaged-devices.conf, enP36480s1 is not managed, but still has an IP configured on it. Maybe CoreOS is starting the NetworkManager a first time in the initrd and it does not see the configuration.

### System details

```
$ rpm-ostree status -b
State: idle
AutomaticUpdatesDriver: Zincati
  DriverState: active; periodically polling for updates (last checked Sat 2023-01-14 23:31:17 UTC)
BootedDeployment:
● fedora:fedora/aarch64/coreos/next
                  Version: 37.20230110.1.0 (2023-01-11T23:24:37Z)
                   Commit: 28729e10c569ae46560de6fb251d45be9ea7efa6666b98790b09f7ad4af8c8bc
             GPGSignature: Valid signature by ACB5EE4E831C74BB7C168D27F55AD3FB5323552A

```

- Azure with accelerated networking
- Arm64 in my case, but should be reproducible with x64 as well 

### Ignition config
```
variant: fcos
version: 1.4.0

storage:

  directories:

    - path: /etc/NetworkManager/conf.d

  files:

    
    # https://learn.microsoft.com/en-us/azure/virtual-network/accelerated-networking-overview
    - path: /etc/NetworkManager/conf.d/99-azure-unmanaged-devices.conf
      contents:
        inline: |
          # Ignore SR-IOV interface on Azure, since it'll be transparently bonded
          # to the synthetic interface
          [keyfile]
          unmanaged-devices=driver:mlx4_core;driver:mlx5_core
```
### Additional information

reported on RHCOS through a case to the vendor, but since it is reproduced on fcos, I figured I'll send an issue here too.
