### ISSUE TITLE
createRaids fails by waiting until timeout for successfully partitioned underlying raid0 partitions

### ISSUE THREAD

**Issue by N3rdle** [coreos/fedora-coreos-tracker#1396]
### SUMMARY

I believe i've found a regression that causes what appears to me to be very basic raid configurations to fail to form on stable:37.20230110-3.1 for (at least) x86_64

### DETAILS:

The following rather simple validating butane config fails to yield an operational os instance when installed onto bare x86_64 metal with an ssd at /dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:0:0 (which corresponds to /dev/sda)
raidConfig ultimately times out waiting on the underlying partitions with the following observations i've made:

* this was booted from PXE images with the rootfs being hosted on the same server via http
* the failure occurs while ignition is running after the typical reboot to the real target boot device
* the summary of the error is that that disks: createRaids waits for the underlying partitions that are to be assembled into a raid0 volume 
* disks: createPartitions appears to finish successfully on all devices
* createRaids's activities yield the following systemd outputs as the timeout proceeds:
   * waiting on ignition-disks.service
     * waiting on dev-disk-by\x2dpartname-var1.device
     * waiting on dev-disk-by\x2dpartname-var2.device
     * NOTICE: no wait for var3, as which makes total sense since it's not a part of the raid set and the issue is with createRaids
* the 4 disks are identical skus with identical geometry and firmware
* i get the same results with any number of disks in the raid0 set
* i get the same results with other raid configurations (linear, raid1, etc)
* per `/usr/sbin/sfdisk`, the devices have exactly the expected partitions built, of type Linux filesystem
* i get the same results with the partitions created as gpt partition type linux raid
* i get the same results if i change the path to the raid volume from the by-name variant to be /dev/md/varraid0
* i get the same results if i change the installation disk to /dev/sda from the path-based variant
* i get the same results if i use the disk's overarching block-device vs one large partition per disk
* this happens even if i use `--assume-clean` in the raid options to avoid doing any synchronizing (thinking that it was a legitimate timeout in this case perhaps for raid1, etc)
* all disks were entirely wiped before installing
* the x86_64 box has 96 GB of ram
* the ignition file is well formed and looks right
* everything works as expected if i simply remove the raid set from the configuration altogether and configure  the /var filesystem to use any of the var partitions by part-name as shown
* am i missing something obvious, does this just not work and it's "well-known" (except by those who are new and trusting documentation), or is this really the major regression it appears to be?

### Reproduction steps

1. create configuration above
2. hand it out via PXE to a new physical computer
3. watch it time out

### Expected behavior

the disk subsystem gets built per the legal specifications

### Actual behavior

createRaids times out while waiting on systemd devices to finish provisioning

### System details

- Bare metal, x86_64, 96GB ram, 24 total cores

### Ignition config

```yaml
variant: fcos
version: 1.4.0
storage:
    disks:
      - device: /dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:0:0
        partitions:
          - number: 4
            label: root
            wipe_partition_entry: true
            size_mib: 16384
      - device: /dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:1:0
        partitions:
          - number: 1
            label: var1
      - device: /dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:2:0
        partitions:
          - number: 1
            label: var2
      - device: /dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:3:0
        partitions:
          - number: 1
            label: var3
    raid:
      - name: varraid0
        level: raid0
        devices:
          - /dev/disk/by-partname/var1
          - /dev/disk/by-partname/var2
    filesystems:
      - label: root
        device: /dev/disk/by-partname/root
        format: xfs
        wipe_filesystem: true
      - path: /var
        label: var
        device: /dev/disk/by-id/dm-name-varraid0
        format: xfs
        with_mount_unit: true
passwd:
    users:
      - name: core
        groups:
          - sudo
          - wheel
        ssh_authorized_keys:
          - ssh-ed25519 BLAHBLAH
```
