### ISSUE TITLE
clevis-tang keyed luks root filesystem never uses ignition configured network configuration after installation-time boot

### ISSUE THREAD

**Issue by N3rdle** [coreos/fedora-coreos-tracker#1401]
### Describe the bug

If one uses Clevis/Tang to key luks on the root filesystem, and then one reboots the installed operating system after the ignition install-time boot completes (at which point the configured network configuration *is* used as expected), the booting coreos instance uses the initramfs-baked-in default internal DHCP NetworkManager configuration for all network interfaces in the system with which to derive the luks keys, and then never switches to using the configured networking

### Reproduction steps

1. configure a root filesystem with luks keyed by clevis/tang with a custom NetworkManager keyfile(s) installed by ignition
2. reboot after the ignition execution is totally done
3. the OS will now reboot with DHCP addresses, not the configured network that you laid down via ignition

### Expected behavior

Use the network configuration laid down by ignition

### Actual behavior

Uses DHCP as baked into the initramfs

### System details

bare metal, x86_64, 24 cores, 96 GB ram
FCOS 37.20230110-3.1

### Ignition config

```yaml
variant: fcos
version: 1.4.0
storage:
    disks:
      # NOTE: we refer to disks by absolute pci path, safest
      - device: /dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:0:0
        partitions:
          - number: 4
            label: rootpart
            wipe_partition_entry: true
            # this is the luks gpt partition type
            type_guid: CA7D7CCB-63ED-4C53-861C-1742536059CC
            size_mib: 131072
          - number: 5
            label: varpart
            type_guid: CA7D7CCB-63ED-4C53-861C-1742536059CC
    luks:
        # here's the philosophy of disk layouts:
        # this implements a network-bound full disk encryption approach
        # if the disks are taken out of this network, they can't be decrypted
        # our use case is to avoid inadvertent disclosure to outsiders if we ship a drive, etc.
        # we must be sure to only put our data into /var/lib/containers
      - name: rootluks
        label: rootluks
        wipe_volume: true
        device: /dev/disk/by-partlabel/rootpart
        options:
        key_file:
            inline: FULL_DISK_ENCRYPTION_KEY
#        clevis:
#            tang:
#              - url: http://10.0.0.1:80
#                thumbprint: <blah>
      - name: varluks
        label: varluks
        wipe_volume: true
        device: /dev/disk/by-partlabel/varpart
        key_file:
            inline: FULL_DISK_ENCRYPTION_KEY
    filesystems:
      - label: root
        # path: / ** NOTE: NEVER uncomment this, breaks late stage provisioning, HERE AS A WARNING
        device: /dev/disk/by-id/dm-name-rootluks
        format: xfs
        wipe_filesystem: true
      - path: /var
        label: var
        device: /dev/disk/by-id/dm-name-varluks
        format: xfs
        with_mount_unit: true
    files:
      - path: /etc/NetworkManager/system-connections/eno1.nmconnection
        user:
            id: 0
        group:
            id: 0
        mode: 0o0600
        overwrite: true
        contents:
            inline: |
              [connection]
              id=eno1
              type=ethernet
              interface-name=eno1
             
              [ethernet]
              mtu=1500
              
              [ipv4]
              address=10.00.0.40/16
              gateway=10.00.0.1
              dns=10.0.0.1;
              dns-search=blah.com;
              may-fail=false
              method=manual
              
              [ipv6]
              addr-gen-mode=default
              method=disabled
              
              [proxy]
```
