### ISSUE TITLE
Zincati service silently fails to start

### ISSUE THREAD

**Issue by SomewhereOutInSpace** [coreos/fedora-coreos-tracker#1405]
### Describe the bug

The Zincati service is dead with no clear cause, and refuses to be started manually.

### Reproduction steps

Unknown. Unfortunately there aren't even any logs, at least in `journalctl`:
```
[core@jumpgate ~]$ journalctl -u zincati
-- No entries --
```

### Expected behavior

Zincati should be alive and updating my system.

### Actual behavior

I noticed that my installation's uptime was getting quite long (22 days) and realized that Zincati was dead:
```
[core@jumpgate ~]$ sudo systemctl status zincati
○ zincati.service - Zincati Update Agent
     Loaded: loaded (/usr/lib/systemd/system/zincati.service; enabled; preset: enabled)
     Active: inactive (dead)
       Docs: https://github.com/coreos/zincati
```
Running `systemctl start/restart zincati` simply hangs with no output until I manually terminate the process:
```
[core@jumpgate ~]$ systemctl restart zincati
==== AUTHENTICATING FOR org.freedesktop.systemd1.manage-units ====
Authentication is required to restart 'zincati.service'.
Authenticating as: CoreOS Admin (core)
Password: 
==== AUTHENTICATION COMPLETE ====
^C
```
Even a manual update and reboot didn't resolve the issue. 

Trying to run the Zincati executable directly yielded `[ERROR zincati] critical error: update agent not running as zincati user`, but I couldn't for the life of me figure out how to `su` into it.

### System details

```
● fedora:fedora/x86_64/coreos/stable
                  Version: 37.20230110.3.1 (2023-01-24T16:21:39Z)
               BaseCommit: fc214c16d248686d4cf2bb3050b59c559f091692d7af3b07ef896f1b8ab2f161
             GPGSignature: Valid signature by ACB5EE4E831C74BB7C168D27F55AD3FB5323552A
          LayeredPackages: cockpit-ostree cockpit-podman cockpit-system docker-compose rclone
```
Vultr VPS.

### Ignition config

```
variant: fcos
version: 1.4.0
passwd:
  users:
    - name: core
      ssh_authorized_keys:
        - [REDACTED]
      password_hash: [REDACTED]
      home_dir: /home/core
      groups:
        - sudo
        - wheel
        - docker
      shell: /bin/bash  
systemd:
  units:
    - name: mount.service
      enabled: true
      contents: |
        [Unit]
        Description=Trigger mount script.
        Wants=mount.timer
        [Service]
        Type=oneshot
        ExecStart=/bin/bash /home/core/b2_mounts/spin_up_mounts.sh
        [Install]
        WantedBy=multi-user.target
    - name: mount.timer
      enabled: true
      contents: |
        [Unit]
        Description=Run mount script on boot.
        [Timer]
        OnBootSec=15s
        [Install]
        WantedBy=timers.target
storage:
  disks:
    - device: /dev/disk/by-id/coreos-boot-disk
      wipe_table: false
      partitions:
        - label: swap
          size_mib: 0
          start_mib: 49152
  filesystems:
    - device: /dev/disk/by-partlabel/swap
      format: swap
      wipe_filesystem: true
      with_mount_unit: true        
  files:
    - path: /home/core/packages
      contents:
        inline: cockpit-ostree cockpit-podman cockpit-system docker-compose rclone
    - path: /etc/hostname
      contents:
        inline: jumpgate
    - path: /etc/zincati/config.d/10-configure-autoupdates.toml
      contents:
        source: https://blog.hello-www.net/resources/zincati
    - path: /etc/motd
      overwrite: true
      contents:
        source: https://blog.hello-www.net/resources/motd
    - path: /etc/ssh/sshd_config.d/90-access-config.conf
      contents:
        source: https://blog.hello-www.net/resources/sshd
    - path: /etc/systemd/zram-generator.conf
      contents:
        source: https://blog.hello-www.net/resources/zram
```
