### ISSUE TITLE
Enabling Tang on `/var` doesn't force networking in initrd

### ISSUE THREAD

**Issue by bgilbert** [coreos/fedora-coreos-tracker#1409]
### Describe the bug

If the rootfs is encrypted with Tang, `rdcore rootmap` automatically adds an `rd.neednet=1` karg for subsequent boots.  We don't have similar logic for `/var`, but `/var` is also mounted from the initrd.  So, if the rootfs is not Tang-encrypted but `/var` is (which is probably _not_ a common configuration) the system fails to boot after the first boot.

### Reproduction steps

1. Install Tang on your workstation
2. Resize an FCOS QEMU image to add some extra space
3. Boot the image with user-mode networking and the Butane config given below
4. After boot succeeds, reboot the VM

### Expected behavior

Boot succeeds.

### Actual behavior

Boot stops at a passphrase prompt:

```console
🔐 Please enter passphrase for disk var: (press TAB for no echo) 
```

And the journal shows repeated Clevis errors:
```console
Feb 05 03:57:46 localhost clevis-luks-askpass[800]: Error communicating with server http://10.0.2.2!
Feb 05 03:57:46 localhost clevis-luks-askpass[917]: Error communicating with server http://10.0.2.2!
Feb 05 03:57:47 localhost clevis-luks-askpass[1034]: Error communicating with server http://10.0.2.2!
```

### System details

- QEMU (but should happen anywhere)
- FCOS 37.20230110.3.1
- Butane `v0.17.0-19-gbb5ecac586b2`

### Ignition config

```yaml
variant: fcos
version: 1.4.0
storage:
  disks:
    - device: /dev/sda
      partitions:
        - number: 5
          label: var
  luks:
    - device: /dev/disk/by-partlabel/var
      name: var
      clevis:
        tang:
          - url: http://10.0.2.2
            thumbprint: [...]
      wipe_volume: true
  filesystems:
    - device: /dev/mapper/var
      path: /var
      format: xfs
      with_mount_unit: true
passwd:
  users:
    - name: core
      ssh_authorized_keys:
        - ssh-rsa [...]
```

### Additional information

Attempting to work around this with:

```yaml
kernel_arguments:
  should_exist:
    - rd.neednet=1
```

produces:

```console
[ SKIP ] Ordering cycle found, skipping lockdev@dev-mapper-var.target
[  OK  ] Reached target sound.target - Sound Card.
[  OK  ] Finished lvm2-monitor.serv…sing dmeventd or progress polling.
[  OK  ] Reached target local-fs-pr…reparation for Local File Systems.
         Starting systemd-fsck@dev-…92f-2ba7-4cbb-b65a-b376feb79c06...
[  OK  ] Finished systemd-fsck@dev-…ec92f-2ba7-4cbb-b65a-b376feb79c06.
         Mounting boot.mount - CoreOS Dynamic Mount for /boot...
[  OK  ] Mounted boot.mount - CoreOS Dynamic Mount for /boot.
[   ***] Job dev-mapper-var.device/start running (32s / no limit)
```
