### ISSUE TITLE
Chronyd Configuration On Newly Provisioned Testing (37.20230322.2.0) Nodes Failing

### ISSUE THREAD

**Issue by fifofonix** [coreos/fedora-coreos-tracker#1449]
### Describe the bug

Prior to this FCOS version it was possible to configure a custom NTP server via ignition by writing to /etc/sysconfig/chronyd. Note machines previously commissioned with this ignition snippet upgrade fine to this `testing` version. This issue occurs also on latest `next`.

```
    - path: /etc/sysconfig/chronyd
      mode: 0644
      overwrite: true
      contents:
        inline: |
          OPTIONS="'server ntp.server.acme.edu'
          "
```

It is not clear to me what the simple way should be to configure a custom ntp server. If there is a simple more canonical way than above I'm open to adopting it instead.

### Reproduction steps

1. Commission a new machine for the specified `testing` stream version with ignition snippet provided.
2. Chronyd.service fails to start.

### Expected behavior

1. Chronyd.service should start normally.

### Actual behavior

Chrony.service fails:

```
Could not parse server directive at line 1
```

This seems to be because a FCOS chronyd config is now created (this attempts to merge in the ignition-specified options but fails on quoting issues, yielding something like:

```
OPTIONS=''server ntp.server.acme.edu'
 -f /run/coreos/platform-chrony.conf'
```

### System details

- vSphere & AWS

### Additional information

Manually amending the auto-generated /run/coreos/sysconfig-chrony to below results in a happy chronyd.

```
OPTIONS="'server ntp.nyp.org'
 '-f /run/coreos/platform-chrony.conf'
"
```
