### ISSUE TITLE
`/boot` partition fills up with unused kernels

### ISSUE THREAD

**Issue by har7an** [coreos/fedora-coreos-tracker#1493]
### Describe the bug

I'm using CoreOS with default update strategy on a x86_64 platform. Recently I noticed that the `/boot` partition on my system is full, causing updates to fail.

On closed inspection I noticed that `/boot` contained 5 kernels when I had a system with only 3 deployments (current, pending, rollback). I "solved" the problem by remounting `/boot` as `rw`, deleting the unused kernels, and then letting it reboot during the maintenance window. Now my deployment is on `38.20230414.3.0`, but `/boot` is full again, and updates fail.

### Reproduction steps

Cannot say, my other installations run fine.

### Expected behavior

Updates should succeed, old kernels should be purged from `/boot` automatically.

### Actual behavior

`/boot` fills up with kernels of non-existent deployments and updates fail. The system is stuck on the current revision.

### System details

- Bare Metal installation
- Version: 38.20230414.3.0 (2023-05-01T21:23:54Z)

### Butane or Ignition config

```yaml
variant: fcos
version: 1.4.0

passwd:
  users:
    - name: hartan
      groups:
        - wheel
        - sudo

storage:
  filesystems:
    # Reformat rootfs to btrfs
    - device: /dev/disk/by-partlabel/root
      wipe_filesystem: true
      format: btrfs
      label: root
  files:
    # Set hostname
    - path: /etc/hostname
      mode: 0644
      contents:
        inline: REDACTED
    # German keymap, please
    - path: /etc/vconsole.conf
      mode: 0644
      contents:
        inline: KEYMAP=de
    # Set vim as default editor
    - path: /etc/profile.d/zz-default-editor.sh
      overwrite: true
      contents:
        inline: |
          export EDITOR=nvim
    # Static network configuration
    - path: /etc/NetworkManager/system-connections/ens192.nmconnection
      mode: 0600
      contents:
        inline: |
          [connection]
          id=ens192
          uuid=8ccaac10-7deb-34cb-ba02-28a60ebf44c6
          type=ethernet
          autoconnect-priority=-999
          interface-name=ens192
          permissions=
          
          [ethernet]
          mac-address-blacklist=
          
          [ipv4]
          address1=REDACTED
          dns=REDACTED;
          dns-search=
          method=manual
          
          [ipv6]
          addr-gen-mode=eui64
          dns-search=
          ip6-privacy=0
          method=auto

systemd:
  units:
    # Installing layered package with rpm-ostree
    - name: rpm-ostree-install-packages.service
      enabled: true
      contents: |
        [Unit]
        Description=Layer packages with rpm-ostree
        Wants=network-online.target
        After=network-online.target
        # We run before `zincati.service` to avoid conflicting rpm-ostree
        # transactions.
        Before=zincati.service
        ConditionPathExists=!/var/lib/%N.stamp

        [Service]
        Type=oneshot
        RemainAfterExit=yes
        ExecStart=/usr/bin/rpm-ostree install --apply-live --allow-inactive \
            gcc neovim openssl-devel zsh
        ExecStart=/bin/touch /var/lib/%N.stamp

        [Install]
        WantedBy=multi-user.target
```
```


### Additional information

_No response_
