### ISSUE TITLE
TPM not found on some hardware with kernel 6.4.11

### ISSUE THREAD

**Issue by hervst** [coreos/fedora-coreos-tracker#1555]
### Describe the bug

We have several bare metal installations of Fedora CoreOS on Intel NUCs running. Some of them use the "testing" stream. Therefor they upgraded from 38.20230806.2.0 to 38.20230819.2.0 recently. After the upgrade they fail decrypting the LUKS encrypted volume on boot. The error message is: 

`clevis-luks-askpass[XXX]: A TPM2 device with the in-kernel resource manager is needed!`

When rolling back from 38.20230819.2.0 to 38.20230806.2.0 the system boots again without these issues.

Trying to reinstall Fedora CoreOS 38.20230819.2.0 on one of our base metal devices with LUKS enabled also fails. The same Ignition file works fine with older Fedora CoreOS versions.

### Reproduction steps

1. Install Fedora CoreOS bare metal testing stream using 38.20230806.2.0 or earlier with LUKS (TPM2) encryption enabled
2. Upgrade system to 38.20230819.2.0

### Expected behavior

System should decrypt boot volume on start-up without any issues.

### Actual behavior

System fails to decrypt boot volume on start-up.

### System details

- Fedora CoreOs Bare Metal Testing Stream
- Upgrade from 38.20230806.2.0 to 38.20230819.2.0
- Device is an Intel NUC BXNUC10i5FNKN2

### Butane or Ignition config

```yaml
variant: fcos
version: 1.4.0

passwd:
  groups:
    - name: cockpit
      system: false
  users:
    - name: $USERNAME
      uid: 1001
      system: false
      ssh_authorized_keys:
        - ssh-ed25519 $KEY $KEY_NAME
      password_hash: $PASSWORD_HASH
      groups:
        - sudo
        - wheel

boot_device:
  luks:
    tpm2: true
```

### Additional information

Log while booting with version 38.20230806.2.0: [fcosBootBeforeUpdate.txt](https://github.com/coreos/fedora-coreos-tracker/files/12454114/fcosBootBeforeUpdate.txt)
Log while booting with version 38.20230819.2.0: [fcosBootAfterUpdate.txt](https://github.com/coreos/fedora-coreos-tracker/files/12454113/fcosBootAfterUpdate.txt)

Please be aware that I manually typed the display outputs in both log files so there might be small typos.

Log while trying to install Fedora CoreOS 38.20230819.2.0 testing stream with LUKS enabled: [rdsosreport.txt](https://github.com/coreos/fedora-coreos-tracker/files/12454115/rdsosreport.txt)
