### ISSUE TITLE
docker-compose (via the podman-docker layer) no longer working after upgrade to crun 1.9 from 1.8.7

### ISSUE THREAD

**Issue by BaconIsAVeg** [coreos/fedora-coreos-tracker#1570]
### Describe the bug

I recently switched from using docker to rootless podman, and everything has been working fine for the past few weeks.  Thursday (Wednesday?) night crun was updated from 1.8.7 to 1.9.  When I tried to start my stack the next morning, none of the containers would start.  I've tried looking for the error, however all references are against much older releases and I couldn't find any recent issues mentioning `OCI permission denied`.

If I downgrade the package to 1.8.7, everything works fine again, however this isn't an ideal long-term solution.

### Reproduction steps

1. This is the docker-compose file I'm using:

```
version: '3'

volumes:
  mysql_data:
    driver: local
  es_data:
    driver: local
  appname_cache:
    driver: local

services:
  appname:
    build:
      context: .
      dockerfile: docker/images/appname/Dockerfile.local
    user: 0:0
    userns_mode: keep-id:uid=1000,gid=1000
    ports:
      - "8080:80"
    restart: unless-stopped
    volumes:
      - .:/var/www/html
      - appname_cache:/var/www/html/cache
    environment:
      - APACHE_RUN_USER=appname
      - APACHE_RUN_GROUP=appname
      - PLATONE_ENV=local
      - PLATONE_STAGE=local
      - DB_HOSTNAME=mysql
      - SMTP_HOST=mail
      - SMTP_PORT=1025
      - ENABLE_CRON=false

  mysql:
    build:
      context: .
      dockerfile: docker/images/mysql/8.0/Dockerfile
    cpu_shares: 512
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=appname
      - MYSQL_USER=appname
      - MYSQL_PASSWORD=appname
      - MYSQL_ROOT_PASSWORD=root

  elasticsearch:
    build:
      context: .
      dockerfile: docker/images/elastic/7.16/Dockerfile
    cpu_shares: 512
    restart: unless-stopped
    volumes:
      - es_data:/usr/share/elasticsearch/data
    environment:
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
      - discovery.type=single-node
      - bootstrap.memory_lock=true
    cap_add:
      - IPC_LOCK
    mem_swappiness: 0
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536

  redis:
    image: redis:alpine
    mem_limit: 64mb
    restart: unless-stopped

  mail:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
    restart: unless-stopped
```

2. Run `docker-compose up -d`

### Expected behavior

All 5 containers should startup successfully.

### Actual behavior

```
❯ docker-compose up -d
[+] Running 0/5
 ⠹ Container elasticsearch-1  Starting                                                                      1.2s
 ⠹ Container mysql-1          Starting                                                                      1.2s
 ⠹ Container mail-1           Starting                                                                      1.2s
 ⠹ Container redis-1          Starting                                                                      1.2s
 ⠹ Container appname-1          Starting                                                                      1.2s
Error response from daemon: crun: write to `/proc/self/oom_score_adj`: Permission denied: OCI permission denied
```

### System details

Bare Metal
EndeavourOS (Arch repos)

Package versions: 
```
❯ yay -Q|grep -E "crun|podman|docker"
crun 1.9-1
docker-compose 2.20.3-1
dockerfile-language-server 0.10.2-1
podman 4.6.2-1
podman-compose 1.0.6-3
podman-desktop 1.3.1-1
podman-dnsname 1.3.1-2
podman-docker 4.6.2-1
```
