### ISSUE TITLE
timezone not being set on FCOS via ignition

### ISSUE THREAD

**Issue by baude** [coreos/fedora-coreos-tracker#1580]
### Describe the bug

https://docs.fedoraproject.org/en-US/fedora-coreos/time-zone/#_setting_the_time_zone_via_ignition suggests the timezone can be set with a symlink.  This indeed used to work but does not seemingly work anymore.

I might be missing something obvious in which case it is user error.

### Reproduction steps

Use a ignition config with a symlink foir /etc/localtime.

### Expected behavior

i expect after boot that timedatectl or maybe even date shows the set timezone.

### Actual behavior

It always shows UTC

### System details

- podman machine

### Butane or Ignition config

```yaml
Here is a snipped of the ignition file.    

  {
        "group": {
          "name": "root"
        },
        "overwrite": false,
        "path": "/etc/localtime",
        "user": {
          "name": "root"
        },
        "hard": false,
        "target": "\\usr\\share\\zoneinfo\\HST"
      }
```
