### ISSUE TITLE
Feature Request: Disable all DHCP requests

### ISSUE THREAD

**Issue by comminutus** [coreos/fedora-coreos-tracker#1609]
# Feature Request #
Hello, in our environment we often teardown and recreate our cluster.  This results in several DHCP requests - 1 per node that is being provisioned.  I've already [disabled automatic network configuration](https://docs.fedoraproject.org/en-US/fedora-coreos/sysconfig-network-configuration/#_disabling_automatic_configuration_of_ethernet_devices) and [use static IP addresses](https://docs.fedoraproject.org/en-US/fedora-coreos/sysconfig-network-configuration/#_configuring_a_static_ip) using NetworkManager, but these modifications occur after the LiveCD is booted.

I've set the `offline: true` value inside of an `install.yaml` file as part of my settings, which gets embedded via `coreos-installer iso ignition embed at `/etc/coreos/installer.d/install.yaml`.  Here's the contents of the file that gets embedded:
```
variant: fcos
version: 1.5.0
storage:
  files:
    - path: /var/roothome/install.ign
      contents:
        local: install.ign

    - path: /etc/coreos/installer.d/install.yaml
      contents:
        local: install.yaml
```
However, despite setting `offline` to `true`, I'm still seeing DHCP requests come through during the LiveCD boot process.  I tried turning off my DHCP server, and the process which requests a DHCP address eventually times out but the installation still succeeds onto the hard disk.

## Desired Feature ##
Have some way to completely disable all network requests / DHCP requests during the LiveCD boot process.

**Comment by travier** [comment]
Moved to the tracker as this is a Fedora CoreOS issue.

**Comment by jlebon** [comment]
This should be fixed by https://github.com/coreos/coreos-installer/pull/1335.

One easy way to test it is to override the `coreos-installer.service` systemd unit with the new content in that PR.

**Comment by comminutus** [comment]
Thanks @jlebon . Since that CoreOS Installer systemd service lives on the live CD itself, how can I override it?  Would I have to build the project with the changes or is there some way to patch an existing ISO?

**Comment by jlebon** [comment]
You can override it via your Ignition config, e.g.

```yaml
systemd:
  units:
  - name: coreos-installer.service
    contents: |
      [Unit]
      ...
```

That said, as CI shows, #1335 is missing some bits. But short-term you can at least use a similar mechanism to remove the `Wants`, e.g. something like

```yaml
systemd:
  units:
  - name: coreos-installer.service
    dropins:
    - name: no-wants.conf
      contents: |
        [Unit]
        Wants=
```
