### ISSUE TITLE
Timed out waiting for device /dev/md/md-var

### ISSUE THREAD

**Issue by mks-h** [coreos/fedora-coreos-tracker#1613]
### Describe the bug

I wish to install CoreOS on my bare-metal machine, but before committing to it, I'm trying to set it up on a QEMU virtual machine made to loosely emulate the actual one. However, it always fails to create RAID, because of a timeout.
The logs:
```
systemd[1]: dev-md-md\x2dvar.device: Job dev-md-md\x2dvar.device/start timed out.
ignition[570]: Timed out waiting for device dev-md-md\x2dvar.device - /dev/md/md-var.
ignition[570]: disks: createFilesystems: op(a) [failed] waiting for devices [/dev/md/md-var]: device unit dev-md-md\x2dvar.device timeout
systemd[1]: dev-md-md\x2dvar.device: Job dev-md-md\x2dvar.device/start failed with result 'timeout'.
... ignition spits out the config here ...
ignition[570]: Ignition failed: failed to create filesystems: failed to wait on filesystems devs: device unit dev-md-md\x2dvar.device timeout
systemd[1]: ignition-disks.service: Main process exited, code=exited, status=1/FAILURE
systemd[1]: ignition-disks.service: Failed with result 'exit-code'.
systemd[1]: Failed to start ignition-disks.service - Ignition (disks).
systemd[1]: Dependency failed for ignition-complete.target - Ignition Complete.
systemd[1]: Dependency failed for initrd.target - Initrd Default Target.
...
```

### Reproduction steps

1. Download the bare metal ISO
`coreos-installer download -p metal -a x86_64 -f iso`
2. Generate the Ignition config
`butane --pretty --strict coreos-timeout-bug.yml > coreos-timeout-bug.ign`
3. Embed the Ignition config into ISO
`coreos-installer iso ignition embed -i coreos-timeout-bug.ign -o coreos-timeout-bug.iso fedora-coreos-38.20231027.3.2-live.x86_64.iso`
4. Create two QEMU disks
`qemu-img create -f qcow2 coreos-timeout-bug-drive1.qcow 10G && qemu-img create -f qcow2 coreos-timeout-bug-drive2.qcow 10G`
5. Run QEMU
```
qemu-kvm \
	-cpu core2duo \
	-m 4096 \
	-device ich9-ahci,id=ahci \
	-blockdev driver=file,node-name=file0,filename=coreos-timeout-bug-drive1.qcow \
	-blockdev driver=file,node-name=file1,filename=coreos-timeout-bug-drive2.qcow \
	-blockdev driver=qcow2,node-name=drive0,file=file0 \
	-blockdev driver=qcow2,node-name=drive1,file=file1 \
	-device ide-hd,drive=drive0,bus=ahci.0 \
	-device ide-hd,drive=drive1,bus=ahci.1 \
	-device qemu-xhci,id=xhci \
	-drive if=none,id=usbstick,format=raw,file=coreos-timeout-bug.iso \
	-device usb-storage,drive=usbstick,bus=xhci.0,bootindex=1
```
6. Receive the "Press Enter for maintenance" message, and press Enter
7. Use `journalctl` to see the error in full, at around 82%

### Expected behavior

Install and work

### Actual behavior

Time out on RAID creation

### System details

- QEMU with Bare Metal ISO
- fedora-coreos-38.20231027.3.2-live.x86_64.iso

### Butane or Ignition config

```yaml
variant: fcos
version: 1.5.0
storage:
  disks:
    - device: /dev/sda
      partitions:
        - label: root
          number: 4
          size_mib: 8192
          resize: true
        - label: var-1
          size_mib: 200
    - device: /dev/sdb
      partitions:
        - label: var-2
          size_mib: 200
  raid:
    - name: md-raid
      level: raid1
      devices:
        - /dev/disk/by-partlabel/var-1
        - /dev/disk/by-partlabel/var-2
  filesystems:
    - device: /dev/md/md-var
      path: /var
      format: xfs
      label: var
```
