### ISSUE TITLE
WARNING: SCSI device dm-0 has no device ID on LUKS device

### ISSUE THREAD

**Issue by freedge** [coreos/fedora-coreos-tracker#1712]
### Describe the bug

Booting CoreOS with an extra disk configured with luks encryption, I am getting this warning:

```
# journalctl -t  55-scsi-sg3_id.rules --no-pager
Apr 23 07:11:48 localhost 55-scsi-sg3_id.rules[1110]: WARNING: SCSI device dm-0 has no device ID, consider changing .SCSI_ID_SERIAL_SRC in 00-scsi-sg3_config.rules
Apr 23 07:11:48 localhost 55-scsi-sg3_id.rules[1141]: WARNING: SCSI device dm-0 has no device ID, consider changing .SCSI_ID_SERIAL_SRC in 00-scsi-sg3_config.rules
Apr 23 07:11:53 localhost 55-scsi-sg3_id.rules[1286]: WARNING: SCSI device dm-0 has no device ID, consider changing .SCSI_ID_SERIAL_SRC in 00-scsi-sg3_config.rules
Apr 23 07:11:53 localhost 55-scsi-sg3_id.rules[1289]: WARNING: SCSI device dm-0 has no device ID, consider changing .SCSI_ID_SERIAL_SRC in 00-scsi-sg3_config.rules
Apr 23 07:11:55 localhost 55-scsi-sg3_id.rules[1381]: WARNING: SCSI device dm-0 has no device ID, consider changing .SCSI_ID_SERIAL_SRC in 00-scsi-sg3_config.rules
Apr 23 07:11:55 localhost 55-scsi-sg3_id.rules[1412]: WARNING: SCSI device dm-0 has no device ID, consider changing .SCSI_ID_SERIAL_SRC in 00-scsi-sg3_config.rules
Apr 23 07:11:57 localhost 55-scsi-sg3_id.rules[1448]: WARNING: SCSI device dm-0 has no device ID, consider changing .SCSI_ID_SERIAL_SRC in 00-scsi-sg3_config.rules
Apr 23 07:11:58 localhost 55-scsi-sg3_id.rules[1478]: WARNING: SCSI device dm-0 has no device ID, consider changing .SCSI_ID_SERIAL_SRC in 00-scsi-sg3_config.rules
Apr 23 07:11:58 localhost 55-scsi-sg3_id.rules[1508]: WARNING: SCSI device dm-0 has no device ID, consider changing .SCSI_ID_SERIAL_SRC in 00-scsi-sg3_config.rules
Apr 23 07:11:48 localhost 55-scsi-sg3_id.rules[1110]: WARNING: SCSI device dm-0 has no device ID, consider changing .SCSI_ID_SERIAL_SRC in 00-scsi-sg3_config.rules
Apr 23 07:11:48 localhost 55-scsi-sg3_id.rules[1141]: WARNING: SCSI device dm-0 has no device ID, consider changing .SCSI_ID_SERIAL_SRC in 00-scsi-sg3_config.rules
Apr 23 07:11:53 localhost 55-scsi-sg3_id.rules[1286]: WARNING: SCSI device dm-0 has no device ID, consider changing .SCSI_ID_SERIAL_SRC in 00-scsi-sg3_config.rules
Apr 23 07:11:53 localhost 55-scsi-sg3_id.rules[1289]: WARNING: SCSI device dm-0 has no device ID, consider changing .SCSI_ID_SERIAL_SRC in 00-scsi-sg3_config.rules
Apr 23 07:11:55 localhost 55-scsi-sg3_id.rules[1381]: WARNING: SCSI device dm-0 has no device ID, consider changing .SCSI_ID_SERIAL_SRC in 00-scsi-sg3_config.rules
Apr 23 07:11:55 localhost 55-scsi-sg3_id.rules[1412]: WARNING: SCSI device dm-0 has no device ID, consider changing .SCSI_ID_SERIAL_SRC in 00-scsi-sg3_config.rules
Apr 23 07:11:57 localhost 55-scsi-sg3_id.rules[1448]: WARNING: SCSI device dm-0 has no device ID, consider changing .SCSI_ID_SERIAL_SRC in 00-scsi-sg3_config.rules
Apr 23 07:11:58 localhost 55-scsi-sg3_id.rules[1478]: WARNING: SCSI device dm-0 has no device ID, consider changing .SCSI_ID_SERIAL_SRC in 00-scsi-sg3_config.rules
Apr 23 07:11:58 localhost 55-scsi-sg3_id.rules[1508]: WARNING: SCSI device dm-0 has no device ID, consider changing .SCSI_ID_SERIAL_SRC in 00-scsi-sg3_config.rules
Apr 23 07:12:02 core 55-scsi-sg3_id.rules[2104]: WARNING: SCSI device dm-0 has no device ID, consider changing .SCSI_ID_SERIAL_SRC in 00-scsi-sg3_config.rules
```

### Reproduction steps

1. create VM with 2 disks
2. configure second disk for luks decryption
3. get a warning

### Expected behavior

no warning

### Actual behavior

a warning

### System details

```
# rpm-ostree status
State: idle
AutomaticUpdatesDriver: Zincati
  DriverState: active; periodically polling for updates (last checked Tue 2024-04-23 05:43:04 UTC)
Deployments:
● fedora:fedora/x86_64/coreos/next
                  Version: 40.20240416.1.1 (2024-04-19T04:22:07Z)
                   Commit: 0006e2ccac33f9b6e944c34ab5bfc1cecacd505fb514488fcc5cb35c151af90b
             GPGSignature: Valid signature by 115DF9AEF857853EE8445D0A0727707EA15B79CC
```

This is on hyper-v, booted with
```
Expand-Archive .\Downloads\fedora-coreos-40.20240416.1.1-hyperv.x86_64.vhdx.zip -DestinationPath .\Downloads\ -Force
New-VM -Name core -MemoryStartupBytes 4096MB -Generation 2 -BootDevice VHD -VHDPath .\Downloads\fedora-coreos-40.20240416.1.1-hyperv.x86_64.vhdx -SwitchName "Default Switch"
Set-Vm core -MemoryMinimumBytes 2048MB  -CheckpointType disabled -Notes "Fedora CoreOS 40"
Set-VMFirmware -VMName core -EnableSecureBoot Off
Set-VMKeyProtector -VMName core -NewLocalKeyProtector
Enable-VMTPM -VMName core
Add-VMNetworkAdapter -SwitchName br-mine -VmName core -Name eth1
New-VHD -Path .\Downloads\extra.vhdx -SizeBytes 400MB -Dynamic
Add-VMHardDiskDrive -VMName core -Path .\Downloads\extra.vhdx
scp stream:hyperv.ign .
.\Downloads\kvpctl.exe core add-ign hyperv.ign
Start-VM core
```

### Butane or Ignition config

```yaml
variant: fcos
version: 1.5.0

passwd:
  users:
    - name: frigo
      ssh_authorized_keys:
      - "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA3EVo0gswYxVGq6MEHUQTVnDpYLnmWnZnRcYGfuLzrULcPX4tgBYpILOlxI0lZXMj+Ebnf2FWohp1MLbC349uwI92CMTwSk6blWW/LX1NJWG5vKDmUx25B7DiPFdIMWp23EJZk/x5NshFwgooKgzDKj8/Y5lQeEI6OsGoOPxGNbUD5/rQDALnEybrXgPckyOlqNa43TB9/rDFa4KABUEHXQDWPzmsWRONVYIRjJ9wUrzgvAdJo6Q6qDkJpMkXpzFdSjcwGbWx4Dx9ylWp5zQSHXTfI3mqbAmW2lCDOEUKGUZVyYeHjFtsPKWKx+5hVUsCiK3V9zhJVlOnGtjr8Obbyw=="
      system: false
      groups:
      - wheel
      - sudo

storage:
  disks:
    - device: /dev/disk/by-id/coreos-boot-disk
      wipe_table: false
      partitions:
        - label: root
          number: 4
          size_mib: 0
          resize: true
    - device: /dev/sdb
      wipe_table: true
      partitions:
        - label: etcd
          number: 1
          size_mib: 0
          resize: true

  filesystems:
    - device: /dev/mapper/etcd
      format: xfs
      label: etcd
      wipe_filesystem: true
      with_mount_unit: true
      path: /var/lib/etcd

  luks:
    - clevis:
        tpm2: true
      device: /dev/disk/by-partlabel/etcd
      label: luks-etcd
      wipe_volume: true
      name: etcd
      options:
      - "--sector-size"
      - "512"
      discard: true
      open_options:
        - --perf-no_read_workqueue
        - --perf-no_write_workqueue

  files:
    - path: /etc/udev/rules.d/01-block.rules
      mode: 0644
      contents:
        inline: |
          KERNEL=="sd*[!0-9]", KERNELS=="0:0:0:1", ATTRS{vendor}=="Msft*", ATTR{size}=="819200", SYMLINK+="disk-etcd"

    - path: /etc/hosts
      contents:
        inline: |
          127.0.0.1 localhost localhost.localdomain localhost4 localhost4.localdomain4
          ::1       localhost localhost.localdomain localhost6 localhost6.localdomain6
          10.224.123.3 core
      overwrite: true

    - path: /etc/NetworkManager/system-connections/eth0.nmconnection
      mode: 0600
      contents:
        inline: |
          [connection]
          id=eth0
          type=ethernet
          interface-name=eth0
          [ipv4]
          address1=10.224.123.3/20,10.224.123.1
          dns=192.168.1.254;
          dns-search=
          may-fail=false
          method=manual

    - path: /etc/NetworkManager/system-connections/eth1.nmconnection
      mode: 0600
      contents:
        inline: |
          [connection]
          id=eth1
          type=ethernet
          interface-name=eth1
          [ipv4]
          address1=172.0.0.3/24
          dns=
          dns-search=
          may-fail=false
          method=manual

    - path: /etc/chrony.conf
      mode: 0644
      overwrite: true
      contents:
        inline: |
          local stratum 2
          refclock PHC /dev/ptp_hyperv poll 3 dpoll -2 offset 0
          driftfile /var/lib/chrony/drift
          makestep 1.0 -1
          rtcsync
          keyfile /etc/chrony.keys
          ntsdumpdir /var/lib/chrony
          leapsectz right/UTC
          logdir /var/log/chrony

    - path: /etc/hostname
      mode: 0644
      contents:
        inline: core

  links:
    - path: /etc/localtime
      target: ../usr/share/zoneinfo/Europe/Monaco
```

### Additional information

I would also like to not reference "/dev/sdb" but instead rely on "/dev/disk-etcd" as created using my own rules, but this does not seem possible.

```
# udevadm info /sys/class/block/sdb
P: /devices/LNXSYSTM:00/LNXSYBUS:00/ACPI0004:00/VMBUS:00/661f4cb6-17d5-400c-8b36-33017798d1f0/host0/target0:0:0/0:0:0:1/block/sdb
M: sdb
U: block
T: disk
D: b 8:16
N: sdb
L: 0
S: disk/by-path/acpi-VMBUS:00-vmbus-661f4cb617d5400c8b3633017798d1f0-lun-1
S: disk/by-diskseq/2
S: disk/by-id/scsi-36002248004661d6a8cc9dc3d0663a38f
S: disk/by-id/wwn-0x6002248004661d6a8cc9dc3d0663a38f
Q: 2
E: DEVPATH=/devices/LNXSYSTM:00/LNXSYBUS:00/ACPI0004:00/VMBUS:00/661f4cb6-17d5-400c-8b36-33017798d1f0/host0/target0:0:0/0:0:0:1/block/sdb
E: SUBSYSTEM=block
E: DEVNAME=/dev/sdb
E: DEVTYPE=disk
E: DISKSEQ=2
E: MAJOR=8
E: MINOR=16
E: USEC_INITIALIZED=32260489
E: ID_SCSI=1
E: ID_VENDOR=Msft
E: ID_VENDOR_ENC=Msft\x20\x20\x20\x20
E: ID_MODEL=Virtual_Disk
E: ID_MODEL_ENC=Virtual\x20Disk\x20\x20\x20\x20
E: ID_REVISION=1.0
E: ID_TYPE=disk
E: ID_SERIAL=36002248004661d6a8cc9dc3d0663a38f
E: ID_SERIAL_SHORT=6002248004661d6a8cc9dc3d0663a38f
E: ID_WWN=0x6002248004661d6a
E: ID_WWN_VENDOR_EXTENSION=0x8cc9dc3d0663a38f
E: ID_WWN_WITH_EXTENSION=0x6002248004661d6a8cc9dc3d0663a38f
E: ID_BUS=scsi
E: ID_PATH=acpi-VMBUS:00-vmbus-661f4cb617d5400c8b3633017798d1f0-lun-1
E: ID_PATH_TAG=acpi-VMBUS_00-vmbus-661f4cb617d5400c8b3633017798d1f0-lun-1
E: ID_PART_TABLE_UUID=cd70cc6b-3527-4eb8-84b4-7fd548a19e71
E: ID_PART_TABLE_TYPE=gpt
E: SCSI_TPGS=0
E: SCSI_TYPE=disk
E: SCSI_VENDOR=Msft
E: SCSI_VENDOR_ENC=Msft\x20\x20\x20\x20
E: ID_SCSI_INQUIRY=1
E: SCSI_IDENT_LUN_T10=4d5346542020202004661d6a8cc9d648a9cbdc3d0663a38f
E: SCSI_IDENT_LUN_NAA_REGEXT=6002248004661d6a8cc9dc3d0663a38f
E: DEVLINKS=/dev/disk/by-path/acpi-VMBUS:00-vmbus-661f4cb617d5400c8b3633017798d1f0-lun-1 /dev/disk/by-diskseq/2 /dev/disk/by-id/scsi-36002248004661d6a8cc9dc3d0663a38f /dev/disk/by-id/wwn-0x6002248004661d6a8c>E: TAGS=:systemd:
E: CURRENT_TAGS=:systemd:

# udevadm info /sys/class/block/dm-0
P: /devices/virtual/block/dm-0
M: dm-0
R: 0
U: block
T: disk
D: b 253:0
N: dm-0
L: 0
S: mapper/etcd
S: disk/by-id/dm-name-etcd
S: disk/by-uuid/24550cd7-a218-4a2c-9c2a-3305733061d6
S: disk/by-id/dm-uuid-CRYPT-LUKS2-5bf3c378553249eb85f17f53a9040f8c-etcd
S: disk/by-label/etcd
Q: 4
E: DEVPATH=/devices/virtual/block/dm-0
E: SUBSYSTEM=block
E: DEVNAME=/dev/dm-0
E: DEVTYPE=disk
E: DISKSEQ=4
E: MAJOR=253
E: MINOR=0
E: USEC_INITIALIZED=25372084
E: DM_UDEV_DISABLE_LIBRARY_FALLBACK_FLAG=1
E: DM_UDEV_PRIMARY_SOURCE_FLAG=1
E: DM_UDEV_RULES_VSN=2
E: DM_ACTIVATION=1
E: DM_NAME=etcd
E: DM_UUID=CRYPT-LUKS2-5bf3c378553249eb85f17f53a9040f8c-etcd
E: DM_SUSPENDED=0
E: ID_FS_LABEL=etcd
E: ID_FS_LABEL_ENC=etcd
E: ID_FS_UUID=24550cd7-a218-4a2c-9c2a-3305733061d6
E: ID_FS_UUID_ENC=24550cd7-a218-4a2c-9c2a-3305733061d6
E: ID_FS_SIZE=334475264
E: ID_FS_LASTBLOCK=98043
E: ID_FS_BLOCKSIZE=4096
E: ID_FS_TYPE=xfs
E: ID_FS_USAGE=filesystem
E: SYSTEMD_READY=1
E: DEVLINKS=/dev/mapper/etcd /dev/disk/by-id/dm-name-etcd /dev/disk/by-uuid/24550cd7-a218-4a2c-9c2a-3305733061d6 /dev/disk/by-id/dm-uuid-CRYPT-LUKS2-5bf3c378553249eb85f17f53a9040f8c-etcd /dev/disk/by-label/e>E: TAGS=:systemd:
E: CURRENT_TAGS=:systemd:

```

**Comment by jbtrystram** [comment]
sg3_utils got updated recently and caused some troubles. 
Thanks for reporting 

According to your `udevadm info` output, your udev rule seems to work however : 
```
E: DEVLINKS=/dev/disk/by-id/scsi-36..... /dev/disk-etcd .....
```

**Comment by freedge** [comment]
the udev rule works but is too late, it should be present in the initramdisk for me to be able to reference it in the disks part.

**Comment by jbtrystram** [comment]
can you try to boot with the following kernel argument : `udev.scsi_symlink_src=S`  ?

**Comment by jbtrystram** [comment]
I was trying to replicate your issue, but I see two different issues there : 

1 - your additional disk (microsoft virtual disk)- /dev/sdb, not showing up with as `/dev/disk-etcd`
	For this one there isn't much we can do to get your udev rule into initramfs. You should reference it through it's WWN from the ignition config to have a non-ambiguous pointer : `disk/by-id/wwn-0x600224806509d192d362bf93d8cd70ed`
	You can probably specify a WWN value at creation time through hyper-v options

2 - The decrypted device mapper `dm-0` generates warning issues in the logs : it looks like `luksformat` does not allow to set custom scsi serial values to the result device, I am investigating

**Comment by travier** [comment]
```
  luks:
    - clevis:
        tpm2: true
      device: /dev/disk/by-partlabel/etcd
      label: luks-etcd
      wipe_volume: true
      name: etcd
      options:
      - "--sector-size"
      - "512"
      discard: true
      open_options:
        - --perf-no_read_workqueue
        - --perf-no_write_workqueue
```

It's been a while since I've looked at LUKS setup but that won't work from my understanding. You are referencing the device by a label that you are asking Ignition to create so Ignition won't be able to find it.
