### ISSUE TITLE
systemd-systemd unmerge + merge results in broken system

### ISSUE THREAD

**Issue by quentin9696** [coreos/fedora-coreos-tracker#1744]
### Describe the bug

Systemd sysext don't work properly on FCOS. Extensions are not merged with the root filesystem. Some directories works, some other don't

### Reproduction steps

1. `ls -al /usr/local/bin` will return only `bar` file
1. `systemctl stop systemd-sysext`
1. `ls -al /usr/local/bin` will return only `baz` file

### Expected behavior

content of `/usr/local/bin` should have both `bar` and `baz` files as it's done with `/usr/bin/foo`

### Actual behavior

Files are not merged, only extensions file are display

### System details

AWS instance

```
State: idle
AutomaticUpdatesDriver: Zincati
  DriverState: active; periodically polling for updates (last checked Wed 2024-06-05 15:43:19 UTC)
BootedDeployment:
● fedora:fedora/x86_64/coreos/stable
                  Version: 40.20240504.3.0 (2024-05-20T18:00:04Z)
                   Commit: 72cf2f80ba1496d478e110d03e1199d9d21382840e96ffeddf4303eb040fbb55
             GPGSignature: Valid signature by 115DF9AEF857853EE8445D0A0727707EA15B79CC
```

### Butane or Ignition config

```yaml
variant: fcos
version: 1.5.0
storage:
  directories:
    - path: /var/lib/extensions
    - path: /var/lib/extensions/foo
    - path: /var/lib/extensions/foo/usr
    - path: /var/lib/extensions/foo/usr/bin
    - path: /var/lib/extensions/foo/usr/local
    - path: /var/lib/extensions/foo/usr/local/bin
    - path: /var/lib/extensions/foo/usr/lib
    - path: /var/lib/extensions/foo/usr/lib/extension-release.d
  files:
    - path: /var/lib/extensions/foo/usr/bin/foo
      mode: 0755
      contents:
        inline: |
          echo "Hello World in bin extension"
    - path: /var/lib/extensions/foo/usr/local/bin/bar
      mode: 0755
      contents:
        inline: |
          echo "Hello World - in local/bin extension"
    - path: /usr/local/bin/baz
      mode: 0755
      contents:
        inline: |
          echo "Hello World - in local/bin root"
    - path: /var/lib/extensions/foo/usr/lib/extension-release.d/extension-release.foo
      contents:
        inline: |
          ID="_any"
systemd:
  units:
    - name: systemd-sysext.service
      enabled: true
```

### Additional information

Run a brand new FCOS, manually create systemd sysext (you can do the same as it's done in provided butane) and run `systemd-systemd merge` will corrupt FCOS. For example, trying to `sudo su` will give you the error
> $ sudo su
sudo: account validation failure, is your account locked?
sudo: a password is required
