### ISSUE TITLE
Different partition layout after re-provisioning between version 39 and 40

### ISSUE THREAD

**Issue by iwanb** [coreos/fedora-coreos-tracker#1745]
### Describe the bug

Re-provisioning a bare metal machine using the example storage from the doc, first installed with `39.20231101.3.0`, then reinstalled with `40.20240519.3.0`, leads to different partition layout, and thus the reprovisioning fails.

### Reproduction steps

I've reproduced this in qemu here: https://github.com/iwanb/coreos-reprovision-baremetal

I haven't tried to narrow down the version where the change was introduced.

### Expected behavior

Partitions stay the same when re-provisioning.

From this doc I would expect it to be the case: https://docs.fedoraproject.org/en-US/fedora-coreos/bare-metal/#_data_persistence

I could imagine that it can be hard to provide full backwards and forward compatibility for this, so an alternative would be to document how to specify the partitions more precisely, and warn that re-provisioning could otherwise break.

### Actual behavior

Partition difference, the var partition is smaller in the new version:
```
$ diff disk-before disk-after
6c6
< Disk identifier: 333AA36F-1E5A-4770-9721-3217CD45AD37
---
> Disk identifier: 8FD44CE1-F723-46C4-9585-1314E286CC33
13c13
< /dev/nbd0p5 17827840 41943006 24115167 11.5G Linux filesystem
---
> /dev/nbd0p5 17827840 41940992 24113153 11.5G Linux filesystem
```

### System details

Bare metal (saw it there first) and QEMU (reproduced).

### Butane or Ignition config

```yaml
Butane config (from https://docs.fedoraproject.org/en-US/fedora-coreos/storage/#_setting_up_separate_var_mounts):

variant: fcos
version: 1.5.0
storage:
  disks:
  - # The link to the block device the OS was booted from.
    device: /dev/disk/by-id/coreos-boot-disk
    # We do not want to wipe the partition table since this is the primary
    # device.
    wipe_table: false
    partitions:
    - number: 4
      label: root
      # Allocate at least 8 GiB to the rootfs. See NOTE above about this.
      size_mib: 8192
      resize: true
    - size_mib: 0
      # We assign a descriptive label to the partition. This is important
      # for referring to it in a device-agnostic way in other parts of the
      # configuration.
      label: var
  filesystems:
    - path: /var
      device: /dev/disk/by-partlabel/var
      # We can select the filesystem we'd like.
      format: ext4
      # Ask Butane to generate a mount unit for us so that this filesystem
      # gets mounted in the real root.
      with_mount_unit: true
```
```


### Additional information

_No response_

**Comment by hrismarin** [comment]
In the docs section you point to ([Data persistence](https://docs.fedoraproject.org/en-US/fedora-coreos/bare-metal/#_data_persistence)), there is a link to [Using persistent state](https://docs.fedoraproject.org/en-US/fedora-coreos/live-booting/#_using_persistent_state) section where it states that you can safely set `wipe_partition_entry` when reusing a disk, since those don’t modify the contents of a [partition](https://coreos.github.io/ignition/operator-notes/#partition-reuse-semantics). Adding `wipe_partition_entry: true` to your Butane config should allow you to re-provision nodes with different releases of FCOS while maintaining persistent state.

So your butane configuration could be like this:

```yaml
variant: fcos
version: 1.5.0
storage:
  disks:
  - # The link to the block device the OS was booted from.
    device: /dev/disk/by-id/coreos-boot-disk
    # We do not want to wipe the partition table since this is the primary
    # device.
    wipe_table: false
    partitions:
    - number: 4
      label: root
      # Allocate at least 8 GiB to the rootfs. See NOTE above about this.
      size_mib: 8192
      resize: true
    - size_mib: 0
      # Check if existing partition matches the specified one,
      # delete existing partition and create specified partition
      # if it does not match.
      wipe_partition_entry: true
      # We assign a descriptive label to the partition. This is important
      # for referring to it in a device-agnostic way in other parts of the
      # configuration.
      label: var
  filesystems:
    - path: /var
      device: /dev/disk/by-partlabel/var
      # We can select the filesystem we'd like.
      format: ext4
      # Ask Butane to generate a mount unit for us so that this filesystem
      # gets mounted in the real root.
      with_mount_unit: true
```
