### ISSUE TITLE
Podman Container Bridge Networking Doesn't Work IF docker commands have been run on a booted new Next node

### ISSUE THREAD

**Issue by fifofonix** [coreos/fedora-coreos-tracker#1822]
### Describe the bug

Podman bridge network created for a new container does not operate successfully IF the node has first run a docker command (as simple as `docker ps`). Can't even access DNS servers.

Note: Concurrent docker/podman usage is not recommended per FCOS FAQ for several years. However, up until now operations as simple as this have succeeded allowing users in most cases to use both in parallel (up to current `test`)

### Reproduction steps

1. Provision a minimal new `next` node on any platform VMWare/AWS.
2. Launch a podman container and verify its networking: `sudo podman run -it fedora:41 curl -v google.com` # Succeeds
3. Reboot node
4. Run `docker ps` activating docker and possibly triggering some networking operation of some sort
5. Simple podman container networking now fails with no ability to access DNS servers even: `sudo podman run -it fedora:41 curl -v google.com` # Fails

### Expected behavior

Podman container can access the internet 

### Actual behavior

Podman container can not even access DNS servers.

### System details

- Reproduced on vSphere and AWS.

### Butane or Ignition config

```yaml
variant: fcos
version: 1.4.0
passwd:
  users:
    # The core user has sudo privileges by default.
    - name: core
storage:
  files:
    - path: /etc/hostname
      mode: 0420
      overwrite: true
      contents:
        inline: "d-mini-1"
  files:
    - path: /etc/NetworkManager/system-connections/Wired\ connection\ 1
      mode: 0600
      contents:
        inline: |
          [connection]
          id=Wired connection 1
          type=ethernet
          [ipv4]
          dns-search=ec2.internal;amce.com;ACME.COM;
          method=auto
          [ipv6]
          addr-gen-mode=default
          method=auto
    - path: /etc/ssh/sshd_config.d/05-acme.conf
      mode: 0644
      overwrite: true
      contents:
        inline: |
          TrustedUserCAKeys /etc/ssh/trusted-user-ca-keys.pem
          HostCertificate /etc/ssh/ssh_host_ecdsa_key-cert.pub
    - path: /etc/sysconfig/docker
      mode: 0644
      overwrite: true
      contents:
        # We customise this because we want to suppress --live-restore which
        # is incompatible with docker swarm.
        inline: |
          OPTIONS="--selinux-enabled
          --default-ulimit nofile=64000:64000
          --init-path /usr/libexec/docker/docker-init
          --userland-proxy-path /usr/libexec/docker/docker-proxy
          "
    - path: /etc/sysconfig/chronyd
      mode: 0644
      overwrite: true
      contents:
        inline: |
          OPTIONS="'server acme-ntp-1'
          "
```

### Additional information

Non-working output:
```
core@d-pdm-mini-1:~$ sudo podman run -it fedora:41 curl -v google.com
* Could not resolve host: google.com
* shutting down connection #0
curl: (6) Could not resolve host: google.com
```
