### ISSUE TITLE
Enabling DeviceTree on Pi 4 8 GB causes boot to fail (even Keyboard is not regoniced anymore)

### ISSUE THREAD

**Issue by PackElend** [coreos/fedora-coreos-tracker#1856]
### Describe the bug

I provisioned Fedora CoreOS on the Raspberry Pi 4.
I'm able to deactivate the 3 GB limit and boot into CoreOS.

As soon as I activate DeviceTree in Bios it hangs after finishing [systemd-vconsole-setup.service, systemd-vconsole-setup - Configure the virtual console at boot at Linux.org](https://www.linux.org/docs/man8/systemd-vconsole-setup.html).
<details>
  <summary>Image, vconsole</summary>
![image](https://github.com/user-attachments/assets/6dad27af-170a-4905-9a9b-21eee8067304)
</details>

It hangs at [dracut.initqueue](https://community.frame.work/t/fedora-39-boot-hanging-dracut-initqueue/42883)
<details>
  <summary>Image, initqueue</summary>

![image](https://github.com/user-attachments/assets/5c98d1ce-d913-416f-82b9-ba2659ba3f0a)

</details>

[Provisioning Fedora CoreOS on the Raspberry Pi 4 :: Fedora Docs](https://docs.fedoraproject.org/en-US/fedora-coreos/provisioning-raspberry-pi4/#_edk2_combined_fedora_coreos_edk2_firmware_disk)

### Reproduction steps

1. [Provisioning Fedora CoreOS on the Raspberry Pi 4 :: Fedora Docs](https://docs.fedoraproject.org/en-US/fedora-coreos/provisioning-raspberry-pi4/#_edk2_combined_fedora_coreos_edk2_firmware_disk)
2. boot
3. power off
4. activate DeviceTree
5. boot

### Expected behavior

normal boot

### Actual behavior

It hangs at dracut.initqueue

### System details

bare matel on Raspberry Pi4

admin@CoreOS:~$ sudo rpm-ostree status
State: idle
AutomaticUpdatesDriver: Zincati
  DriverState: active; periodically polling for updates (last checked Tue 2024-12-31 21:55:19 UTC)
Deployments:
● fedora:fedora/aarch64/coreos/stable
                  Version: 41.20241122.3.0 (2024-12-16T21:54:30Z)
               BaseCommit: 4c2285b3993e7c505ae167fbcf1d14dfa353a7c05732c79e7ecd67732e74ef55
             GPGSignature: Valid signature by 466CF2D8B60BC3057AA9453ED0622462E99D6AD1
          LayeredPackages: iwlwifi-dvm-firmware NetworkManager-wifi

  fedora:fedora/aarch64/coreos/stable
                  Version: 41.20241122.3.0 (2024-12-16T21:54:30Z)
                   Commit: 4c2285b3993e7c505ae167fbcf1d14dfa353a7c05732c79e7ecd67732e74ef55
             GPGSignature: Valid signature by 466CF2D8B60BC3057AA9453ED0622462E99D6AD1

### Butane or Ignition config

```yaml
variant: fcos
version: 1.0.0
passwd:
  users:
    - name: admin
      groups:
        - "sudo"
        - "docker"
      password_hash: hidden

systemd:
  units:
    - name: docker.service
      enabled: true

    - name: containerd.service
      enabled: true
    - name: serial-getty@ttyS0.service
      dropins:
      - name: autologin-core.conf
        contents: |
          [Service]
          # Override Execstart in main unit
          ExecStart=
          # Add new Execstart with `-` prefix to ignore failure
          ExecStart=-/usr/sbin/agetty --autologin admin --noclear %I $TERM
          TTYVTDisallocate=no          
storage:
  files:
    - path: /etc/hostname
      mode: 0644
      contents:
        inline: |
          CoreOS          
    - path: /etc/profile.d/systemd-pager.sh
      mode: 0644
      contents:
        inline: |
          # Tell systemd to not use a pager when printing information
          export SYSTEMD_PAGER=cat          
    - path: /etc/sysctl.d/20-silence-audit.conf
      mode: 0644
      contents:
        inline: |
          # Raise console message logging level from DEBUG (7) to WARNING (4)
          # to hide audit messages from the interactive console
          kernel.printk=4          
    - path: /etc/ssh/sshd_config.d/20-enable-passwords.conf
      mode: 0644
      contents:
        inline: |
          # Enable SSH password login
          PasswordAuthentication yes   
	- path: /etc/NetworkManager/system-connections/wifi1.nmconnection
      mode: 0600
      contents:
        inline: |
          [connection]
          id=Local
          type=wifi
          interface-name=wlan0

          [wifi]
          ssid=SRF_E090
          mode=infrastructure

          [wifi-security]
          key-mgmt=wpa-psk
          psk=hidden

          [ipv4]
          method=auto

          [ipv6]
          method=auto

    - path: /etc/NetworkManager/system-connections/wifi2.nmconnection
      mode: 0600
      contents:
        inline: |
          [connection]
          id=MobileHotSpot
          type=wifi
          interface-name=wlan0

          [wifi]
          ssid=FP4
          mode=infrastructure

          [wifi-security]
          key-mgmt=wpa-psk
          psk=hidden

          [ipv4]
          method=auto

          [ipv6]
          method=auto		
		  
  links:
    - path: /etc/localtime
      target: ../usr/share/zoneinfo/Europe/Berlin
```

### Additional information

I provisioned 100% on Raspberry Pi OS, without any Fedora OS running, using Podman Images.

my procedure from [Producing an Ignition Config :: Fedora Docs](https://docs.fedoraproject.org/en-US/fedora-coreos/producing-ign/) instead [Getting started | Butane](https://coreos.github.io/butane/getting-started/), see https://github.com/coreos/butane/issues/573

```
podman run --interactive --rm --security-opt label=disable \
       --volume ${PWD}:/pwd --workdir /pwd quay.io/coreos/butane:release \
       --pretty --strict config.bu > config.ign
```
than as described on [Provisioning Fedora CoreOS on the Raspberry Pi 4 :: Fedora Docs](https://docs.fedoraproject.org/en-US/fedora-coreos/provisioning-raspberry-pi4/#_edk2_combined_fedora_coreos_edk2_firmware_disk)

1. CoreOS Install
    ```
    FCOSDISK=/dev/sda
    STREAM=stable # or `next` or `testing`
    echo $FCOSDISK
    echo $STREAM
    sudo podman run --pull=always --privileged --rm \
        -v /dev:/dev -v /run/udev:/run/udev -v .:/data -w /data \
        quay.io/coreos/coreos-installer:release \
        install -a aarch64 -s $STREAM -i config.ign $FCOSDISK		   
    ```	
1. UEFI Firmware
    ```	
    FCOSEFIPARTITION=$(lsblk $FCOSDISK -J -oLABEL,PATH  | jq -r '.blockdevices[] | select(.label == "EFI-SYSTEM")'.path)
    mkdir /tmp/FCOSEFIpart
    sudo mount $FCOSEFIPARTITION /tmp/FCOSEFIpart
    pushd /tmp/FCOSEFIpart
    VERSION=v1.34  # use latest one from https://github.com/pftf/RPi4/releases
    sudo curl -LO https://github.com/pftf/RPi4/releases/download/${VERSION}/RPi4_UEFI_Firmware_${VERSION}.zip
    sudo unzip RPi4_UEFI_Firmware_${VERSION}.zip
    sudo rm RPi4_UEFI_Firmware_${VERSION}.zip
    popd
    sudo umount /tmp/FCOSEFIpart	
    ```
