### ISSUE TITLE
The ignition verification passed, but the system initialization failed. What should I do?

### ISSUE THREAD

**Issue by n2aod** [coreos/fedora-coreos-tracker#1860]
![image](https://github.com/user-attachments/assets/8d63e4e7-1efa-498c-b03a-37e2867ea654)

```
variant: fcos
version: 1.5.0

storage:
  disks:
    - device: /dev/nvme0n1
      wipe_table: true
      partitions:
        - label: UEFI
          number: 1
          size_mib: 1024
          start_mib: 0
          wipe_partition_entry: true
          type_guid: "c12a7328-f81f-11d2-ba4b-00a0c93ec93b"
        - label: SWAP
          number: 2
          size_mib: 32768
          start_mib: 1024
          wipe_partition_entry: true
          type_guid: "0657fd6d-a4ab-43c4-84e5-0933c84b4f4f"
        - label: ROOT
          number: 3
          size_mib: 0
          wipe_partition_entry: true
          type_guid: "4f68bce3-e8cd-4db1-96e7-fbcaf984b709"
  filesystems:
    - device: /dev/nvme0n1p1
      format: vfat
      path: /boot/efi
      wipe_filesystem: true
      label: UEFI
      with_mount_unit: true
    - device: /dev/nvme0n1p2
      format: swap
      wipe_filesystem: true
      label: SWAP
      mount_options:
        - "pri=10"
      with_mount_unit: true
    - device: /dev/nvme0n1p3
      format: btrfs
      path: /
      wipe_filesystem: true
      label: ROOT
      options:
        - "-ddup"
      mount_options:
        - "compress=zstd"
      with_mount_unit: true
  links:
    - path: /etc/localtime
      target: /usr/share/zoneinfo/Asia/Shanghai
      overwrite: true
      hard: false
      user:
        id: 0
      group:
        id: 0
  directories:
    - path: /data
      overwrite: true
      mode: 0755
      user:
        id: 1000
      group:
        id: 1000
  files:
    - path: /etc/hostname
      overwrite: true
      mode: 0644
      user:
        id: 0
      group:
        id: 0
      contents:
        inline: "fedora"
    - path: /data/welcome.txt
      overwrite: true
      mode: 0644
      user:
        id: 0
      group:
        id: 0
      contents:
        inline: "Hello Fedora CoreOS"
    - path: /etc/systemd/zram-generator.conf
      overwrite: true
      mode: 0644
      user:
        id: 0
      group:
        id: 0
      contents:
        inline: |
          [zram0]
          zram-size = ram / 2
          compression-algorithm = zstd
          priority = 100

kernel_arguments:
  should_exist:
    - "net.ipv4.ip_forward=1"
    - "net.ipv6.conf.all.forwarding=1"

systemd:
  units:
    - name: systemd-hostnamed.service
      enabled: true

passwd:
  users:
    - name: core
      ssh_authorized_keys:
        - "ssh-ed25519 123456"
      primary_group: core
      groups:
        - wheel
        - users
      uid: 1000
      home_dir: /home/core
      shell: /bin/bash
      system: false
  groups:
    - name: core
      gid: 1000

```
