### ISSUE TITLE
Build quadlets are generating bad build commands when using Pull=

### ISSUE THREAD

**Issue by astroforge** [coreos/fedora-coreos-tracker#1865]
### Describe the bug

After updating to 41.20241215.3.0 (2025-01-06T19:34:31Z), systemd `Build `units that include a `Pull=` setting fail to build. 

The issue appears to be that `podman build` now expects the pull parameter in the format `--pull=newer`, but `podman-system-generator` appears to be generating the build command with the format `--pull newer`.  This causes the `podman build` command to generate the error "Error: accepts at most 1 arg(s), received 2" (numbers may vary depending on how many Build settings are defined).

### Reproduction steps

1. Create a systemd unit file such as the following and save as /etc/containers/systemd/podman.mycontainer_img.build:
```
[Unit]
Description=Container Image Build Service
After=network-online.target podman.service
Requires=podman.service network.target network-online.target

[Build]
ImageTag=localhost/mycontainer
Pull=newer
SetWorkingDirectory=/var/home/roothome/build-mycontainer

[Install]
WantedBy=default.target
```
2. Note that while you would normally need a valid Containerfile in /var/home/roothome/build-mycontainer, however the error occurs before this file is used, and so for the purpose of demonstrating the error it's okay if this doesn't exist.
3.  Generate the systemd units:
```
sudo /usr/lib/systemd/system-generators/podman-system-generator
sudo systemctl daemon-reload
```
4. Attempt to start the build service:
`sudo systemctl start podman.mycontainer_img-build.service`

```
Job for podman.mycontainer_img-build.service failed because the control process exited with error code.
See "systemctl status podman.mycontainer_img-build.service" and "journalctl -xeu podman.mycontainer_img-build.service" for details.
```

5. Inspect journalctl for more details:
journalctl -u podman.mycontainer_img-build.service

```
Jan 18 20:25:24 appcontent systemd[1]: Starting podman.mycontainer_img-build.service - Container Image Build Service...
Jan 18 20:25:24 appcontent podman.mycontainer_img-build[13279]: Error: accepts at most 1 arg(s), received 2
Jan 18 20:25:24 appcontent systemd[1]: podman.mycontainer_img-build.service: Main process exited, code=exited, status=125/n/a
Jan 18 20:25:24 appcontent systemd[1]: podman.mycontainer_img-build.service: Failed with result 'exit-code'.
Jan 18 20:25:24 appcontent systemd[1]: Failed to start podman.mycontainer_img-build.service - Container Image Build Service.
```

Note the specific error: `Error: accepts at most 1 arg(s), received 2`

6. Identify the command that was executed by running:
`systemctl show podman.mycontainer_img-build.service | grep ExecStart=`

`ExecStart={ path=/usr/bin/podman ; argv[]=/usr/bin/podman build --pull newer --tag localhost/mycontainer /var/home/roothome/build-mycontainer ; ignore_errors=no ; start_time=[Sat 2025-01-18 20:25:24 EST] ; stop_time=[Sat 2025-01-18 20:25:24 EST] ; pid=13279 ; code=exited ; status=125 }`

From the argv parameter we can see the command being run.  Let's run it manually.
`sudo /usr/bin/podman build --pull newer --tag localhost/mycontainer /var/home/roothome/build-mycontainer`

`Error: accepts at most 1 arg(s), received 2`

7. Reading the  [podman documentation for the --pull option](https://docs.podman.io/en/v5.3.0/markdown/podman-build.1.html#pull-policy ) we can see that the correct format is --pull=<value>.  Let's try that manually:

`sudo /usr/bin/podman build --pull=newer --tag localhost/mycontainer /var/home/roothome/build-mycontainer`

<succeeds and attempts to build the containerfile in /var/home/roothome/build-mycontainer>
(if the /var/home/roothome/build-mycontainer directory does not exist and contain a Containerfile to build, you will get an error such as `Error: context must be a directory: "/var/home/roothome/build-mycontainer"` but this is to be expected.)

### Expected behavior

Podman is expected to build the referenced Containerfile.   Specifically, podman-system-generator is expected to generate a valid ExecStart command for the `podman build` operation.  It should set ExecStart to:

`/usr/bin/podman build --pull=newer ...`

### Actual behavior

The resulting systemd Build unit service fails to run the `podman build` command with an error regarding parameters, because the omission of the expected equals sign after the "--pull" option results in an extra unknown parameter.  It is incorrectly setting ExecStart to:

`/usr/bin/podman build --pull newer ...`

(note the space instead of an equal sign after the --pull option)

### System details

QEMU
Fedora CoreOS Version: 41.20241215.3.0 (2025-01-06T19:34:31Z)

### Butane or Ignition config

```yaml
variant: fcos
version: 1.5.0

systemd:
  units:
    # Disables docker services completely (so podman is used instead)
    - name: docker.service
      mask: true
    # Enable podman auto-update timer
    - name: podman-auto-update.timer
      enabled: true

storage:
  directories:
    # Create directory for image building
    - path: /var/home/roothome/build-mycontainer
      mode: 0755
      user:
        name: root
      group:
        name: root

  files:
    # Create Custom Containerfile
    - path: /var/home/roothome/build-mycontainer/Containerfile
      contents:
        inline: | 
          # mycontainer Containerfile
          FROM docker.io/alpine:latest

    # Create Custom Container Image
    - path: /etc/containers/systemd/podman.myconatiner_img.build
      contents:
        inline: | 
          [Unit]
          Description=Container Image Build Service
          After=network-online.target podman.service
          Requires=podman.service network.target network-online.target

          [Build]
          ImageTag=localhost/mycontainer
          Pull=newer
          SetWorkingDirectory=/var/home/roothome/build-mycontainer
          TLSVerify=false
          
          [Install]
          WantedBy=default.target
```

### Additional information

Reading the [podman documentation for the --pull option](https://docs.podman.io/en/v5.3.0/markdown/podman-build.1.html#pull-policy ) we can see that the correct format is --pull=<value>.
