### ISSUE TITLE
SELinux issue

### ISSUE THREAD

**Issue by ahjohannessen** [coreos/fedora-coreos-tracker#1887]
### Describe the bug

Ran into the following this morning:

```
Mar 12 09:05:18 ilb01 ostree[479967]: Refreshing SELinux policy
Mar 12 09:05:19 ilb01 ostree[479977]: libsemanage.semanage_direct_get_module_info: Unable to open extra_binsbin module lang ext file at /etc/selinux/targeted/tmp/modules/400/extra_binsbin/lang_ext. (No such file or directory).
Mar 12 09:05:19 ilb01 ostree[479977]: semodule:  Failed!
Mar 12 09:05:19 ilb01 ostree[479967]: Refreshed SELinux policy in 261 ms
Mar 12 09:05:19 ilb01 ostree[479967]: error: Finalizing deployment: Finalizing SELinux policy: Child process exited with code 1
Mar 12 09:05:19 ilb01 systemd[1]: ostree-finalize-staged.service: Control process exited, code=exited, status=1/FAILURE
Mar 12 09:05:19 ilb01 systemd[1]: ostree-finalize-staged.service: Failed with result 'exit-code'.
```

resultated in machines kept rebooting.

This is when zincati/rpm-ostree trying to upgrade to 41.20250215.3.0 from 41.20250130.3.0

### Reproduction steps

Let rpm-ostree upgrade to 41.20250215.3.0 from 41.20250130.3.0

### Expected behavior

That it would not end up in this state.

### Actual behavior

Infinite loop of restarts failing

### System details

- VMWare esxi
- Fedora CoreOS 41.20250215.3.0

```
State: idle
BootedDeployment:
● fedora:fedora/x86_64/coreos/stable
                  Version: 41.20250130.3.0 (2025-02-17T11:42:32Z)
               BaseCommit: d881f2c35bdd4e90960a026b7a161bed82a660da71f484c97f0655776ed9307a
             GPGSignature: Valid signature by 466CF2D8B60BC3057AA9453ED0622462E99D6AD1
          LayeredPackages: dmidecode haproxy keepalived python unzip
```

**Comment by ahjohannessen** [comment]
I should note that it is just two machines that fail out of four that have similar setup. 

I use Ansible to set `sebool_haproxy_connect_any` for `haproxy`.

The tasks I use in Ansible to ensure that HAproxy can run properly is:

```yaml
- name: "Determine if haproxy has selinux permissions"
  ansible.builtin.command:
    getsebool haproxy_connect_any
  register: sebool_haproxy_connect_any
  changed_when: false

- name: "Enable haproxy_connect_any SELinux boolean"
  ansible.builtin.command:
    setsebool -P haproxy_connect_any 1
  when: sebool_haproxy_connect_any.stdout.find("off") != -1


- name: "Ensure haproxy log directory"
  ansible.builtin.file:
    path: "/var/lib/haproxy/dev"
    state: directory
    owner: haproxy
    group: haproxy
    mode: '755'

- name: "Ensure haproxy log socket"
  ansible.builtin.file:
    path: "/var/lib/haproxy/dev/log"
    owner: haproxy
    group: haproxy
    access_time: preserve
    modification_time: preserve
    state: touch

- name: "Setup systemd mount for haproxy"
  template:
    src: haproxy.mount.j2
    dest: "/etc/systemd/system/var-lib-haproxy-dev-log.mount"
    owner: root
    group: root
    mode: '644'

- name: Setup systemd service for haproxy
  template:
    src: haproxy.service.j2
    dest: /etc/systemd/system/haproxy.service
    owner: root
    group: root
    mode: '644'

- name: Ensure systemd haproxy mount is enabled
  systemd:
    name: "var-lib-haproxy-dev-log.mount"
    state: started
    enabled: yes
    daemon_reload: yes      

- name: Ensure systemd haproxy service is enabled
  systemd:
    name: haproxy
    state: started
    enabled: yes
    daemon_reload: yes
```
