### ISSUE TITLE
Rebase to fcos-42 failing due to git

### ISSUE THREAD

**Issue by tvannahl** [coreos/fedora-coreos-tracker#1904]
### Describe the bug

I do have git among my layered packages and its breaking the rebase.

### Reproduction steps

1. Install fcos-41
2. Add git to the layered packages (`rpm-ostree install git`)
3. rebase to fcos `next`

### Expected behavior

Rebase should succeed without error

### Actual behavior

Rebase fails

```
root@ophelia:~# systemctl stop zincati
root@ophelia:~# sudo rpm-ostree rebase "fedora/x86_64/coreos/next"
2 metadata, 0 content objects fetched; 788 B transferred in 1 seconds; 0 bytes content written
Checking out tree 0cec6ef... done
Enabled rpm-md repositories: fedora-cisco-openh264 updates fedora copr:copr.fedorainfracloud.org:owenh:micro-okd updates-archive
Importing rpm-md... done
rpm-md repo 'fedora-cisco-openh264' (cached); generated: 2024-08-21T16:04:02Z solvables: 3
rpm-md repo 'updates' (cached); generated: 2025-02-04T16:34:59Z solvables: 0
rpm-md repo 'fedora' (cached); generated: 2025-03-26T08:12:18Z solvables: 77006
rpm-md repo 'copr:copr.fedorainfracloud.org:owenh:micro-okd' (cached); generated: 2025-03-23T21:14:08Z solvables: 37
rpm-md repo 'updates-archive' (cached); generated: 2025-02-06T19:33:32Z solvables: 0
Resolving dependencies... done
error: Could not depsolve transaction; 1 problem detected:
 Problem: cannot install both git-core-2.49.0-1.fc42.x86_64 from fedora and git-core-2.48.1-3.fc42.x86_64 from @System
  - package git-2.49.0-1.fc42.x86_64 from fedora requires git-core = 2.49.0-1.fc42, but none of the providers can be installed
  - conflicting requests
```

### System details

Base metal x64

```
root@ophelia:~# rpm-ostree status -b
State: idle
AutomaticUpdatesDriver: Zincati
  DriverState: inactive
BootedDeployment:
● fedora:fedora/x86_64/coreos/testing
                  Version: 41.20250315.2.0 (2025-03-17T23:37:35Z)
               BaseCommit: f2f2f67cd2a1f1c3bf15fe288903bb4bee88c9b4f6a320d0d03fd84976d6a26c
             GPGSignature: Valid signature by 466CF2D8B60BC3057AA9453ED0622462E99D6AD1
      RemovedBasePackages: nfs-utils-coreos 1:2.8.1-7.rc2.fc41
          LayeredPackages: avahi borgbackup firewalld fish git microshift microshift-olm netatalk parted samba-client wget
```

### Butane or Ignition config

```yaml

```
