### ISSUE TITLE
Degraded RAID1 with LUKS fails to boot

### ISSUE THREAD

**Issue by chris-neely** [coreos/fedora-coreos-tracker#1916]
I apologize if this is not the appropriate place. I'm assuming this probably isn't an actual bug, but to make sure I figured I'd bring it up here because I've been testing a number of difference scenarios out and have not been able to find any other sources with users attempting or documenting the results of said scenario.

I'm using the following butane configuration on bare metal image:

```
boot_device:
  luks:
    tang:
      - url: http://
        thumbprint: 
  mirror:
    devices:
      - /dev/sda
      - /dev/sdb
```

If I set the second disk as the boot disk, it boots up fine, so the boot loader seems to be on both devices. If detach the first disk, with the second disk being the boot disk, the system wont boot. I've tried adding a blank disk and rebuilding it via mdadm and while that does work, and gets me back to bootable, It doesn't allow me to boot from the disk that I booted, which seems strange since the mirror: parameter puts the boot loader and all the required files on both drives.

Is this normal or expected? My goal is to have a mirror and LUKS configured on a bare metal server. 

![Image](https://github.com/user-attachments/assets/8b2fd9a0-5f3e-4d24-bf0b-099b288d5008)
