### ISSUE TITLE
/etc/sudoers.d/coreos-sudo-group is owned by uid 1000 should be 0

### ISSUE THREAD

**Issue by cdn-goose** [coreos/fedora-coreos-tracker#1949]
### Describe the bug

I’m seeing this problem on a newly built coreos live ISO (from stable branch) with an embedded IGN file where a user is added to the sudo group.

Seems to be related: [/etc/sudoers is owned by uid 1000, should be 0 · Issue #1 · coreos/fedora-coreos-config · GitHub](https://github.com/coreos/fedora-coreos-config/issues/1)

If I 

```sudo chown root:root /etc/sudoers.d/coreos-sudo-group```

 it works.

This IGN runs a simple script that asks users for some info, and then runs the installer. Unless I chown the sudoers file, sudo asks for a password (which works).

You need to sudo in order to do the actual install to disk:

  ```sudo coreos-installer install -n -i some.ign ${DEVICE}```

It’s my understanding that sudo should not ask for a password since the sudoers file has this entry in it:

%sudo ALL=(ALL) NOPASSWD: ALL

Workaround is to add this to the live iso IGN:
```
storage:
files:

   path: /etc/sudoers.d/coreos-sudo-group
     user:
       name: root
     group:
       name: root
```
Once the system is installed, the same issue is seen. (Passed in IGN to the installer needs the work around mentioned above).

### Reproduction steps

Build:
```
cosa init --branch=stable --force https://github.com/coreos/fedora-coreos-config
cosa fetch --with-cosa-overrides
cosa build --force
cosa buildextend-metal4k
cosa buildextend-metal
cosa buildextend-live
```
Into ISO --> embed IGN:
```
coreos-installer iso ignition embed -i first_stage.ign -o embedded.iso  <created ISO from build>
```
first_stage.ign  (generated from butane, verified good) has nothing more than creating a few users, and adding them to the sudo group. 

Yaml: 
```
variant: fcos
version: 1.5.0
passwd:
 users:
   - name: user1
     uid: 2000 
     shell: /usr/bin/bash
     password_hash: <hash>
     groups:
       - wheel 
       - sudo 

```

### Expected behavior

On live ISO boot terminal, user(s) in group 'sudo' should not have to type in password on sudo required commands. 

Shell scripts that are run on ISO boot with autologin from Live IGN embed that require sudo should not require shell interaction. 

Such as:  sudo coreos-installer install -n -i some.ign ${DEVICE} after some info gathering to create "some.ign" to pass into the coreos-installer. 

### Actual behavior

Any sudo required command requires a password, which from shell scripts create interaction at the shell. 

### System details

Bare metal ISO, Fedora 42

### Butane or Ignition config

```yaml

```
