### ISSUE TITLE
bug: cannot assign group "dialout" to user

### ISSUE THREAD

**Issue by mikyll** [coreos/fedora-coreos-tracker#1955]
### Describe the bug

I'm not able to add a user to group "dialout", via Ignition configuration. I have not tested with other _"non-custom groups"_ but probably the behaviour is the same.

### Reproduction steps

1. Download the ISO from https://builds.coreos.fedoraproject.org/prod/streams/stable/builds/42.20250427.3.0/x86_64/fedora-coreos-42.20250427.3.0-live-iso.x86_64.iso.
2. Boot the live image (I used VirtualBox).
3. Obtain the Ignition configuration (hosted locally or whatever): config1.ign and config2.ign, generated from Butane configurations provided below.
4. Run `sudo coreos-installer install /dev/sda --ignition-file <config_name>.ign --copy-network`.
5. Shutdown, remove the live and boot again.
6. The first boot process should fail with the log errors provided below.

### Expected behavior

I expect to be able to add `myuser` to group `dialout`.

### Actual behavior

When trying to add `myuser` to group `dialout`, I got:

- `useradd: group 'dialout' does not exist` when using `passwd.users.[].groups[]` in Butane/Ignition config;
- `groupadd: group 'dialout' already exists` if I try creating the group via `passwd.groups[]` in Butane/Ignition config.

Logs:

- config 1: adding user to group

    ```lang-none
    ...
    ignition[1195]: files: ensureUsers: op(2): [started] creating or modifying user "myuser"
    ignition[1195]: files: ensureUsers: op(2): executing: "useradd" "--root" "/sysroot" "--home-dir" "/home/myuser" "--create-home" "--password" "$y$j9T$tZyPwp1NEbj9P6WAv.F720$Rj9PJnLqoTph5k2Qd5hAPLF6Evsp9TEgCz5ZkmwMHT4" "--uid" "1001" "--groups" "sudo,dialout" "--shell" "/bin/bash" "myuser"
    ignition[1195]: files: ensureUsers: op(2): [failed]   creating or modifying user "myuser": exit status 6: Cmd: "useradd" "--root" "/sysroot" "--home-dir" "/home/myuser" "--create-home" "--password" "$y$j9T$tZyPwp1NEbj9P6WAv.F720$Rj9PJnLqoTph5k2Qd5hAPLF6Evsp9TEgCz5ZkmwMHT4" "--uid" "1001" "--groups" "sudo,dialout" "--shell" "/bin/bash" "myuser" Stdout: "" Stderr: "useradd: group 'dialout' does not exist\n"
    systemd[1]: ignition-files.service: Main process exited, code=exited, status=1/FAILURE
    ...
    systemd[1]: ignition-files.service: Failed with result 'exit-code'.
    ```

- config 2: creating group and adding user to group

    ```lang-none
    ignition[1193]: files: ensureGroups: op(1): [started] adding group "dialout" 
    ignition[1193]: files: ensureGroups: op(1): executing: "groupadd" "--root" "/sysroot" "--gid" "18" "--password" "*" "dialout"
    ignition[1193]: files: ensureGroups: op(1): [failed]   adding group "dialout": exit status 9: Cmd "groupadd" "--root" "/sysroot" "--gid" "18" "--password" "*" "dialout" Stdout: "" Stderr: "groupadd: group 'dialout' already exists\n"
    ...
    systemd[1]: ignition-files.service: Main process exited, code=exited, status=1/FAILURE
    systemd[1]: ignition-files.service: Failed with result 'exit-code'.
    systemd[1]: Failed to start ignition-files.service - Ignition (files).
    ```

### System details

- Release specs:
  - channel: `stable`
  - arch: `x86_64`
  - artifact: `metal`
  - format: `.iso`
- Fedora CoreOS version: `42.20250427.3.0`

Installed on VirtualBox

### Butane or Ignition config

```yaml
Config 1: adding user to group


variant: fcos
version: 1.6.0
passwd:
  users:
    - name: myuser
      # Password: mypassword
      password_hash: "$y$j9T$tZyPwp1NEbj9P6WAv.F720$Rj9PJnLqoTph5k2Qd5hAPLF6Evsp9TEgCz5ZkmwMHT4"
      groups:
        - sudo
        - dialout
      home_dir: /home/myuser
      shell: /bin/bash
      uid: 1001


Config 2: creating group and adding user to group


variant: fcos
version: 1.6.0
passwd:
  groups:
    - name: dialout
      gid: 18  # Standard dialout GID
  users:
    - name: myuser
      # Password: mypassword
      password_hash: "$y$j9T$tZyPwp1NEbj9P6WAv.F720$Rj9PJnLqoTph5k2Qd5hAPLF6Evsp9TEgCz5ZkmwMHT4"
      groups:
        - sudo
        - dialout
      home_dir: /home/myuser
      shell: /bin/bash
      uid: 1001
```

### Additional information

I've also posted the question on [Unix & Linux StackExchange](https://unix.stackexchange.com/q/794934/592830)

**Comment by mikyll** [comment]
@nhermosilla14 yes, I found a workaround, using a systemd unit and `usermod`. Here's an example (full Butane configuration):

```yaml
variant: fcos
version: 1.6.0
passwd:
  users:
    - name: myuser
      # Password: mypassword
      password_hash: "$y$j9T$tZyPwp1NEbj9P6WAv.F720$Rj9PJnLqoTph5k2Qd5hAPLF6Evsp9TEgCz5ZkmwMHT4"
      groups:
        - sudo
      home_dir: /home/myuser
      shell: /bin/bash
      uid: 1001

systemd:
  units:
    - name: add-myuser-to-dialout.service
      enabled: true
      contents: |
        [Unit]
        Description=Add myuser to dialout group
        Wants=sysinit.target
        After=sysinit.target
        Before=zincati.service
        ConditionPathExists=!/var/lib/%N.stamp

        [Service]
        Type=oneshot
        RemainAfterExit=yes
        ExecStart=/bin/sh -eux -c 'grep -qE "^dialout:" /etc/group || grep -E "^dialout:" /usr/lib/group >> /etc/group'
        ExecStart=/bin/sh -eux -c 'usermod -a -G dialout myuser'
        ExecStart=/bin/touch /var/lib/%N.stamp

        [Install]
        WantedBy=multi-user.target
```

I had also posted the question on Unix & Linux StackExchange, but with no luck: [Fedora CoreOS: how can I add a user to dialout group?](https://unix.stackexchange.com/questions/794934/fedora-coreos-how-can-i-add-a-user-to-dialout-group)
