### ISSUE TITLE
GrowFs Skips when use Butane sugar  s390x-zfcp

### ISSUE THREAD

**Issue by madhu-pillai** [coreos/fedora-coreos-tracker#1958]
During OCP installation with `multipath` enabled  CEX based Luks Encryption  Butane sugar `s390x-zfcp` config  fails to growfs which causing the device out of space before the final boot. 

[Butane_Sugar_ZFCP.log](https://github.com/user-attachments/files/20395926/Butane_Sugar_ZFCP.log)

```
variant: openshift
version: 4.19.0 
metadata:
  name: main-storage
  labels:
    machineconfiguration.openshift.io/role: master
boot_device:
  layout: s390x-zfcp
  luks:
    device: /dev/sda
    cex:
      enabled: true
openshift:
  fips: true 
  kernel_arguments:
    - rd.luks.key=/etc/luks/cex.key 
 ```
However when we use the luks `device: /dev/disk/by-label/root`  similar to below works fine and completes the installation.

```
variant: openshift  
version: 4.19.0  
metadata:  
  name: 99-master-s390x-cex-luks-config  
  labels:  
    machineconfiguration.openshift.io/role: master 
openshift:
  fips: true
  kernel_arguments:  
    - rd.luks.key=/etc/luks/cex.key  
storage:
  filesystems:
    - device: /dev/mapper/root
      format: xfs
      label: root
      wipe_filesystem: true
  luks:
    - cex: 
        enabled: true
      device: /dev/disk/by-label/root
      label: luks-root
      name: root
      wipe_volume: true
```

The logs which i captured is as follows.
