### ISSUE TITLE
write script to send fedmsg when we want a release artifact signed

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-tracker#198]
As part of the [Fedora Signing Discussion](https://github.com/coreos/fedora-coreos-tracker/issues/187) it was identified that we need to send a message when we want to get our artifacts signed in preparation for a release. The payload of the message needs to include the artifacts as well as the checksums (so the signer can check before creating signature). We believe the `meta.json` should suffice as the payload.

This script would need to be executed somewhere in our release process, or perhaps any time a release candidate becomes available so that all signatures are in place well in time before we do a release.

**Comment by puiterwijk** [comment]
Note that fedmsg is being replaced with fedora-messaging.
I think you should use the latter for any new code.

**Comment by dustymabe** [comment]
> Note that fedmsg is being replaced with fedora-messaging.
> I think you should use the latter for any new code.

Indeed that is defnitely the plan. The problem I have when describing *fedora messaging messages* is that there isn't a succinct way to do it like there was with *fedmsg*. I've just still been calling them *fedmsgs* because people know what you mean when you say it.

**Comment by dustymabe** [comment]
After some recent discussions there are actually a few different messages we probably want to send. Here is a proposal for now:

- `org.fedoraproject.prod.coreos.ostree`
    - gives information about an ostree commit that was just created
    - can be used to trigger signing an ostree commit
    - similar to [pungi-compose-ostree](https://fedora-fedmsg.readthedocs.io/en/latest/topics.html#pungi-compose-ostree) message today.

- `org.fedoraproject.prod.coreos.build.status.change`
    - shares information about status of the current coreos build in jenkins (moving through stages of pipeline, etc)
    - similar to [pungi-compose-status-change](https://fedora-fedmsg.readthedocs.io/en/latest/topics.html#pungi-compose-status-change)
    - should deliver the information in the meta.json from a fedora coreos pipeline run

Any other ones I'm missing?

**Comment by jlebon** [comment]
> `org.fedoraproject.prod.coreos.ostree`

Maybe let's split this out into two, e.g. `org.fedoraproject.prod.coreos.ostree.signing-request` and `org.fedoraproject.prod.coreos.ostree`? The former is for #200; signing an OSTree commit during the build process so we can include it in the image artifacts. The latter would be when the OSTree commit is available in the bucket proper, and signalling to releng to pull it into the unirepo?

Actually, we could also fold the `signing-request` one into `org.fedoraproject.prod.coreos.build.status.change` messages. Not sure if that's harder for releng though.

**Comment by dustymabe** [comment]
> > `org.fedoraproject.prod.coreos.ostree`
> 
> Maybe let's split this out into two, e.g. `org.fedoraproject.prod.coreos.ostree.signing-request` and `org.fedoraproject.prod.coreos.ostree`? The former is for #200; signing an OSTree commit during the build process so we can include it in the image artifacts. The latter would be when the OSTree commit is available in the bucket proper, and signalling to releng to pull it into the unirepo?
> 
> Actually, we could also fold the `signing-request` one into `org.fedoraproject.prod.coreos.build.status.change` messages. Not sure if that's harder for releng though.

yeah maybe we should just do that for all of these and re-use the state change messages. Actually I just looked a bit closer and the pungi messages have a status change and a phase change. I guess a new proposal would be:

- `org.fedoraproject.prod.coreos.build.stage.start`
    - shares information about the COSA build moving through the pipeline 
    - similar to [pungi-compose-phase-start](https://fedora-fedmsg.readthedocs.io/en/latest/topics.html#pungi-compose-phase-start)
    - should deliver the information in the meta.json from a fedora coreos pipeline run
    - can be used to trigger ostree commit signing
    - can be used to trigger artifact signing
    - can be used to trigger transfer ostree to unified repo

- `org.fedoraproject.prod.coreos.build.status.change`
    - shares information about status of the current coreos COSA build in jenkins (i.e. whether it failed or not)
    - similar to [pungi-compose-status-change](https://fedora-fedmsg.readthedocs.io/en/latest/topics.html#pungi-compose-status-change)
    - should deliver the information in the meta.json from a fedora coreos pipeline run

**Comment by jlebon** [comment]
So `org.fedoraproject.prod.coreos.build.status.change` would only actually be emitted at the end of builds with the final success/failure result? Minor bikeshed, though ISTM like those should be called e.g. `org.fedoraproject.prod.coreos.build.complete` or something if that's the case.

Anyway, SGTM!

**Comment by dustymabe** [comment]
> So `org.fedoraproject.prod.coreos.build.status.change` would only actually be emitted at the end of builds with the final success/failure result?

Yeah when it starts and when it finishes (or fails). 

I'll take this to fedora infra and see if they have any input.

**Comment by dustymabe** [comment]
> I'll take this to fedora infra and see if they have any input.

https://pagure.io/fedora-infrastructure/issue/7940

**Comment by jlebon** [comment]
I have a suggestion: I think we should make more explicit the difference between informational messages ("if anyone cares, our build has reached state $x") from messages requesting direct action from releng ("please do $x for me; I'll be waiting").

For informational events we can start with:
- build started
- build ended

And we can add more messages in the future about intermediate states if useful.

For requests, there are three main ones:
- OSTree commit signing
- Build artifact signing
    - These two requests would ideally happen on every build (see https://github.com/coreos/fedora-coreos-tracker/issues/200#issuecomment-500054869). In theory, build artifact signing could happen as part of a release only, but signing every build I think would help with e2e testing.
- OSTree commit import into unified repo
    - This request will only happen during a release.

---

Strawman for informational events:

```
topic: org.fedoraproject.prod.coreos.build.status.change
headers:
    build_id: ${build_id}
    stream: ${stream}
    basearch: ${basearch}
    status: (STARTED|FINISHED|...)
message:
    # if FINISHED
    result: (SUCCESS|FAILURE)
    # if SUCCESS
    build_dir: s3://.../${build_id}/${basearch}/
```

Strawman for OSTree commit signing request:

```
topic: org.fedoraproject.prod.coreos.build.request.ostree-sign
headers:
    build_id: ${build_id}
    stream: ${stream}
    basearch: ${basearch}
message:
    commit_object: s3://.../${build_id}/${basearch}/ostree-commit-object
    checksum: <SHA256>
```

Strawman for build artifact signing request:

```
topic: org.fedoraproject.prod.coreos.build.request.artifacts-sign
headers:
    build_id: ${build_id}
    stream: ${stream}
    basearch: ${basearch}
message:
    metadata: s3://.../${build_id}/${basearch}/meta.json
    checksum: <SHA256>
```

Strawman for OSTree commit import requests:

```
topic: org.fedoraproject.prod.coreos.build.request.ostree-import
headers:
    build_id: ${build_id}
    stream: ${stream}
    basearch: ${basearch}
message:
    commit: s3://.../ostree-commit.tar
    # checksum for integrity checking the tarball; but note the commit inside will already be signed
    checksum: <SHA256>
```

And we'll need matching messages from Fedora infra to signal to us when the request was fulfilled, maybe just reflecting back the same message but on topic `$topic.finished` with header `status: (SUCCESS|FAILURE)`?

Does that look sane?
/cc @bgilbert @sinnykumari @puiterwijk
