### ISSUE TITLE
Default reverse packet filter setting (rp_filter)

### ISSUE THREAD

**Issue by dghubble** [coreos/fedora-coreos-tracker#219]
In Container Linux, reverse packet filtering was set to strict (1). In Fedora CoreOS its set to loose (2). From readings, this may be typical in RH-family and by choice. Its nbd to switch back, just wanted to ask about it.

```
sudo sysctl net.ipv4.conf.default.rp_filter
net.ipv4.conf.default.rp_filter = 2
```

I noticed because Calico will error until the strictness is increased:

```
storage:
  files:
    - path: /etc/sysctl.d/reverse-path-filter.conf
      contents:
        inline: |
          net.ipv4.conf.all.rp_filter=1
```

Related: https://access.redhat.com/solutions/53031

```
rpm-ostree status
● ostree://fedora:fedora/x86_64/coreos/testing
                   Version: 30.20190716.1 (2019-07-16T20:04:14Z)
                    Commit: ff4803b069b5a10e5bee2f6bb0027117637559d813c2016e27d57b309dd09d6f
              GPGSignature: (unsigned)
```
