### ISSUE TITLE
Configure composite device

### ISSUE THREAD

**Issue by spaced** [coreos/fedora-coreos-tracker#275]
With coreos it was possible to define a different disk/partition for the mutable part:
https://coreos.com/os/docs/latest/root-filesystem-placement.html

use-case: a bare metal installation
- installation via pxe `coreos.inst.install_dev=sda`
- have a immutable (small) disk on `/dev/sda`
- mutable data `/var` should go to `/dev/sdb`

with fedora-coreos i can configure/mount `/var` with following ignition:
```
---
variant: fcos
version: 1.0.0

storage:
  disks:
    - device: /dev/sdb
      wipe_table: true
      partitions:
        - label: var
          type_guid: 4F68BCE3-E8CD-4DB1-96E7-FBCAF984B709
  filesystems:
    - path: "/var"
      device: "/dev/sdb1"
      format: "ext4"
      wipe_filesystem: true
      label: "var"
systemd:
  units:
    - name: var.mount
      enabled: true
      contents: |
        [Mount]
        What=/dev/disk/by-partlabel/var
        Where=/var
        Type=ext4
        Before=ostree-remount.service
        [Install]
        WantedBy=local-fs.target
```

it works but: Im not sure the `ostree-remount` stuff will skip or is not able to mount correctly `/var` i i will hit various side-effects later on.
