### ISSUE TITLE
First class support for systemd portable services via ignition (discuss)

### ISSUE THREAD

**Issue by keithy** [coreos/fedora-coreos-tracker#311]
This has been discussed in #37 as a means to provide system containers.

Systemd provides the containerisation features for Portable Containers, but lacks the transport layer. Therefore it would seem useful for ignition to add the missing piece.
```
systemd:
  portable_units:
    - name: health-check
      attached: true
      source: https://..../tar.gz
      verification:
        hash: sha512-xyz
```
In the meantime I propose a systemd unit that performs the same tasks, on first boot.
but invite a discussion as to where to put files until portables are officially supported.
