### ISSUE TITLE
ssh_authorized_keys: and no_create_home: true doesnt work

### ISSUE THREAD

**Issue by keithy** [coreos/fedora-coreos-tracker#316]
but it could

https://unix.stackexchange.com/a/422795

**Comment by keithy** [comment]
Workaround
(note: SSH still tries and fails to change directory to the non-existent users home directory)
```
    - name: sshd-config-dropins.service
      enabled: true
      contents: |
        [Unit]
        Description=Compose sshd_config
        ConditionFirstBoot=yes
        After=multi-user.target
        Before=boot-complete.target
        [Service]
        Type=oneshot
        ExecStart=-sh -c 'find /etc/ssh/sshd_config.d -type f -name *.conf -exec cat {} + >> /etc/ssh/sshd_config'
        [Install]
        WantedBy=multi-user.target
        RequiredBy=boot-complete.target 
```
drop in
```
    - path: /etc/ssh/sshd_config.d/extra_keys.conf
      mode: 0600
      user:
        id: 1000
      group:
        id: 1000
      contents:
        inline: |
          #
          # Added from ignition
          Match User *
              AuthorizedKeysFile  /etc/ssh/sshd_config.d/authorized_keys_%u
```
    - path: /etc/ssh/sshd_config.d/authorized_keys_goss-homeless
      mode: 0644
      user:
        id: 0
      group:
        id: 0
      contents:
        inline: |
          command="sudo /usr/local/lib/goss/pkg/usr/local/bin/goss -g /etc/goss/goss.yaml validate ${SSH_ORIGINAL_COMMAND}" ssh-ed25519 AAAA... ...bT bob@is.your.uncle
```
