### ISSUE TITLE
Boot / Ignition: Unable to download files with a server having static IP configuration

### ISSUE THREAD

**Issue by rbicker** [coreos/fedora-coreos-tracker#333]
Hi

I am trying to download a file during the ignition process.

Unfortunately this does not work. DNS resolution is failing:
![2019-12-18-181340_2252x95_scrot](https://user-images.githubusercontent.com/12236145/71107974-7051c300-21c2-11ea-864c-29afdf6b3729.png)

I then tried with the IP of the webserver instead of the dns name mirror.example.com, then I get another error stating that the network is unreachable.

When I omit the kublet file section, the server boots fine and I am able to download the file from the given URL using curl.

So I think the problem is, that the network configuration in my ignition configuration is being applied after the ignition process tries to download the given file(?)

```yaml
# my ignition configuration
variant: fcos
version: 1.0.0
passwd:
  users:
    - name: root
      ssh_authorized_keys:
        - ssh-rsa AAAAB3...
systemd:
  units:
    - name: kubelet.service
      enabled: true
      contents: |
        [Unit]
        Description=kubelet: The Kubernetes Node Agent
        Documentation=http://kubernetes.io/docs/

        [Service]
        ExecStart=/opt/bin/kubelet
        Restart=always
        StartLimitInterval=0
        RestartSec=10

        [Install]
        WantedBy=multi-user.target
storage:
  directories:
    - path: /opt/bin
      mode: 0644
  files:
    - path: /etc/NetworkManager/system-connections/eth0.nmconnection
      mode: 0600
      contents:
        inline: |
          [connection]
          id=Uplink
          type=802-3-ethernet
          autoconnect=true
          interface-name=eth0
          match-device=interface-name:eth0
          [ethernet]
          mac-address=00:50:56:b1:24:66
          [ipv4]
          method=manual
          addresses=10.223.112.221/24
          gateway=10.223.112.1
          dns=8.8.8.8;8.8.4.4;
          dns-search=example.local
    - path: /etc/hostname
      mode: 0644
      contents:
        inline: coreos01.example.local
    - path: /opt/bin/kubectl
      mode: 0755
      contents:
        source: http://mirror.example.com/bin/x86_64/k8s/kubectl
```

Thanks for your help.

**Comment by dustymabe** [comment]
> When I omit the kublet file section, the server boots fine and I am able to download the file from the given URL using curl.
> 
> So I think the problem is, that the network configuration in my ignition configuration is being applied after the ignition process tries to download the given file(?)

Correct. I just confirmed that without any networking configuration required (i.e. dhcp suffices) I am able to download a file:

```
INFO     : files: createFilesystemsFiles: createFiles: op(3): [started]  writing file "/sysroot/var/opt/bin/kubectl"    
INFO     : files: createFilesystemsFiles: createFiles: op(3): GET https://dustymabe.fedorapeople.org/kubectl: attempt #1
INFO     : files: createFilesystemsFiles: createFiles: op(3): GET result: OK                                            
INFO     : files: createFilesystemsFiles: createFiles: op(3): [finished] writing file "/sysroot/var/opt/bin/kubectl"    
```

using this basic fcct config:

```
variant: fcos
version: 1.0.0
passwd:
  users:
    - name: core
      ssh_authorized_keys:
        - ssh-rsa AAAA...
storage:
  directories:
    - path: /opt/bin
      mode: 0644
  files:
    - path: /opt/bin/kubectl
      mode: 0755
      contents:
        source: https://dustymabe.fedorapeople.org/kubectl
```

I don't know if applying the network configuration during ignition is supposed to work like that or not. @lucab @jlebon, do you know?
