### ISSUE TITLE
Best practices for delivering container content that executes on the host

### ISSUE THREAD

**Issue by cgwalters** [coreos/fedora-coreos-tracker#354]
As we emphasize containers, there are a variety of techniques for executing code on the host.  Package layering is one.

In OpenShift today, we have a pattern of privileged containers that execute some binaries on the host.

Recently however, this failed because running binaries targeting e.g. RHEL7 on a RHEL8 host may fail if they link to e.g. openssl.  A general best practice here is really that the binaries need to be targeting the same userspace as the host.

Here's a relevant commit: https://github.com/openshift/cluster-network-operator/pull/389

Further, I think we should move these binaries into e.g. `/run/bin` - if there's a higher level process that pulls the containers to a node on reboot (e.g. a systemd unit created via Ignition, or in the OpenShift case the kubelet), then having the binaries in `/run` helps ensure that if e.g. the container is removed, at least the binaries will go away on reboot.

That said...we may consider even shipping something like `/usr/bin/coreos-host-overlay install <name> <rootfs>` that assumes the host rootfs is mounted at `/host` and handles the case where e.g. a container delivering host binraies is upgraded before reboot.

(This problem set quickly generalizes of course to something like "transient RPMs")

**Comment by cgwalters** [comment]
To be clear, the result of this could be some documentation; or it could be code.  I think if we do nothing though, people are going to do manifestly bad things.

**Comment by cgwalters** [comment]
Yet another reason I'd like these binaries in `/run` is that eventually I'd like to have the binaries that come with the host be signed and do something like enforce that any privileged code executed from a *persistent* storage comes from signed binaries.

**Comment by danwinship** [comment]
See also https://issues.redhat.com/browse/SDN-695 for some older thoughts specifically on the deploying-CNI-plugins angle. We definitely need something simpler than what we're doing now.

oh... this is an FCOS bug and that link probably isn't public. Well, the suggestion was to have some sort of config somewhere with like

```
cniPlugins:
  - name: cni-default
    sourceImage: quay.io/openshift/origin-container-networking-plugins:4.3
    rhel7Plugins:
      - /usr/src/plugins/rhel7/bin/*
    rhel8Plugins:
      - /usr/src/plugins/rhel8/bin/*
    plugins:
      - /usr/src/plugins/bin/*
  - name: openshift-sdn
    sourceImage: quay.io/openshift/origin-sdn:4.3
    plugins: 
      - /opt/cni/bin/openshift-sdn
  - name: multus
    ...
```

and then something would know how to pull the binaries out of those images and ensure they got installed correctly.

re `/run/bin`, there is trickiness with how CNI works which is terrible but we may need to have the multus binary be in its own directory without any other binaries in it (to avoid confusing cri-o about when the CNI plugin is ready), and we need all of the other CNI plugins to be in a directory without any non-CNI-plugin binaries (to avoid privilege escalation via multus). So anyway, we may need `/run/multus/bin` and `/run/cni/bin` or `/run/bin/multus/` and `/run/bin/cni/`
