### ISSUE TITLE
Failed to boot if use /boot/ignition/config.ign

### ISSUE THREAD

**Issue by jjqq2013** [coreos/fedora-coreos-tracker#490]
Sorry I failed to boot, so I can not output `rpm-ostree status`, 
I am using https://builds.coreos.fedoraproject.org/prod/streams/stable/builds/31.20200505.3.0/x86_64/fedora-coreos-31.20200505.3.0-metal.x86_64.raw.xz

Just decompress it and dd copy to the disk, 
normally it boots well,

however, If I prepare a simple  /boot/ignition/config.ign, then it just hang there (and reboot again and again after 10? minutes). No any error message.

```
{
  "ignition": {
    "version": "2.1.1"
  },
  "passwd": {
    "users": [
      {
        "name": "core2",
        "sshAuthorizedKeys": [
          "ssh-rsa AAAA...."
        ]
      }
    ]
  }
}
```

It is generated with a yml
```
variant: fcos
version: 1.0.0
passwd:
  users:
    - name: core2
      ssh_authorized_keys:
        - "ssh-rsa AAAA..."
```

If I remove the passwd tree the it works:
```
{
  "ignition": {
    "version": "2.1.1"
  }
```
