### ISSUE TITLE
FCCT: Missing storage/filesystems documentation

### ISSUE THREAD

**Issue by remoe** [coreos/fedora-coreos-tracker#495]
It is not clear what "ignition" does here:

https://docs.fedoraproject.org/en-US/fedora-coreos/fcct-config/#_file_systems

For example when one has an external data disk defined like so on FCOS boot:

```yaml
variant: fcos
version: 1.0.0
storage:
  filesystems:
    - path: /var/mnt/drive0
      device: /dev/vdb
      format: ext4
```

After first boot the partition is created with ext4 filesystem. But what does "ignition" when the FCOS boot system is reprovisioned without the external data disk (attach existing disk) ? Does "ignition" reformat the existing partition? When yes, can one avoid this?
