### ISSUE TITLE
package layering fails on f32 base with modular packages

### ISSUE THREAD

**Issue by grantral** [coreos/fedora-coreos-tracker#525]
## Steps to reproduce
1. Install last stable stream; fedora-coreos-31.20200517.3.0-live.x86_64.iso
2. `$ sudo rpm-ostree install buildah -r`
3. `$ sudo rpm-ostree install flatpak -r`
4. `$ sudo rpm-ostree rebase fedora/x86_64/coreos/next -r`

## Expected behaviour
The system successfully reboots and runs on the next stream.

## Actual behaviour
```
Receiving objects: 99% (9825/9836) 1.0 MB/s 523.6 MB 
Receiving objects: 99% (9825/9836) 1.0 MB/s 523.6 MB... done
Checking out tree 08040be... done
Enabled rpm-md repositories: updates fedora
Updating metadata for 'updates'... done
rpm-md repo 'updates'; generated: 2020-06-05T01:26:33Z
Updating metadata for 'fedora'... done
rpm-md repo 'fedora'; generated: 2020-04-22T22:22:36Z
Importing rpm-md... done
Forbidden base package replacements:
  policycoreutils 3.0-2.module_f32+7989+651e8914 -> 3.0-2.fc32 (fedora)
This likely means that some of your layered packages have requirements on newer or older versions of some base packages. Doing `rpm-ostree cleanup -m` and `rpm-ostree upResolving dependencies... done
error: Some base packages would be replaced
```

### Ignition config
```
variant: fcos
version: 1.1.0
passwd:
  users:
    - name: core
      password_hash: $y$j9T$oUoFYoBD1fmR12XKbZOjU.$7gbf0M2XCYsUY.Njp9deA3leG/p1scY2a30cvBLs6J7
      ssh_authorized_keys:
        - ssh-rsa AAAAB3NzaC1yc...
storage:
  files:
    - path: /etc/ssh/sshd_config.d/03-enable-passwords.conf
      mode: 0644
      contents:
        inline: |
          # Fedora CoreOS disables SSH password login by default.
          # Enable it.
          # This file must sort before 04-disable-passwords.conf.
          PasswordAuthentication yes
```

### rpm-ostree status
```
State: idle
Deployments:
● ostree://fedora:fedora/x86_64/coreos/stable
                   Version: 31.20200517.3.0 (2020-06-01T17:15:29Z)
                BaseCommit: 967b7b8d624e6d10ff51c2e81ef198fae966c567ac2e9b479771c693d0987949
              GPGSignature: Valid signature by 7D22D5867F2A4236474BF7B850CB390B3C3359C4
           LayeredPackages: buildah flatpak

  ostree://fedora:fedora/x86_64/coreos/stable
                   Version: 31.20200517.3.0 (2020-06-01T17:15:29Z)
                BaseCommit: 967b7b8d624e6d10ff51c2e81ef198fae966c567ac2e9b479771c693d0987949
              GPGSignature: Valid signature by 7D22D5867F2A4236474BF7B850CB390B3C3359C4
           LayeredPackages: buildah
```

## Notes
1. `rpm-ostree` suggests using `rpm-ostree up`, but this command does not exist;
2. Output `rpm-ostree upResolving dependencies... done` is merged.
