### ISSUE TITLE
`man` is missing in f32

### ISSUE THREAD

**Issue by grantral** [coreos/fedora-coreos-tracker#534]
## Steps to reproduce
1. `$ toolbox --help`

## Actual behaviour
```
/usr/bin/toolbox: line 1615: exec: man: not found
```
### Ignition config
```
variant: fcos
version: 1.1.0
passwd:
  users:
    - name: core
      ssh_authorized_keys:
        - ssh-rsa AAAAB3NzaC1yc...
```

### rpm-ostree status
```
State: idle
Deployments:
● ostree://fedora:fedora/x86_64/coreos/next
                   Version: 32.20200601.1.1 (2020-06-03T02:26:26Z)
                    Commit: 08040bebbab87a3343a281f94bb68010df618eb6ce6ac3d4230d2595959b5da1
              GPGSignature: Valid signature by 97A1AE57C3A2372CCA3A4ABA6C13026D12C944D0
```
