### ISSUE TITLE
Trying to define a file system on a RAID storage device, but failed

### ISSUE THREAD

**Issue by skycastlelily2** [coreos/fedora-coreos-tracker#539]
Try to install the fedora-coreos-32.20200601.1.1-qemu.x86_64.qcow2  next stream with the following Ignition config,but  failed
```
variant: fcos
version: 1.0.0
passwd:
  users:
    - name: core
      ssh_authorized_keys:
          - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDTMN33vFBGNLlPju9KcKPYBjonumraOo86mJsT3wnQuJHVMrsU5XWR/In5zaLx/AxZTSoURWeUVWKwaVq2iAFUOmKk66Sr4M1qsytHUcOmGfb8EsxF3mwFSq8shOkNqQiZSD5EgbsxqUh3SSa8VrAmIkipA93Tpcwb+q0oPGg9tZqZVaFSi6pIEavLhKD+J908NiTVhIIUxdxxFUae4bUFms52rUTeoCtvZHIkYzwClYupNMU19srDBFEBBoXy12y/zOWgcI/nKrRXEo6W+/Z/PSq15x5bA7vINOmPwpcnkxyvFW8npCLkn0I48Ks3xZFJMgGOfMVcKeyTqQqeenzJQs77hZZKT5rPauMnQzm3rAKjcMoYLTe+RlNtch5wg2fwAM7qvAY5uX7wy8XhdUmK6J2SwziwQJ72TVLVLEEw+HJWpNGAGVGNTUKECbtF7TNCvuoWnRJxF/goShHs6GyE0pywIwbp7USxwzFgVcYA+xHVwbfb/kuvexThXUXfWTc= lnie@bogon

storage:
  disks:
  - 
    device: /dev/disk/by-id/ata-QEMU_HARDDISK_wwn-0x50014ee261e524
    wipe_table: true
    partitions:
    -
      label: "raid.1.1"
      number: 1
      size_mib: 6553
      start_mib: 0
  - device: /dev/disk/by-id/ata-QEMU_HARDDISK_wwn-0x50014ee0b8442c
    wipe_table: true
    partitions:
    - label: "raid.1.2"
      number: 1
      size_mib: 6553
      start_mib: 0
  - device: /dev/disk/by-id/ata-QEMU_HARDDISK_wwn-0x50014e2eb507fc
    wipe_table: false
    partitions:
    - size_mib: 0
      start_mib: 0
      label: var
  raid:
    - name: publicdata
      level: raid1
      devices:
      - /dev/disk/by-partlabel/raid.1.1
      - /dev/disk/by-partlabel/raid.1.2
  filesystems:
    - path: /var
      device: /dev/disk/by-partlabel/var
      format: xfs

    - path: /var/publicdata
      device: /dev/md/publicdata
      format: ext4
      label: PUB


systemd:
  units:
    -
      name: var.mount
      enabled: true
      contents: |
        [Unit]
        Before=local-fs.target
        [Mount]
        Where=/var
        What=/dev/disk/by-partlabel/var
        [Install]
        WantedBy=local-fs.target
```

```
Displaying logs from failed units: ignition-ostree-mount-firstboot-sysroot.service
ignition-ostree-mount-var.service
ostree-prepare-root.service
-- Logs begin at Sun 2020-06-14 09:11:06 UTC, end at Sun 2020-06-14 09:11:14 UTC. --
Jun 14 09:11:14 systemd[1]: Starting Ignition OSTree: Mount (firstboot) /sysroot...
Jun 14 09:11:14 ignition-ostree-mount-sysroot[611]: ignition-ostree-mount-sysroot: Failed to find /dev/disk/by-label/root
Jun 14 09:11:14 systemd[1]: ignition-ostree-mount-firstboot-sysroot.service: Main process exited, code=exited, status=1/FAILURE
Jun 14 09:11:14 systemd[1]: ignition-ostree-mount-firstboot-sysroot.service: Failed with result 'exit-code'.
Jun 14 09:11:14 systemd[1]: Failed to start Ignition OSTree: Mount (firstboot) /sysroot.
-- Logs begin at Sun 2020-06-14 09:11:06 UTC, end at Sun 2020-06-14 09:11:14 UTC. --
Jun 14 09:11:14 systemd[1]: Starting Mount OSTree /var...
Jun 14 09:11:14 ignition-ostree-mount-var[614]: /sysroot//ostree/boot.1/fedora-coreos/543ff2e25b851e504a2d171feff52881251c83d4fef2d70b61cfe547a0a6d790/0 is not a symlink
Jun 14 09:11:14 systemd[1]: ignition-ostree-mount-var.service: Main process exited, code=exited, status=1/FAILURE
Jun 14 09:11:14 systemd[1]: ignition-ostree-mount-var.service: Failed with result 'exit-code'.
Jun 14 09:11:14 systemd[1]: Failed to start Mount OSTree /var.
Jun 14 09:11:14 systemd[1]: ignition-ostree-mount-var.service: Triggering OnFailure= dependencies.
-- Logs begin at Sun 2020-06-14 09:11:06 UTC, end at Sun 2020-06-14 09:11:14 UTC. --
Jun 14 09:11:14 systemd[1]: Starting OSTree Prepare OS/...
Jun 14 09:11:14 ostree-prepare-root[612]: ostree-prepare-root: Couldn't find specified OSTree root '/sysroot//ostree/boot.1/fedora-coreos/543ff2e25b851e504a2d171feff52881251c83d4fef2d70b61cfe547a0a6d790/0': No such file or directory
Jun 14 09:11:14 systemd[1]: ostree-prepare-root.service: Main process exited, code=exited, status=1/FAILURE
Jun 14 09:11:14 systemd[1]: ostree-prepare-root.service: Failed with result 'exit-code'.
Jun 14 09:11:14 systemd[1]: Failed to start OSTree Prepare OS/.
Jun 14 09:11:14 systemd[1]: ostree-prepare-root.service: Triggering OnFailure= dependencies.
Press Enter for emergency shell or wait 4 minutes 30 seconds for reboot.     
 ```
Here is the output of journalctl -t ignition
```
 disks: createRaids: op(e): executing: "mdadm" "--create" "publicdata" "--force>
 disks: createRaids: op(e): [finished] creating "publicdata"
 disks: createFilesystems: op(f): [started]  waiting for devices [/dev/disk/by->
 disks: createFilesystems: op(f): [finished] waiting for devices [/dev/disk/by->
 disks: createFilesystems: created device alias for "/dev/disk/by-partlabel/var>
 disks: createFilesystems: created device alias for "/dev/md/publicdata": "/run>
 disks: createFilesystems: op(10): [started]  determining filesystem type of "/>
 disks: createFilesystems: op(10): op(11): [started]  determining filesystem ty>
 disks: createFilesystems: op(10): op(11): found  filesystem at "/dev/disk/by-p>
 disks: createFilesystems: op(10): op(11): [finished] determining filesystem ty>
 disks: createFilesystems: op(10): op(12): [started]  creating "xfs" filesystem>
 disks: createFilesystems: op(10): op(12): executing: "mkfs.xfs" "-f" "/run/ign>
 disks: createFilesystems: op(10): op(12): [finished] creating "xfs" filesystem>
 disks: createFilesystems: op(10): found  filesystem at "/dev/md/publicdata" wi>
 disks: createFilesystems: op(10): [finished] determining filesystem type of "/>
 disks: createFilesystems: op(13): [started]  creating "ext4" filesystem on "/r>
 disks: createFilesystems: op(13): executing: "mkfs.ext4" "-F" "-L" "PUB" "/run>
 disks: createFilesystems: op(13): [finished] creating "ext4" filesystem on "/r>
 disks: op(14): [started]  waiting for udev to settle
 disks: op(14): executing: "udevadm" "settle"
 disks: op(14): [finished] waiting for udev to settle
 disks: disks passed
 Ignition finished successfully
```

**Comment by bgilbert** [comment]
Your FCC looks okay to me.  Have you verified that `ata-QEMU_HARDDISK_wwn-0x50014e2eb507fc` is your boot device?  It looks like the start of the problem is:

```
ignition-ostree-mount-sysroot: Failed to find /dev/disk/by-label/root
```

and it seems possible that you've accidentally overwritten your boot device with one of the RAID partitions.

**Comment by skycastlelily2** [comment]
yes,that's the problem,sorry for having failed to notice it.
Btw,could I use software RAID storage device as the boot device?
I have tried with following FCC,but got an error:
[lnie@bogon ~]$ fcct --pretty --strict part2.yaml --output part2.ign
Error translating config: Error unmarshaling yaml: yaml: line 39: did not find expected key
```
variant: fcos
version: 1.0.0
passwd:
  users:
    - name: core
      ssh_authorized_keys:
          - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDTMN33vFBGNLlPju9KcKPYBjonumraOo86mJsT3wnQuJHVMrsU5XWR/In5zaLx/AxZTSoURWeUVWKwaVq2iAFUOmKk66Sr4M1qsytHUcOmGfb8EsxF3mwFSq8shOkNqQiZSD5EgbsxqUh3SSa8VrAmIkipA93Tpcwb+q0oPGg9tZqZVaFSi6pIEavLhKD+J908NiTVhIIUxdxxFUae4bUFms52rUTeoCtvZHIkYzwClYupNMU19srDBFEBBoXy12y/zOWgcI/nKrRXEo6W+/Z/PSq15x5bA7vINOmPwpcnkxyvFW8npCLkn0I48Ks3xZFJMgGOfMVcKeyTqQqeenzJQs77hZZKT5rPauMnQzm3rAKjcMoYLTe+RlNtch5wg2fwAM7qvAY5uX7wy8XhdUmK6J2SwziwQJ72TVLVLEEw+HJWpNGAGVGNTUKECbtF7TNCvuoWnRJxF/goShHs6GyE0pywIwbp7USxwzFgVcYA+xHVwbfb/kuvexThXUXfWTc= lnie@bogon

storage:
  disks:
  # This defines two partitions, each on its own disk. The disks are
  # identified by their WWN.
  - device: /dev/disk/by-id/ata-QEMU_HARDDISK_wwn-0x50014ee261e524
    wipe_table: true
    partitions:
    -
      # Each partition gets a human-readable label.
      label: "raid.1.1"
      # Each partition is placed at the beginning of the disk and is 64 GiB
      # long.
      number: 1
      size_mib: 6553
      start_mib: 0
  - device: /dev/disk/by-id/ata-QEMU_HARDDISK_wwn-0x50014ee0b8442c
    wipe_table: true
    partitions:
    - label: "raid.1.2"
      number: 1
      size_mib: 6553
      start_mib: 0

  # We use the previously defined partitions as devices in a RAID1 md array.
  raid:
    - name: publicdata
      level: raid1
      devices:
      - /dev/disk/by-partlabel/raid.1.1
      - /dev/disk/by-partlabel/raid.1.2

  - device: /dev/md/publicdata
    wipe_table: false
    partitions:
    - size_mib: 0
      start_mib: 0
      # We assign a descriptive label to the partition. This is important
      # for referring to it in a device-agnostic way in other parts of the
      # configuration.
      label: var

  filesystems:
    - path: /var
      device: /dev/disk/by-partlabel/var
      format: xfs


systemd:
  units:
    -
      # We need to create a systemd mount unit so that /var actually gets
      # mounted on /var.
      name: var.mount
      enabled: true
      contents: |
        [Unit]
        Before=local-fs.target
        [Mount]
        Where=/var
        What=/dev/disk/by-partlabel/var
        [Install]
        WantedBy=local-fs.target

    - name: serial-getty@ttyS0.service
      dropins:
      - name: autologin-core.conf
        contents: |
          [Service]
          # Override Execstart in main unit
          ExecStart=
          # Add new Execstart with `-` prefix to ignore failure
          ExecStart=-/usr/sbin/agetty --autologin core --noclear %I $TERM
          TTYVTDisallocate=no
 ```

**Comment by bgilbert** [comment]
`/boot` and `/boot/efi` can't be on a software RAID, and `/` can't be on a software RAID at the moment (#94).  But you can certainly create a software RAID data volume on the same disk as the boot disk.  The issue in the FCC above is that you've pasted your `raid` block into the middle of your `disks` block.

**Comment by skycastlelily2** [comment]
Hi,
Thanks a lot for your reply.

>The issue in the FCC above is that you've pasted your `raid` block into the middle of your `disks` block.

I put 'raid' into the middle because I want to create a partition on the software RAID disk,  it will fail with "/dev/md/publicdata not found" if I put raid before  "- device: /dev/md/publicdata",do you have any advice?

> But you can certainly create a software RAID data volume on the same disk as the boot disk. 

I tried with the following FCC ,but failed

```
storage:
  disks:
  # This defines two partitions, each on its own disk. The disks are
  # identified by their WWN.
  - device: /dev/disk/by-id/ata-QEMU_HARDDISK_wwn-0x50014ee261e524
    wipe_table: false
    partitions:
    - label: var
      number: 1
      size_mib: 10240
      start_mib: 1
    -
      # Each partition gets a human-readable label.
      label: "raid.1.1"
      # Each partition is placed at the beginning of the disk and is 64 GiB
      # long.
      number: 2
      size_mib: 10240
      start_mib: 10260

    - label: "raid.1.2"
      number: 3
      size_mib: 10240
      start_mib: 20600

  # We use the previously defined partitions as devices in a RAID1 md array.
  raid:
    - name: publicdata
      level: raid1
      devices:
      - /dev/disk/by-partlabel/raid.1.1
      - /dev/disk/by-partlabel/raid.1.2


  # The resulting md array is used to create an EXT4 file system.
  filesystems:
    - path: /var
      device: /dev/disk/by-partlabel/var
      format: xfs

    - path: /var/publicdata
      device: /dev/md/publicdata
      format: ext4
      label: PUB

```

```
[    3.225791] ignition[560]: disks: createPartitions: op(2): [failed]   partitioning "/run/ignition/dev_aliases/dev/disk/by-id/ata-QEMU_HARDDISK_wwn-0x50014ee261e524": Failed to pretend to create partitions. Err: exit status 4. Stderr: Could not create partition 1 from 2048 to 20973567
```

If I change the start_mib of first partition to 0,it will fail with 

```
partitioning "/run/ignition/dev_aliases/dev/disk/by-id/ata-QEMU_HARDDISK_wwn-0x50014ee261e524": Failed to pretend to create partitions. Err: exit status 4. Stderr: Could not create partition 2 from 21012480 to 41983999
```
