### ISSUE TITLE
forwarding NIC renaming udev rules from the initramfs

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-tracker#553]
There is a dracut arg called `ifname=` that will allow someone to dynamically create a udev rule to change the name of a NIC to whatever they would like it to be. For example I could tell the system to name NIC with MAC `12:34:56:78:9a:bc` to `infra` with `ifname=infra:12:34:56:78:9a:bc`.

This gets applied via [ifname-genrules.sh](https://github.com/dracutdevs/dracut/blob/5c3d0a96473ac339fa2d1b25213b8f301c1cfd0d/modules.d/40network/ifname-genrules.sh) from the `40network` dracut module which creates a rule in the initramfs like:

```
# cat /etc/udev/rules.d/80-ifname.rules
SUBSYSTEM=="net", ACTION=="add", DRIVERS=="?*", ATTR{address}=="12:34:56:78:9a:bc", ATTR{type}=="1", NAME="infra"
```

Since we persist other parts of the networking config from the initramfs (static IPs, hostname, etc), should we persist these udev rules as well? Or should we require a user to either write out the udev rule (or systemd link file) themselves OR add the `ifname=` karg so that it gets dynamically generated every time?

Just for posterity here is how to create a udev rule or systemd link file:

```
storage:
  files:
    - path: /etc/udev/rules.d/80-ifname.rules
      mode: 0644
      contents:
        inline: |
          SUBSYSTEM=="net", ACTION=="add", DRIVERS=="?*", ATTR{address}=="12:34:56:78:9a:bc", ATTR{type}=="1", NAME="infra"'
```

```
storage:
  files:
    - path: /etc/systemd/network/25-infra.link
      mode: 0644
      contents:
        inline: |
          [Match]
          MACAddress=12:34:56:78:9a:bc
          [Link]
          Name=infra
```

**Comment by dustymabe** [comment]
We discussed this in the [meeting today](https://lists.fedoraproject.org/archives/list/coreos@lists.fedoraproject.org/message/RKIU2F7NQHLLTPGWEFP3HXYMIVCRUJ4Y/).

It was a productive discussion, but we're still evaluating our current set of networking configuration hacks and if we want to bring something like this into the fold or if we want to draw a line somewhere. We'll take some time to do some more thought/investigation and revisit soon. Read full meeting log for more details!

**Comment by jlebon** [comment]
Had a chat with Dusty and Benjamin about this last week. I expressed some concerns about expanding the list of networking kargs we understand. Dusty pointed out that overall our automatic handling of these kargs is still necessary and is not obviated by the recent networking work like #554 

Specifically for `ifname=`, Dusty mentioned that it could be useful as a way to make it easier to configure other networking args. E.g. `ifname=foo:MAC ip=$ip:...:foo` so that it only turns on that specific interface.

Overall, I lean towards not special-handling it, so that users do have to explicitly also add a e.g. systemd link file. In RHCOS, there is at least one customer that did this. Though I don't feel strongly either way at this point.

**Comment by cgruver** [comment]
Good day all, I was just getting ready to test an iPXE boot & install with the karg being discussed here.

It's not clear from the conversation.  Will this karg be honored and persisted through the installation process to rename the network interface?

Relevant code snippet below.  The vars get filled in by a script which is creating an iPXE boot file named after the MAC of the boot NIC.  I want that NIC to be named `nic0`.

```
ifname=nic0:${NET_MAC_0} ip=${IP_01}::${LAB_GATEWAY}:${LAB_NETMASK}:${HOSTNAME}.${LAB_DOMAIN}:nic0:none nameserver=${LAB_NAMESERVER}
```

**Comment by dustymabe** [comment]
We discussed this during the [meeting today](https://lists.fedoraproject.org/archives/list/coreos@lists.fedoraproject.org/message/DSYDBJTYHFRTVLSC6OVEHT4SYXD3KHEA/).

```
  * AGREED: We haven't seen a lot of users needing this functionality
    just yet so we'd prefer to wait to add that functionality. What we
    have for propagating networking karg information a bit hacky, but is
    required for now in order to not require every user who needs static
    networking to specify networking information twice. We'd prefer to
    not further the behavior for now.  (dustymabe, 17:25:22)
```

**Comment by dustymabe** [comment]
@cgruver - your feedback would have been useful before the meeting today :smile: - that being said if we do find it's a popular request it would need to be reconsidered.

If you (anyone) find yourself in this situation there are a few categories you fall in to:

- you need networking in the initramfs (i.e. remote sources for ignition configs (OKD fits here))
    - in this case you can provide ip= args and ifname=args but you'll also need to create a file with your ignition configs to persist the naming into the real root.

```
ifname=nic0:${NET_MAC_0} ip=${IP_01}::${LAB_GATEWAY}:${LAB_NETMASK}:${HOSTNAME}.${LAB_DOMAIN}:nic0:none
```

and also

```
storage:
  files:
    - path: /etc/systemd/network/25-nic0.link
      mode: 0644
      contents:
        inline: |
          [Match]
          MACAddress=${NET_MAC_0}
          [Link]
          Name=nic0

```

- you don't need networking in the initramfs
    - in this case you can just provide all networking configuration via Ignition by writing out files
    - so you would create the .link file and also files under `/etc/NetworkManager/system-connections/`

**Comment by cgruver** [comment]
Yeah, I'm going to try to start attending your meetings since OKD and FCOS are working closely together.

The reason that this came up is the recent change that will affect how the NIC names are determined.  My first thought to mitigate it was to use the `ifname=` karg.  This is mainly because I'm doing automated UPI deployments of OKD with fixed IP addresses...  It's a data-center vs. cloud paradigm situation.

I think all of this could be mitigated if I knew how to create ignition config snippets and add them to the ignition config created by OpenShift Installer in an automated way.

To that end, any help you guys can provide would be appreciated.  I haven't found any good documentation that describes how to add to an existing ignition file with a mechanism that can be automated.  That would also simplify my single-node-cluster build as well.

**Comment by cgruver** [comment]
Off Topic...  Do you guys have a Slack channel?

**Comment by dustymabe** [comment]
> Yeah, I'm going to try to start attending your meetings since OKD and FCOS are working closely together.

+1

> 
> The reason that this came up is the recent change that will affect how the NIC names are determined. My first thought to mitigate it was to use the `ifname=` karg. This is mainly because I'm doing automated UPI deployments of OKD with fixed IP addresses... It's a data-center vs. cloud paradigm situation.

Yep. Makes sense!

> 
> I think all of this could be mitigated if I knew how to create ignition config snippets and add them to the ignition config created by OpenShift Installer in an automated way.
> 
> To that end, any help you guys can provide would be appreciated. I haven't found any good documentation that describes how to add to an existing ignition file with a mechanism that can be automated. That would also simplify my single-node-cluster build as well.

I automated this recently. It looks something like the following..

Create a `fcct-master.yaml` file like so:

```
# Merge some tweaks/bugfixes with the master Ignition config
variant: fcos
version: 1.1.0
ignition:
  config:
    merge:
      - local: ./files/master.ign
systemd:                        
  units:                        
  # we don't want docker starting
  # https://github.com/openshift/okd/issues/243
  - name: docker.service
    mask: true
storage:
  files:
    # Disable zincati, this should be removed in the next OKD beta
    # https://github.com/openshift/machine-config-operator/pull/1890
    # https://github.com/openshift/okd/issues/215
    - path: /etc/zincati/config.d/90-disable-feature.toml
      contents:
        inline: |
          [updates]
          enabled = false
```

Then do something like:

```
openshift-install create manifests --dir=files
openshift-install create ignition-configs --dir=files
cat fcct-master.yaml | fcct -d ./ -o ./files/master.ign
```

You can then use the ignition to bring up your UPI nodes. You can do the same for bootstrap.


> Off Topic... Do you guys have a Slack channel?

No, but we're on freenode in `#fedora-coreos`. Would love to have you join us there.
