### ISSUE TITLE
Where is sha256sum.txt?

### ISSUE THREAD

**Issue by kazuhisya** [coreos/fedora-coreos-tracker#584]
Hello,

I want a file with checksum like `sha256sum.txt` , but it doesn't seem to be provided by FCOS.
Is there a `sha256sum.txt` format instead of the `file://data:text/plain...` format?

Maybe we will be happy to be able to reference that file when automating downloads with Ansible (or other one).

like this:

```
 - name: download coreos kernel 
   get_url: 
     url: "{{ fcos.url }}/fedora-coreos-{{ fcos.version }}-live-kernel-x86_64" 
     dest: "/path/to/file/{{ fcos.version }}/fedora-coreos-{{ fcos.version }}-live-kernel-x86_64" 
     checksum: "sha256:{{ fcos.url }}/sha256sum.txt" 
```

Thanks
