### ISSUE TITLE
ign applied in Stable Stream, not in Next Stream

### ISSUE THREAD

**Issue by ivzhh** [coreos/fedora-coreos-tracker#620]
## Environments

Host: libvirt on Fedora 32 (`dnf` up-to-date)
Stable Stream: `fedora-coreos-32.20200824.3.0-qemu.x86_64.qcow2`
Next Stream: `fedora-coreos-32.20200907.1.0-qemu.x86_64.qcow2`

## Expected to see

Download Next Stream and start with following ign. Use `qemu-nbd` to mount the overlay `qcow2` file  to do facts check:

* `/mnt/nbd0p4/ostree/deploy/fedora-coreos/var/home/noname/.ssh/authorized_keys.d/ignition` contains ssh pubkey
* VM gets `192.168.0.133` IPv4 address

```yaml
variant: fcos
version: 1.0.0
storage:
  files:
    - path: /etc/NetworkManager/system-connections/enp1s0.nmconnection
      mode: 0600
      overwrite: true
      contents:
        inline: |
          [connection]
          type=ethernet
          id='Custom interface'
          interface-name=enp1s0

          [ethernet]
          #mac-address=<insert MAC address>

          [ipv4]
          method=manual
          addresses=192.168.0.133/24
          gateway=192.168.0.1
          dns=192.168.0.33;1.1.1.1;8.8.8.8
          dns-search=home;host
passwd:
  users:
    - name: noname
      password_hash: $y$j9T$f..W5mNdbCbv57Wbyf9YF1$U/LZGseRps6nPkr.aF1sAE0RaCAEHsWNhcWPvH8GyX4
      ssh_authorized_keys:
        - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJ8k2f+iGpYH/rzzmSAGxAJJIKDSqkmBgE3r141YpxSJ noname
      groups: [ sudo, docker ]
```

## Actual Behavior

With `Stable Stream`, it works as expected. With `Next Stream`, IP is assigned by DHCP and only ``/mnt/nbd0p4/ostree/deploy/fedora-coreos/var/home/core` exists.
