### ISSUE TITLE
Improve package layering UX

### ISSUE THREAD

**Issue by jlebon** [coreos/fedora-coreos-tracker#681]
This is a follow-up to #401. Fedora CoreOS now ships [with an archive repo](https://github.com/coreos/fedora-coreos-config/pull/673) which allows reliable package layering operations. However, there is still work remaining to make it easier to use. Right now, users have to create a systemd unit which runs `rpm-ostree install --reboot ...` which is not great.

Specifically:
1. we need a better interface for package layering via Ignition, whether that be via file drop-ins translated by FCOS glue code, or drop-ins read by rpm-ostree directly (related: https://github.com/coreos/rpm-ostree/issues/2326)
2. we want "Ignition-like" semantics for the extensions: this means that the extensions ideally should be present from the get go in the real root on the first boot (or we should fail the boot if something goes wrong)
3. we need an FCC-friendly way to specify these packages, either directly having users use the file drop-in interface or via sugar

The sugar that was proposed in #401 was something like:

```yaml
extensions:
- usbguard
```

**Comment by jlebon** [comment]
> we want "Ignition-like" semantics for the extensions: this means that the extensions ideally should be present from the get go in the real root on the first boot (or we should fail the boot if something goes wrong)

So one way to do this is to call out to rpm-ostree before switchroot to do the install and then doing [`livefs`](https://github.com/coreos/rpm-ostree/pull/2293) (though I think we can do even better here since the sysroot isn't technically in use yet -- we'd need to enhance rpm-ostree for that).

A first cut would be to just reboot for now, the way we will do for kargs. This won't work for live ISO/PXE though.

**Comment by jlebon** [comment]
For https://github.com/coreos/fedora-coreos-tracker/issues/767, note that these improvements should keep modular extensions in mind.

**Comment by LorbusChris** [comment]
Just an idea: Afaik, *COS extensions today aren't something that RPM is aware of.
I wonder whether we could re-use `Group`s defined in the spec for this (although I believe `Group`s have been deprecated in RPM in Fedora)

**Comment by jlebon** [comment]
Another path that came up in [today's community meeting](https://meetbot-raw.fedoraproject.org/teams/fedora_coreos_meeting/fedora_coreos_meeting.2021-06-16-16.30.html) related to this is embedding packages at install time so that they can be layered offline on first boot. See https://github.com/coreos/fedora-coreos-tracker/issues/862#issuecomment-862575548.

**Comment by alvarlagerlof** [comment]
Has there been any progress on this?

**Comment by dustymabe** [comment]
As an intermediate step to having Ignition support doing package layering in the initramfs we could take what is in [the docs](https://docs.fedoraproject.org/en-US/fedora-coreos/os-extensions/) and modify it slightly and add it to the host. Then users could define their own RPMs in a dropin. Here's the full example:

```
variant: fcos
version: 1.3.0
storage:
  files:
    - path: /etc/systemd/system/rpm-ostree-install.service.d/rpms.conf
      mode: 0644
      contents:
        inline: |
          [Service]
          Environment=RPMS="foo bar baz"
systemd:
  units:
    - name: rpm-ostree-install.service
      enabled: true
      contents: |
        [Unit]
        Description=Layer additional rpms
        Wants=network-online.target
        After=network-online.target
        # We run before `zincati.service` to avoid conflicting rpm-ostree transactions.
        Before=zincati.service
        ConditionPathExists=!/var/lib/%N.stamp
        [Service]
        Type=oneshot
        RemainAfterExit=yes
        ExecStart=/usr/bin/rpm-ostree install --apply-live --allow-inactive $RPMS
        ExecStart=/bin/touch /var/lib/%N.stamp
        [Install]
        WantedBy=multi-user.target
``` 

The proposal is that `rpm-ostree-install.service` is shipped in the base layer of FCOS and the user only has to create the dropin with the RPMs they want to layer in their Butane/Ignition config.

Of course we can also add some sort of `ConditionPathExists=` to make sure it only ran when users really wanted layered RPMs.

**Comment by xanderificnl** [comment]
> 

I was having some issues with rpm-ostree seemingly being killed/locked files (/etc/passwd) etc. There is already an issue about that _somewhere_ on this issue tracker.

For now I've settled on using this for deployments:

- prevents double running rpm-ostree-installer@'s
- reboots after every install (considering it's only intended for new deployments, I felt it was acceptable) to prevent the /etc/passwd lockings

```yaml
variant: fcos
version: 1.5.0
storage:
  directories:
    - path: /var/cache/rpm-ostree-install
systemd:
  units:
   - name: rpm-ostree-install@.service
      enabled: true
      contents: |
        [Unit]
        Description=Layer %i with rpm-ostree
        Wants=network-online.target
        After=network-online.target
        Before=zincati.service
        ConditionPathExists=!/var/cache/rpm-ostree-install/%i.stamp

        [Service]
        Type=oneshot
        RemainAfterExit=yes
        ExecStart=/usr/bin/flock /var/cache/rpm-ostree-install/.lock -c "/usr/bin/rpm-ostree install --assumeyes --idempotent --reboot --allow-inactive %i | tee /var/cache/rpm-ostree-install/%i.stamp"

        [Install]
        WantedBy=multi-user.target
    - name: rpm-ostree-install@fish.service
      enabled: true
    - name: rpm-ostree-install@neovim.service
      enabled: true
    - name: rpm-ostree-install@htop.service
      enabled: true
```
