### ISSUE TITLE
Bare Metal Provisioning failure (no bootloader installed)

### ISSUE THREAD

**Issue by bnordgren** [coreos/fedora-coreos-tracker#683]
**Describe the bug**
Provisioning a bare metal Dell PowerEdge T310 from the console does not result in a bootable system, and there's precious little in the way of information as to why. All items specified in the ignition file have been accomplished by the provisioner. The system just acts like there's no bootloader.

**Reproduction steps**
1. Run coreos-installer /dev/sda with ignition file produced from the following fcc.
2. reboot (let it provision)
3. reboot again, no system.

**Expected behavior**
I expect it to boot.

**Actual behavior**
Machine complains there is no boot media and tries to PXE boot. No boot media is recognized in BIOS mode or UEFI mode.

**System details**
 - Bare Metal Dell PowerEdge T310
 - Three 8Tb disks, assembled into RAID 5, used as root drive. One of them is /dev/sda (installation target).
 - FCOS install media: 32.20201104.3.0-live

**Ignition config**
```
variant: fcos
version: 1.2.0
passwd:
  users:
    - name: core
      password_hash: "<stuff>"
      ssh_authorized_keys:
        - "ssh-ed25519 <more stuff> bryce@spiffster"
storage:
  disks:
    - device: /dev/disk/by-id/wwn-0x5000c500c72d8b34
      wipe_table: true
      partitions:
        - label: raid.dev.1
          number: 2
          size_mib: 0
          start_mib: 0
          type_guid: A19D880F-05FC-4D3B-A006-743F0F84911E
    - device: /dev/disk/by-id/wwn-0x5000c500c72e7394
      wipe_table: true
      partitions:
        - label: raid.dev.2
          number: 2
          size_mib: 0
          start_mib: 0
          type_guid: A19D880F-05FC-4D3B-A006-743F0F84911E
    - device: /dev/disk/by-id/wwn-0x5000c500c72eb52e
      wipe_table: true
      partitions:
        - label: raid.dev.3
          number: 1
          size_mib: 0
          start_mib: 0
          type_guid: A19D880F-05FC-4D3B-A006-743F0F84911E
  raid:
    - name: enterprise
      level: raid5
      devices:
      - /dev/disk/by-partlabel/raid.dev.1
      - /dev/disk/by-partlabel/raid.dev.2
      - /dev/disk/by-partlabel/raid.dev.3
  filesystems:
    - device: /dev/md/enterprise
      format: ext4
      wipe_filesystem: true
      label: root
```

**Additional Information** 
Booting from the install media again (using it as a system rescue disk), I can see it made the raid. It also formatted it ext4. The base of this RAIDed root filesystem has:
* boot (empty)
* lost+found (duh)
* ostree/deploy/fedora-coreos/deploy/<hash>/etc/shadow has the hashed password
* ostree/deploy/fedora-coreos/var/home/core/.ssh/authorized_keys.d/ignition has the provided ssh key.

As far as I can tell it did everything I told it do except make the system bootable. It's really weird to have an empty boot directory. Do I need to factor that out as its own partition? 

It's a headless home file/print server, and I'm unwilling to have it down for too long. The primary advantage of CoreOS would be the rpm-ostree updates. If no solution is rapidly forthcoming, Plan B is to just put Silverblue on it, even though I don't need a console.

**Comment by jlebon** [comment]
That config is RAID'ing the root filesystem only onto all the disks, in the process overwriting the boot disk.

There is [work outstanding](https://github.com/coreos/fedora-coreos-config/pull/718) for native RAID support for all partitions (see also https://github.com/coreos/enhancements/blob/master/os/20201103-full-disk-raid.md). The work is mostly focused on RAID1, though it should be possible to re-use the same mechanism to RAID1 the boot partition and MBR, and RAID5 the rootfs by customizing the Ignition config appropriately (/cc @bgilbert to confirm this).

**Comment by bgilbert** [comment]
Right.  After that work lands, you'd do something like this:

```yaml
variant: fcos
version: 1.3.0-experimental
boot_device:
  mirror:
    devices:
      - /dev/disk/by-id/wwn-0x5000c500c72d8b34
      - /dev/disk/by-id/wwn-0x5000c500c72e7394
      - /dev/disk/by-id/wwn-0x5000c500c72eb52e
storage:
  raid:
    - name: md-root
      level: raid5
```

For now, you can RAID only the root filesystem, which of course won't allow the system to continue booting if the boot disk fails.  Make sure not to use `wipe_table` on the boot disk, but you can still use `wipe_partition_entry` on the `root` partition.
