### ISSUE TITLE
Allow zip as a compression method

### ISSUE THREAD

**Issue by nsmith5** [coreos/fedora-coreos-tracker#721]
**Describe the enhancement**
zip compression would make it easy to install tools like nomad (packaged with zip from upstream). Ideally I'd like something like

```
files:
  - path: /usr/bin/nomad
    mode: 0644
    contents:
      compression: zip
      source: https://releases.hashicorp.com/nomad/0.11.8/nomad_0.11.8_linux_amd64.zip
```

to work.
