### ISSUE TITLE
disks: createPartitions: op(2) [failed] partitioning

### ISSUE THREAD

**Issue by lessfoobar** [coreos/fedora-coreos-tracker#776]
**Describe the bug**

1.862546 localhost ignition[509]: disks: createPartitions: op(2) [failed] partitioning "/run/ignition/dev_aliases/dev/sda": Failed to pretend to create partitions. Err: exit status 4. Stderr: Could not create partition 1 from 20971520 to 2047

**Reproduction steps**

Embed the ignition in the iso: 
- `coreos-installer iso ignition embed -f -i example.ign fedora-coreos-33.20210117.3.2-live.x86_64.iso `
- Use the iso to boot with device `/dev/sda` fedora-coreos-33.20210117.3.2-live.x86_64.iso
- > change the ssh keys

**Ignition config**

```
variant: fcos
version: 1.3.0

### create remote user and password
passwd:
  users:
    - name: core
      uid: 5000
      no_user_group: true
      shell: /bin/bash
      ssh_authorized_keys:
        - ssh-ed25519 XXXXXXXX

storage:

### Create root partition with 10GB and give all the rest to var
  disks:
    - device: /dev/sda
      partitions:
        - label: root
          number: 4
        - label: var
          number: 0
          size_mib: 0
          start_mib: 10240

### encrypt root and var           
  luks:
    - name: root
      label: luks-root
      device: /dev/disk/by-partlabel/root
      key_file:
        inline: 'test'
      wipe_volume: true
    - name: var
      label: luks-var
      key_file:
        inline: 'testtest'
      device: /dev/disk/by-partlabel/var
      wipe_volume: true

### set the filesystems to xfs
  filesystems:
    - device: /dev/mapper/root
      format: xfs
      path: /
      label: root
      wipe_filesystem: true
    - device: /dev/mapper/var
      format: xfs
      path: /var
      label: VAR
      wipe_filesystem: true
      with_mount_unit: true


### configure files
  files:

### set hostname
    - path: /etc/hostname
      mode: 0644
      contents:
        inline: fcos.domain

### configure swap on zram        
    - path: /etc/systemd/zram-generator.conf
      mode: 0644
      contents:
        inline: |
          # This config file enables a /dev/zram0 device with the default settings
          [zram0]

### Add a bash profile that tells systemd to not use a pager for output.          
    - path: /etc/profile.d/systemd-pager.sh
      mode: 0644
      contents:
        inline: |
          # Tell systemd to not use a pager when printing information
          export SYSTEMD_PAGER=cat

### Raise kernel console logging level to hide audit messages from the console         
    - path: /etc/sysctl.d/20-silence-audit.conf
      mode: 0644
      contents:
        inline: |
          # Raise console message logging level from DEBUG (7) to WARNING (4)
          # to hide audit messages from the interactive console
          kernel.printk=4

### configuring Zincati rollout wariness
    - path: /etc/zincati/config.d/51-rollout-wariness.toml
      contents:
        inline: |
          [identity]
          rollout_wariness = 0.25

### configure systemd     
systemd:

### kernel argument so that the machine uses cgroups v2
  units:
    - name: cgroups-v2-karg.service
      enabled: true
      contents: |
        [Unit]
        Description=Switch To cgroups v2
        # We run after `systemd-machine-id-commit.service` to ensure that
        # `ConditionFirstBoot=true` services won't rerun on the next boot.
        After=systemd-machine-id-commit.service
        ConditionKernelCommandLine=systemd.unified_cgroup_hierarchy
        ConditionPathExists=!/var/lib/cgroups-v2-karg.stamp

        [Service]
        Type=oneshot
        RemainAfterExit=yes
        ExecStart=/bin/rpm-ostree kargs --delete=systemd.unified_cgroup_hierarchy
        ExecStart=/bin/touch /var/lib/cgroups-v2-karg.stamp
        ExecStart=/bin/systemctl --no-block reboot

        [Install]
        WantedBy=multi-user.target

    - name: var.mount
      enabled: true
      contents: |
        [Mount]
        What=/dev/disk/by-label/VAR
        Where=/var
        Type=xfs

        [Install]
        WantedBy=local-fs.target
```
I have tested with: 

```
        - label: var
          number: 5
```
also with removal of the number line.

Still the same error occurs.

**Expected behavior**

the expected behavior is to have root FS with 10GB and var to take the rest of the disk

**Actual behavior**
Failing on the initialization process 

**System details**
 - Tested on both Bare Metal/QEMU/
 - Fedora CoreOS 33.20210117.3.2-live.x86_64.iso
