### ISSUE TITLE
root partition is not resizing to fill the disk

### ISSUE THREAD

**Issue by amphineko** [coreos/fedora-coreos-tracker#825]
**Describe the bug**
CoreOS is not resizing the root partition as expected.

**Reproduction steps**
1. Create a new VM with a 64GB disk
2. `sudo coreos-installer install /dev/sda -I <ignition_url> -n` 
3. `reboot`

**Expected behavior**
The partition with `root` label should be resized to fill the disk.

**Actual behavior**
Two partitions with the same `root` partlabel exists.

**System details**
 - Hyper-V on Windows Server 2019
 - `fedora-coreos-33.20210426.3.0-live.x86_64.iso`

**Ignition config**

```
variant: fcos
version: 1.3.0
storage:
  disks:
    - device: /dev/sda
      partitions:
        - label: root
          resize: true
  files:
    - path: /etc/NetworkManager/conf.d/unmanaged-cni.conf
      mode: 0644
      contents:
        inline: |
          [keyfile]
          unmanaged-devices=interface-name:cni*;interface-name:flannel*;interface-name:veth*
    - path: /etc/sysctl.d/20-silence-audit.conf
      mode: 0644
      contents:
        inline: |
          kernel.printk=4
```

**Additional information**
```
[core@localhost ~]$ df -h
Filesystem      Size  Used Avail Use% Mounted on
devtmpfs        3.9G     0  3.9G   0% /dev
tmpfs           3.9G     0  3.9G   0% /dev/shm
tmpfs           1.6G   17M  1.6G   2% /run
tmpfs           4.0M     0  4.0M   0% /sys/fs/cgroup
/dev/sda4       2.4G  1.9G  582M  77% /sysroot
tmpfs           3.9G     0  3.9G   0% /tmp
/dev/sda3       364M   90M  251M  27% /boot
tmpfs           790M     0  790M   0% /run/user/1000
[core@localhost ~]$ lsblk -o +partlabel
NAME   MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT PARTLABEL
sda      8:0    0   64G  0 disk
|-sda1   8:1    0    1M  0 part            BIOS-BOOT
|-sda2   8:2    0  127M  0 part            EFI-SYSTEM
|-sda3   8:3    0  384M  0 part /boot      boot
|-sda4   8:4    0  2.4G  0 part /sysroot   root
`-sda5   8:5    0 61.1G  0 part            root
sr0     11:0    1  770M  0 rom
```
