### ISSUE TITLE
Fedora 34 does not wait for network for Clevis/Tang LUKS encryption

### ISSUE THREAD

**Issue by rugk** [coreos/fedora-coreos-tracker#827]
**Describe the bug**

**Reproduction steps**
The usual stuff from what I try the whole time:
https://discussion.fedoraproject.org/t/no-network-ipv4-connectivity-via-ethernet-at-first-boot-for-luks-clevis-setup/29260/9
TL;DR: Encrypt your root FS with LUKS and Clevis/Tang.

And it’s draining it does not work… yet again…

See https://github.com/coreos/fedora-coreos-tracker/issues/692

**Expected behavior**

**Actual behavior**
A clear and concise description of what actually happened.

**System details**
 - Bare Metal
 -  tested with current testing and stable branch
 - next seems to be currently: ` fedora-coreos-34.20210503.1.0-metal.x86_64.raw.xz` 

**Ignition config**
still the same [as initially said](https://discussion.fedoraproject.org/t/no-network-ipv4-connectivity-via-ethernet-at-first-boot-for-luks-clevis-setup/29260):
```yml
variant: fcos
version: 1.3.0
# ...
  luks:
    # encrypted root
    - name: root
      label: luks-root
      device: /dev/disk/by-partlabel/root
      clevis:
        tpm2: false
        threshold: 1
        tang:
          - url: # …
            thumbprint: # …
      wipe_volume: true
  # resize root volume to 100% of disk
  # https://docs.fedoraproject.org/en-US/fedora-coreos/storage/#_sizing_the_root_partition
storage:
  disks:
    - device: /dev/nvme0n1
      partitions:
        - label: root
          number: 4
          # 0 means to use all available space
          size_mib: 0
          resize: true
  filesystems:
    - device: /dev/mapper/root
      format: btrfs
      wipe_filesystem: true
      label: root
```

Ignition v2.9

**Additional information**

Here more system logs: https://gist.github.com/rugk/039ac5c0fb6ad7590ff88de82277c898
I have more logs, so if you need them, I' could share them privately.

Maybe it’s the same as [my post before](https://discussion.fedoraproject.org/t/no-network-ipv4-connectivity-via-ethernet-at-first-boot-for-luks-clevis-setup/29260/9?u=rugk)? For logs of that, see the gist: https://gist.github.com/rugk/44b4f02f3133130a8f0973ae46cd79b8 (previously reported as https://github.com/coreos/fedora-coreos-tracker/issues/814)
