### ISSUE TITLE
user home directory is not created

### ISSUE THREAD

**Issue by amphineko** [coreos/fedora-coreos-tracker#831]
**Describe the bug**
Home directories for users is not created.

**Reproduction steps**
1. `sudo coreos-installer install /dev/sda -I <ignition_url> -n`
2. `reboot`

**Expected behavior**
CoreOS should create a directory for the provisioned user

**Actual behavior**
Unable to ssh into the system. Logging in on the console prompts that the home directory for the user was not created. It might be the reason that the SSH keys weren't deployed?

![image](https://user-images.githubusercontent.com/2821430/118229714-0e80b000-b4bf-11eb-9f1e-62fbf0579e84.png)
![image](https://user-images.githubusercontent.com/2821430/118229738-1a6c7200-b4bf-11eb-85ff-31717bdfcdba.png)

**System details**
 - Hyper-V on Windows Server 2019
 - `fedora-coreos-33.20210426.3.0-live.x86_64.iso`

**Ignition config**
``` yaml
variant: fcos
version: 1.3.0
passwd:
  users:
    - name: amphineko
      groups:
        - wheel
        - sudo
      password_hash: "<password hash here>"
      ssh_authorized_keys:
        - "ssh-ed25519 <public key here>"
storage:
  disks:
    - device: /dev/sda
      partitions:
        - label: root
          number: 4
          resize: true
        - label: var
          start_mib: 16384
  files:
    - path: /etc/NetworkManager/conf.d/unmanaged-cni.conf
      mode: 0644
      contents:
        inline: |
          [keyfile]
          unmanaged-devices=interface-name:cni*;interface-name:flannel*;interface-name:veth*
    - path: /etc/sysctl.d/20-silence-audit.conf
      mode: 0644
      contents:
        inline: |
          kernel.printk=4
  filesystems:
    - device: /dev/disk/by-partlabel/var
      format: xfs
      path: /var
```
