### ISSUE TITLE
Vultr OS Images are labelled ".dev" and thus have auto-updating disabled

### ISSUE THREAD

**Issue by arianvp** [coreos/fedora-coreos-tracker#845]
**Describe the bug**
When I boot up a "Stable" Fedora CoreOS image on Vultr it shows up as a `.dev` build:
```
$ ssh core@********
Fedora CoreOS 33.20210513.dev.0
```

and as a result auto-updates seem to be disabled:
```
$ cat /etc/zincati/config.d/95-disable-on-dev.toml 
# https://github.com/coreos/fedora-coreos-tracker/issues/212
updates.enabled = false

```

**Reproduction steps**
1.  Start up a Vultr Fedora CoreOS box
2. The machine never updates

**Expected behavior**
The image it uses is a production build, and thus supports updates

**Actual behavior**
The image is a development build

**System details**
 - Vultr
 - Fedora CoreOS 33.20210513.dev.0

**Ignition config**
```
variant: fcos
version: 1.1.0
passwd:
  users:
    - name: core
      ssh_authorized_keys:
        - ssh-rsa AAAAB3NzaC1yc2EAAAAD
```

**Additional information**
Add any other information about the problem here.
