### ISSUE TITLE
Ignition: Disable generation of `30-ignition_config_info.issue` and `30-ssh_authorized_keys.issue`.

### ISSUE THREAD

**Issue by xlejo** [coreos/fedora-coreos-tracker#857]
Hi. I possible disable the generation of .issue files by Ignition? The only way to remove it was removing in a service. 

> Maybe the label is `kind/question` but i cannot change it.

```yaml
- name: init-installation.service
  enabled: true
  contents: |
  [Unit]
  Description=Delete generate issue by Ignition
  ConditionFirstBoot=yes
  After=systemd-machine-id-commit.service
  ConditionPathExists=!/var/lib/init-installation.stamp
  [Service]
  Type=oneshot
  RemainAfterExit=yes
  ExecStart=/bin/sh -c 'rm -f /etc/issue.d/*ignition_config_info.issue'
  ExecStart=/bin/sh -c 'rm -f /etc/issue.d/*ssh_authorized_keys.issue'
  [Install]
  WantedBy=multi-user.target
```
I know it's not in the most elegant way, but it works.

I try deleting with `files` but maybe the generation for `30-ignition_config_info.issue` and `30-ssh_authorized_keys.issue` is after the Ignition provisioning.

```yaml
storage:
  files:
    - path: /etc/issue.d/30_ignition_config_info.issue    
      mode: 0644    
      contents:    
        inline:   
    - path: /etc/issue.d/30_ssh_authorized_keys.issue    
      mode: 0644    
      contents:    
        inline: 
```

Thanks!

**Comment by jlebon** [comment]
> Hi. I possible disable the generation of .issue files by Ignition? The only way to remove it was removing in a service.

You should be able to disable the two services which generate them: `coreos-check-ignition-config.service` and `coreos-check-ssh-keys.service`.

However sadly, `enabled: false` does not currently work, so you have to use this workaround: https://github.com/coreos/fedora-coreos-tracker/issues/392#issuecomment-849356269.

**Comment by dustymabe** [comment]
Since this isn't a bug I'm going to close this out, but please do let us know if the suggestion that @jlebon made helps you.

**Comment by xlejo** [comment]
> > Hi. I possible disable the generation of .issue files by Ignition? The only way to remove it was removing in a service.
> 
> You should be able to disable the two services which generate them: `coreos-check-ignition-config.service` and `coreos-check-ssh-keys.service`.
> 
> However sadly, `enabled: false` does not currently work, so you have to use this workaround: [#392 (comment)](https://github.com/coreos/fedora-coreos-tracker/issues/392#issuecomment-849356269).

With `mask: true` works perfect!

```yaml
systemd:
  units:
    - name: coreos-check-ignition-config.service
      mask: true
    - name: coreos-check-ssh-keys.service
      mask: true
```
