### ISSUE TITLE
Adding Clevis tang encryption to separate /var partition via Ignition fails subsequent boot

### ISSUE THREAD

**Issue by MisterWS** [coreos/fedora-coreos-tracker#958]
**Describe the bug**
Trying to add Clevis-backed encryption to both /root and separate /var partitions results in initial boot succeeding, but following boot-ups fail.

**Reproduction steps**
1. Install CoreOS using the attached FCC config (converted to Ignition)
2. Initial boot up succeeds - both /root and /var are set up, and system boots successfully.
3. Reboot the machine (e.g. using `sudo reboot`)

**Expected behavior**
Machine reboots successfully, with both encrypted partitions mounted.

**Actual behavior**
Machine hangs during subsequent reboots - waiting indefinitely for `A start job is running for /dev/mapper/var`

**System details**
 - Bare Metal / QEMU tested
 - Fedora CoreOS 34.20210821.3.0 (stable stream)

**Ignition config**
````yaml
variant: fcos
version: 1.4.0
kernel_arguments:
  should_not_exist:
    - console=ttyS0,115200n8
passwd:
  users:
    - name: core
      groups:
        - docker
      ssh_authorized_keys:
        - ssh-rsa ...
boot_device:
  mirror:
    devices:
      - /dev/sda
      - /dev/sdb
  luks:
    tang:
      - url: ...
        thumbprint: ...
storage:
  disks:
    - device: /dev/sda
      partitions:
        - label: root-1
          size_mib: 10240
        - label: var-1
    - device: /dev/sdb
      partitions:
        - label: root-2
          size_mib: 10240
        - label: var-2
  raid:
    - name: md-var
      level: raid1
      devices:
        - /dev/disk/by-partlabel/var-1
        - /dev/disk/by-partlabel/var-2
  luks:
    - name: var
      device: /dev/md/md-var
      clevis:
        tang:
          - url: ...
            thumbprint: ...
  filesystems:
    - device: /dev/mapper/root
      label: root
      format: btrfs
      wipe_filesystem: true
    - device: /dev/mapper/var
      path: /var
      label: var
      format: btrfs
      wipe_filesystem: true
      with_mount_unit: true
````

**Additional information**
After initial boot (but before any reboot), running `systemctl status systemd-cryptsetup@var.service` reveals the following logs:

````
systemd-cryptsetup@var.service: Found dependency on sockets.target/start
systemd-cryptsetup@var.service: Found dependency on bootupd.socket/start
systemd-cryptsetup@var.service: Found dependency on sysinit.target/start
systemd-cryptsetup@var.service: Found dependency on systemd-pstore.service/start
systemd-cryptsetup@var.service: Found dependency on var.mount/start
systemd-cryptsetup@var.service: Found dependency on blockdev@dev-mapper-var.target/start
systemd-cryptsetup@var.service: Found dependency on systemd-cryptsetup@var.service/start
systemd-cryptsetup@var.service: Job remote-fs-pre.target/start deleted to break ordering cycle starting with systemd-cryptsetup@var.service/start
````

**Comment by MisterWS** [comment]
From troubleshooting so far, by removing the references to clevis in the LUKS section for var, the system boots normally (resorting to generating a random keyfile, and placing it at /etc/luks/var on the root partition).

**Comment by jlebon** [comment]
I think what's going on here is that `systemd-pstore.service` [uses](https://github.com/systemd/systemd/blob/99db797bc612c0c3b43240800946a9500bc39de5/units/systemd-pstore.service.in#L23) `StateDirectory`, which implicitly gives it something equivalent to `RequiresMountsFor=/var` and so it's ordered after `var.mount`. Unless you're actually using `systemd-pstore.service`, can you try masking the unit?

**Comment by cgwalters** [comment]
Hmm, this seems to have sailed right by our LUKS testing because `ConditionDirectoryNotEmpty=/sys/fs/pstore` means that service doesn't run everywhere - in fact, I'm not getting `/sys/fs/pstore` even with `cosa run --uefi`.  But presumably bare metal has it.

Agree masking pstore is probably a valid workaround, but I think there are two things here:

IMO it's a bug for services (particularly systemd upstream ones) to use `StateDirectory` but be `WantedBy=sysinit.target`.  I think `systemd-pstore.service` should be at least `part of basic.target`. Will file an issue or PR.

The other thing we should do here is adding LUKS + UEFI into our CI.  It may be that e.g. libvirt-uefi is explicitly adding persistent variables in a way we're not with our qemu code.

**Comment by cgwalters** [comment]
Regression from https://github.com/systemd/systemd/commit/167241912f51fbc0d7d0869b9af34c15b5ecc4b6 looks like.

**Comment by cgwalters** [comment]
> because ConditionDirectoryNotEmpty=/sys/fs/pstore means that service doesn't run everywhere - in fact, I'm not getting /sys/fs/pstore

OK I didn't think about this carefully enough, the condition is checking whether the directory is *empty* not whether it's mounted.  And so it will only trigger if something is actually in the pstore, which looks like it would happen on things like MCE errors or kernel panics (but I didn't get data into the pstore by synthesizing a panic, need to investigate).

Also looking at `sysinit.target` issues, it looks like journald is also part of that as expected.

So the real problem here comes into play with `remote-fs-pre.target` for Clevis+tang, not just LUKS - `remote-fs-pre.target` is a whole separate thing in `man bootup`.  It's a bit unfortunate that just encrypting `/var` doesn't work whereas encrypting all of `/` will just because we mount `/` in the initramfs, but defer `/var` to post-switchroot and that creates a totally different dependency chain.

**Comment by MisterWS** [comment]
> Unless you're actually using `systemd-pstore.service`, can you try masking the unit?
Apologies for such a long time for me to respond. I've attempted using the workaround suggested by @jlebon above by adding the following to my Ignition config...
```yaml
systemd:
  units:
    - name: systemd-pstore.service
      mask: true
```
...but the same issue occurs; the machine boots successfully on first boot, but subsequent restarts fail, with the same errors shown.

@cgwalters - from your comments above, do you have any thoughts about a possible fix?
